### ISSUE TITLE
Trigger build pipeline and pass variable

### ISSUE THREAD

**Issue by rmohare** [maikvandergaag/msft-extensions#100]
Hello! 

I have a build pipeline and it has a variable that is used as part of the build to determine what exactly to build. I don't see any way to pass that directly as part of this trigger task.

**Comment by maikvandergaag** [comment]
That isn't in the features at this moment. Will have a look to at it to the task, and mark this issue as a feature request

**Comment by danieleusebio** [comment]
Hi,
Great plugin and for me very usefull. 
I have the same need.It were great if we could pass environment variables(or pipeline variables) to the downstream pipeline. Those variables will match with the variables (or a subset of them) defined in the downstream pipeline.
Thanks in advance.

**Comment by maikvandergaag** [comment]
Will look into this. So the feature should be triggering a pipeline and setting the variables?
