### ISSUE TITLE
Authentication can now be only using a client ID and a secret

### ISSUE THREAD

**Issue by djpirra** [maikvandergaag/msft-extensions#101]
Authentication can now be only using a client ID and a secret ID correct? Can the plugin be updated?

**Comment by maikvandergaag** [comment]
Will update the plugin end off july / beginning of august as I'm now in between houses.

**Comment by jayendranarumugam** [comment]
@maikvandergaag  While enhancing pls note that all the operations are not supported by Service Principal
Please read https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#service-principal-vs-master-account
