### ISSUE TITLE
PowerBI failing in DevDemo environment same is working fine with Dev Environment

### ISSUE THREAD

**Issue by SuryakiranAS** [maikvandergaag/msft-extensions#102]
PowerBI deployment failing in DevDemo environment with below error, Please suggest solution to fix the issue, Please feel free for any logs or clarifications.

Write-Error : A positional parameter cannot be found that accepts argument 'System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument 'System.Management.Automation.MethodInvocationException: Exception calling "Open" with "2" argument(s): "Could not find file '/home/md/E:\Agent\B3A1\_work\r29\a\Artifacts\Drop\Release\package\Toyota.Gts.AppDB\PowerBiReports\Average Peak Usage test.pbix'." ---> System.IO.FileNotFoundException: Could not find file '/home/md/E:\Agent\B3A1\_work\r29\a\Artifacts\Drop\Release\package\Toyota.Gts.AppDB\PowerBiReports\Average Peak Usage test.pbix'.

Thanks in advance.

**Comment by maikvandergaag** [comment]
it seems that is can not find the file that you want to publish. Are you using a different agent than with de environment that is working

**Comment by SuryakiranAS** [comment]
All environment deployment are using single agent.

**Comment by maikvandergaag** [comment]
Please make sure you are referencing the correct file, and that the file is available for your agent. As the exeption mentioned it cannot find the file.
