### ISSUE TITLE
Trigger Azure DevOps Pipeline: A parameter cannot be found that matches parameter name 'UseBasicParsing'.

### ISSUE THREAD

**Issue by osydoran** [maikvandergaag/msft-extensions#103]
I'm getting the following error when trying to run 'Trigger Azure DevOps Pipeline' task in Azure DevOps:
A parameter cannot be found that matches parameter name 'UseBasicParsing'.

**Comment by maikvandergaag** [comment]
Still the same issue?

**Comment by osydoran** [comment]
Yes, but I think this parameter is deprecated so can be removed from 'run-release.ps1' or 'run-build.ps1'.

**Comment by maikvandergaag** [comment]
Should be updated in a couple of moments
