### ISSUE TITLE
Power BI Service Connection in DevOps is failing

### ISSUE THREAD

**Issue by tadlags** [maikvandergaag/msft-extensions#105]
My Power Bi Service Connection is failing? I am able to connect successfully using a Azure Resource Manager connection but the Power BI Action does not recognize the ARM connection. It seems to want a Power BI Service Connection. Is this related to djpirra's comment below #101? Am I doing something wrong or do I need to wait for the update?

**Comment by maikvandergaag** [comment]
You will need to use the Power BI Service Connection to establish a connection to powerbi
