### ISSUE TITLE
Update Power Bi file Name through CI/CD

### ISSUE THREAD

**Issue by ManikantaNani** [maikvandergaag/msft-extensions#108]
HI,
I have Different Environments(Dev,QC,Prod).I am able to publish files in Dev workspace and Qc workspace.Problem facing in Prod workspace. In prod I have different clients and their own datasets.  We have to  publish all client power Bi files into one Prod workspace.

Challenges which i am facing in Power BI CI/CD.
1)I am able to publish and update Data source connection but unable to change file name according to clients in same workspace.

Could you please help to solve this issue.

**Comment by maikvandergaag** [comment]
I will check if this is possible. To be sure I'm getting your question. You want to update the report name after it has been published?

Or do you want to update the name while publishing?

**Comment by ManikantaNani** [comment]
I have to update report name while publishing.

**Comment by ManikantaNani** [comment]
I have to update report name and connection string  while publishing into wokrspace

**Comment by maikvandergaag** [comment]
Oke, you are mentioning the report name, does this also include the dataset?

**Comment by ManikantaNani** [comment]
Yes maikvandergaag
