### ISSUE TITLE
Support for Service Principal

### ISSUE THREAD

**Issue by Nhubbers** [maikvandergaag/msft-extensions#112]
Great extension, is it possible to authenticate using Service Principal?

**Comment by maikvandergaag** [comment]
Hi,

I think you mean the PowerBI Actions  extensions, Since I created the extensions there has been some updates on the authentication methods for the api. I have scheduled a update were I will be updating the authentication methods.

**Comment by dodgy99** [comment]
This would be a great addition as we will soon be moving to use service principal authentication.

**Comment by RoyLofthus** [comment]
We are in the initial stages of setting up CD to PowerBI.com and would like to use SPN.

**Comment by maikvandergaag** [comment]
I understand, will try to do it as soon as possible.

**Comment by datasharkNL** [comment]
Would be a great addition :)

**Comment by dodgy99** [comment]
I've been unable to fix my intermittent issue getting the AAD token for the master user. I'm going to wait until we can use a service principal to authenticate.

Do you have any idea of timescale on when you think you can do this? Would be great

**Comment by dodgy99** [comment]
Hi @maikvandergaag , eagerly awaiting any updates :)

Raised issue #111 not long ago and after trying everything we can think of the standard authentication method is still intermittently failing. Decided to wait for this feature and use Service Principal Authentication.

**Comment by maikvandergaag** [comment]
Been working on the authentication steps yesterday. I will need to check if all actions still work with a service principal token.

**Comment by maikvandergaag** [comment]
I have a beta running. If there are testers please let me know and send me your organization id

**Comment by dodgy99** [comment]
Hi @maikvandergaag 

I'm afraid I can't give you my organisation ID for testing but once made generally available will try it out straight away.

**Comment by dodgy99** [comment]
Hi @maikvandergaag 
Any update on when it will be GA? Greatly appreciated.

**Comment by maikvandergaag** [comment]
Not yet, hope to make it GA next week

**Comment by maikvandergaag** [comment]
I have published it to the marketplace
