### ISSUE TITLE
Ability to publish workspace changes to app

### ISSUE THREAD

**Issue by mwc360** [maikvandergaag/msft-extensions#113]
I love the idea of introducing release mgmt to publishing PBIX files but after it gets publish there should be an additional action to be able to update the app associate with the workspace, otherwise this is a manual step.

**Comment by maikvandergaag** [comment]
Could you alliterate more on that? Sounds like a interesting action

**Comment by mwc360** [comment]
when talking about release management in Power BI, the final production release step for any enterprise deployment is to re-publish the workspace app. The app is what makes the content consumable to end users. Without that function there will always be the manual step of re-publishing the app. Without that this extension only serves the purpose of landing PBIXs into the production staging area (workspaces). Thx!

**Comment by maikvandergaag** [comment]
Hi,

that's sounds like a cool feature then. I will check if that is possible. Could we maybe have a short conversation for me to be able to implement the right thing?

I am now working on service principal support and after that this will be one of the new features

**Comment by mwc360** [comment]
Sure - i'd be happy to help provide use case examples/requirements.
