### ISSUE TITLE
MFA authentication

### ISSUE THREAD

**Issue by marinrodrigo** [maikvandergaag/msft-extensions#115]
Hello!!!

I'm trying to use PowerBIActions and I'm getting the erros below:

##[error]Exception calling "AcquireToken" with "3" argument(s): "missing_federation_metadata_url: Federation Metadata Url is missing for federated user. This user type is unsupported."

![image](https://user-images.githubusercontent.com/29734135/66348986-2d57b180-e92e-11e9-9c15-fd82db960cfa.png)

I follow all the steps correctly, except one: My company uses MFA authentication for AAD.

Is there a way to use PowerBIActions in this scenario?

Thanks!!!

**Comment by maikvandergaag** [comment]
Yes, there is another way. It is under development at this moment. With that scenario you will use a Service Principal. If you want to use the beta release I can give you access.

**Comment by marinrodrigo** [comment]
Hi, there!

Yes, please! That would be awesome! 

Thank you so much!

**Comment by maikvandergaag** [comment]
If you give me your organization id I can share the beta extension with you

**Comment by marinrodrigo** [comment]
I couldn't find the ID. Are you able to give access with the URL? I have two:
https://dev.azure.com/rmarin2/
https://dev.azure.com/ValeAAS/

If it is not possible, can you please tell me where I can find it? Sorry for not having it.

Thanks!

**Comment by maikvandergaag** [comment]
Those are your IDs ;). Will try to add you tomorrow

**Comment by marinrodrigo** [comment]
Great!!! Thank you!!!

**Comment by maikvandergaag** [comment]
It is published to the marketplace

**Comment by marinrodrigo** [comment]
Thank you!!!
