### ISSUE TITLE
##[error]The variables can not be found on the definition: , , 

### ISSUE THREAD

**Issue by lou8566** [maikvandergaag/msft-extensions#116]
In the Build Definition, On the Variables Tab I added two variables:

versionnumber 1.0.0
devopspat ***

In the Tasks, I added the Version Number Counter task, under the build solution task and linked the version variable and the PAT using the variables set up.

The Build process fails at the Version number counter task with the following error:
##[error]The variables can not be found on the definition: , ,

**Comment by maikvandergaag** [comment]
Could you share some screenshots

**Comment by lou8566** [comment]
Here is a screen shot of the variables.
![Variables](https://user-images.githubusercontent.com/3045049/66512349-b691f400-eaa6-11e9-9960-376ab7c77063.png)

Here is the Version number Counter Task
![Task](https://user-images.githubusercontent.com/3045049/66512530-299b6a80-eaa7-11e9-916f-6942bd639eb7.png)
![Version Number Mapping](https://user-images.githubusercontent.com/3045049/66512673-6f583300-eaa7-11e9-89c3-16458668c009.png)
![PAT Mapping](https://user-images.githubusercontent.com/3045049/66512677-70896000-eaa7-11e9-8d80-3f293a967feb.png)

**Comment by maikvandergaag** [comment]
The value for "saved version variable" should be the name of the variable and not the value. So in your example it should be "versionnumber"

**Comment by lou8566** [comment]
Nope, that doesn't work. Same Result.

**Comment by maikvandergaag** [comment]
could you share screenshots after the last change?

**Comment by camilopedroso** [comment]
I'll try to help!
You must create a variable first! Follow these steps.

Cheers!

![var_01](https://user-images.githubusercontent.com/872336/72998148-aad00080-3dfd-11ea-843b-6a5444595a9e.png)
![var_02](https://user-images.githubusercontent.com/872336/72998150-aad00080-3dfd-11ea-99f3-d74d05128b0a.png)
![var_03](https://user-images.githubusercontent.com/872336/72998152-ab689700-3dfd-11ea-9d0e-88a9985db1f0.png)
![var_04](https://user-images.githubusercontent.com/872336/72998154-ab689700-3dfd-11ea-918d-0e82ca302cc7.png)
![var_05](https://user-images.githubusercontent.com/872336/72998156-ab689700-3dfd-11ea-92a8-070be6cc58ab.png)
![var_06](https://user-images.githubusercontent.com/872336/72998157-ac012d80-3dfd-11ea-9748-9f743f05beca.png)
