### ISSUE TITLE
Version number counter task fails - The variables can not be found on the definition: , , 

### ISSUE THREAD

**Issue by dlaskarzhevsky** [maikvandergaag/msft-extensions#117]
Parameters used:

![image](https://user-images.githubusercontent.com/53105481/66865235-d1f87580-ef64-11e9-8cd0-f5c5be8e7828.png)

$(Version) is set to 3.0.0

It appears that variable was read sucessfully but failed to update:

![image](https://user-images.githubusercontent.com/53105481/66864996-5dbdd200-ef64-11e9-946c-820b15231a07.png)

**Comment by maikvandergaag** [comment]
try adding the variable name without $(). That should do the trick

**Comment by dlaskarzhevsky** [comment]
That worked. Thanks.
