### ISSUE TITLE
Incorrect assignment of UpdateMajorVersion parameter

### ISSUE THREAD

**Issue by dlaskarzhevsky** [maikvandergaag/msft-extensions#118]
Line 7 in run-task.ps1:

$UpdateMinorVersion = Get-VstsInput -Name UpdateMajorVersion

Results in empty $UpdateMajorVersion parameter:

![image](https://user-images.githubusercontent.com/53105481/66872651-7a620600-ef74-11e9-8599-2395de18777c.png)

**Comment by maikvandergaag** [comment]
issue should be fixed in new release
