### ISSUE TITLE
Remote pipeline set to 'Specify at the time of release creation'

### ISSUE THREAD

**Issue by chakaSA** [maikvandergaag/msft-extensions#119]
Hi There

I have a remote pipeline where I need to specify the build at release time and would like to trigger this one as well.

I tried and it fails with the message 'Cannot retrieve the default version for artifact 'Release' because default version type is 'selectDuringReleaseCreationType'.

Is there currently a way to pass this value or get the remote pipeline to show the prompt to select?

Thanks
Jacques

**Comment by maikvandergaag** [comment]
No this isn't possible at this moment. I will label your question as a feature request
