### ISSUE TITLE
We couldn't able to use PowerBI-Master User autentication from the PowerBI Service connection

### ISSUE THREAD

**Issue by jayendranarumugam** [maikvandergaag/msft-extensions#131]
Hi @maikvandergaag ,

First of all thanks for your latest fix for the SPN Authentication.

I've created two new authentications (one is **demo** which is using the master account and another the **DemoPBI** which is SPN)
![image](https://user-images.githubusercontent.com/25414541/68592156-67315000-04b8-11ea-9ebe-f429e3f531a2.png)

The problem here is the master account is not showing in the drop-down, only the service principal authentication is showing
![image](https://user-images.githubusercontent.com/25414541/68592036-25a0a500-04b8-11ea-901d-705f013907b5.png)

**Comment by maikvandergaag** [comment]
Problem is being deployed at this moment should be available in 15 min.

**Comment by jayendranarumugam** [comment]
@maikvandergaag I'm still experiencing this problem

**Comment by maikvandergaag** [comment]
@jayendranarumugam: thanks for your quick response. For some reason it is possible to create service connections with the same name when it is a private extension for some reason they don't allow it in public extensions. I'm working on a fix now.

**Comment by maikvandergaag** [comment]
@jayendranarumugam: new version has been published
