### ISSUE TITLE
Invoke-API : The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by NimNagpal** [maikvandergaag/msft-extensions#133]
I am trying to Create a release pipeline which will deploy the powerBI report on the powerBi Web services. For this I am using PowerBI Action task and specifying the relevant details like Client ID, Secret, tenant ID and report and group id as well.

I am getting an error while executing the release, The remote server returned an error: (400) Bad Request.
[tasklog_5 (1).log](https://github.com/maikvandergaag/msft-extensions/files/3832260/tasklog_5.1.log)
<img width="1110" alt="Capture" src="https://user-images.githubusercontent.com/31670186/68603665-a784d400-04a0-11ea-8365-155b97cb7adf.PNG">

**Comment by maikvandergaag** [comment]
Could you also supply screenshots

Groetjes,

Maik van der Gaag

________________________________

**Comment by NimNagpal** [comment]
I did found the problem, I was using a dummy files which didn't had any dataset. thus it was failing to publish the report.
