### ISSUE TITLE
Service principal cant update data source as not the owner

### ISSUE THREAD

**Issue by dodgy99** [maikvandergaag/msft-extensions#135]
Hi,

I've been using your great new service principal feature and for deploying reports it works a treat.

However I've found I haven't been able to update a data source because the user does not own the dataset (copy of log below). I have tried but have been unable to find a way to make a service principal the owner of a dataset.

2019-11-12T09:32:45.6264358Z Logging in with a Service Principal
2019-11-12T09:32:45.6264440Z Trying to update the datasource
2019-11-12T09:32:45.6264516Z Getting Power BI Workspace properties; MyWorkspace
2019-11-12T09:32:46.3209790Z **##[error]This operation is only supported for the dataset owner**

Do you know if there is a way around this?

Thanks again for updating this extension.

Thanks

**Comment by maikvandergaag** [comment]
@dodgy99: Is the report also published by the service principal? If yes could you check which user is specified as the dataset owner

**Comment by dodgy99** [comment]
@maikvandergaag 
Hi, the report is originially published as a different user and hence that user owns the dataset. Publishing subsequently using the service principal does not update the dataset ownership.

You can't log in to the service as a service principal so can't take over dataset ownership manually either.

When trying to publish a new report using the service principal it errors complaining about an empty string. Seems the report has to pre-exist

**Comment by maikvandergaag** [comment]
Could you share more information about the last problem you are mentioning?

Screenshots and steps to reproduce

**Comment by dodgy99** [comment]
Ok have tested further and my second issue seems to have been a transient problem. When deploying a new report it is fine.

My only issue is that deploying an existing report doesn't change the dataset owner automatically, so for existing reports I would have to delete and re-deploy to get the service provider to take over ownership.

Do you know how I can change ownership to a service principal when deploying, either with this extension or a powershell script API call?

**Comment by maikvandergaag** [comment]
Yes there is an API Call, and I have it on my list to incorporate it in the extension.

**Comment by dodgy99** [comment]
@maikvandergaag Thanks

I have also written a powershell script to change the owner to a service principal so via the take over API call so will use that in the meantime.

Thanks for the support its much appreciated :)

**Comment by maikvandergaag** [comment]
@dodgy99 if you could share your script I will try to include it in the upcoming weeks
