### ISSUE TITLE
"##[error]The variables can not be found on the definition: , ," when using variable from variable groups

### ISSUE THREAD

**Issue by RobCoPKC** [maikvandergaag/msft-extensions#140]
Hey,

I'm running into issues when using this task to access a variable in a variable group:

![image](https://user-images.githubusercontent.com/56680419/69554416-0e76b280-0fa2-11ea-976a-82d28e4278aa.png)

![image](https://user-images.githubusercontent.com/56680419/69554490-2817fa00-0fa2-11ea-8da7-954aed48bf95.png)

![image](https://user-images.githubusercontent.com/56680419/69554526-36feac80-0fa2-11ea-99c3-c96eeac2a805.png)

![image](https://user-images.githubusercontent.com/56680419/69554570-45e55f00-0fa2-11ea-9f0d-d75fc345bff0.png)

A different task has no problem accessing this variable. And when I defined the variable explicitly in the pipeline it worked flawlessly.

Could you please take a look at this?

Cheers,
Robin

**Comment by maikvandergaag** [comment]
Hi Robin, try defining the variable on the complete release and not the stage. Only setting it on a specific stage isn't supported at this moment

**Comment by RobCoPKC** [comment]
Hey Maik,

I'm afraid I don't fully understand.
The pipeline is just a standard build pipeline which creates an artifact for deployment. There are no "stages".
I just defined the variable in a variable group to later access it in our release pipeline.

Could you please clarify this again?

Cheers,
Robin

**Comment by maikvandergaag** [comment]
Off course, the build it self is also a stage. But I have taken a look further into your screenshots. You are using variables in a variable group. Updating these values isn't supported at this moment. You will have to add them to the build pipeline.

**Comment by RobCoPKC** [comment]
That is unfortunate. But thank you regardless for your quick response!

Cheers,
Robin

**Comment by alexrang83** [comment]
How would this work with a secret variable set in the variables tab of the UI? I get this same error when trying to reference a secret variable in the YAML. 

Here is the set variable:
![image](https://user-images.githubusercontent.com/21359967/154485039-870075e8-386f-4b4f-8086-d7d98450b483.png)

And here is the YAML snippet:
![image](https://user-images.githubusercontent.com/21359967/154485207-5b578050-217b-4aa1-9a05-7b2adb2b658d.png)
