### ISSUE TITLE
Passing Parameters to Pipeline

### ISSUE THREAD

**Issue by Silburfuchs** [maikvandergaag/msft-extensions#141]
Is there a way with this extension to pass variables to the downstream pipeline if the pipeline is in a separate project?

**Comment by khalidibnelbachyr** [comment]
Hi @Silburfuchs, 

Did you find a solution for this use case?

@maikvandergaag

**Comment by maikvandergaag** [comment]
this is not yet supported and needs to be implemented

**Comment by chenghuang-mdsol** [comment]
@Silburfuchs @khalidibnelbachyr This might be late. but did you guys try this api before?

{orgULR}/{pipelineName}/_apis/pipelines/{buildDefinition.ID}/runs


https://gist.github.com/chenghuang-mdsol/c99f5411a7636cc02d7183fe31837217

**Comment by maikvandergaag** [comment]
is in production
