### ISSUE TITLE
PowerBI Pro Account Required?

### ISSUE THREAD

**Issue by c3bars** [maikvandergaag/msft-extensions#142]
I've been trying to get the Publish action setup and working using our on-prem TFS 2018 server.  While trying to publish using a service principal, I am getting "The operation has timed out." as an error message displayed right after "Getting Power BI Workspace properties; {WorkspaceName}".  I pulled in the v4 folder from the agent server and modified your run-local.ps1 file with the same parameters I'm using in TFS.  When run as myself, which has a PowerBI Pro license, I am able to publish without problem.  If I try as the agent service account, I get the error message above.  Does the agent service account require the PowerBI Pro license or am I missing something within my security setup?

**Comment by maikvandergaag** [comment]
You are missing something in your security setup is my guess. Are you using a V2 workspace to publish to when using the service principal.

To be sure could you share your task configuration?

**Comment by c3bars** [comment]
I feel quite silly, but my problem had nothing to do with this and was actually a block on our firewall preventing our service user from reaching out to the internet.
