### ISSUE TITLE
Cannot update version number using extension

### ISSUE THREAD

**Issue by jlundstocholm** [maikvandergaag/msft-extensions#144]
I have added your extension to our build pipeline, but an exception is thrown when the step is executed.

The logs below indicate an error when accessing the repo of my pipeline. But the user account owning the PAT I have supplied has "Contribute" permissions on the repo ... and I really do not understand, why the extension tries to access the repo at this point. I would expect it to only update the version number variable.

Anyway ... :-)

The debug log is this:

```
##[debug]Evaluating condition for step: 'Version number counter'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Version number counter
==============================================================================
Task         : Version number counter
Description  : Build and release task for a version number counter
Version      : 1.1.4
Author       : Maik van der Gaag
Help         : 
==============================================================================
##[debug]VstsTaskSdk 0.1 commit _COMMIT_HASH_
##[debug]Entering D:\a\_tasks\versioncounter_84f23c57-8c65-4709-bc94-5cbd44e96a99\1.1.4\run-task.ps1.
##[debug]INPUT_VERSIONVARIABLE: 'VersionNumber'
##[debug]INPUT_UPDATEMINORVERSION: 'false'
##[debug]INPUT_MAXVALUEPATCHVERSION: '0'
##[debug]INPUT_MAXVALUEMINORVERSION: '0'
##[debug]INPUT_UPDATEMAJORVERSION: 'false'
##[debug]INPUT_DEVOPSPAT: 'iv6sxtouauf4n66otm7ea6a3m5bly5jkairhco5bgyqvuyjxr3ja'
VersionVariable      : VersionNumber
UpdateMinorVersion   : false
MaxValuePatchVersion : 0
UpdateMajorVersion   : false
MaxValueMinorVersion : 0
DevOpsPAT            : ***
DevOps Uri           : https://dev.azure.com/<removed>/
Project Name         : <removed>
Project Id           : <removed>
BuildId              : 42
Invoking rest method 'Get' for the url: https://dev.azure.com/<removed>/<removed>/_apis/build/builds/42?api-version=4.1.
##[debug]GET https://dev.azure.com/<removed>/<removed>/_apis/build/builds/42?api-version=4.1 with 0-byte payload
##[debug]received 4795-byte response of content type application/json; charset=utf-8; api-version=4.1
Trying to retrieve the build definition with the url: https://dev.azure.com/<removed>/<removed>/_apis/build/definitions/1?api-version=4.1.
##[debug]GET https://dev.azure.com/<removed>/<removed>/_apis/build/definitions/1?api-version=4.1 with 0-byte payload
##[debug]received 8111-byte response of content type application/json; charset=utf-8; api-version=4.1
Value of the Major Version Variable: 1.1.0
Current version Major: 1, Minor 1, Patch 0
Updating patch version number from: 0 to 1.
Updating minor version number from: 1 to 1.
Updating major version number from: 1 to 1.
##[debug]Updating Project Build number with URL: https://dev.azure.com/<removed>/<removed>/_apis/build/definitions/1?api-version=4.1
##[debug]PUT https://dev.azure.com/<removed><removed>/_apis/build/definitions/1?api-version=4.1 with -1-byte payload
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"TF401019: The Git repository with name or identifier <my repo name> does not exist or you do not have permissions for the operation you are attempting.","typeName":"Microsoft.TeamFoundation.Git.Server.GitRepositoryNotFoundException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitRepositoryNotFoundException","errorCode":0,"eventId":3000}
##[debug]At D:\a\_tasks\versioncounter_84f23c57-8c65-4709-bc94-5cbd44e96a99\1.1.4\run-task.ps1:95 char:13
##[debug]+             Invoke-RestMethod -Method Put -Uri $defUri -Headers $devO ...
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, D:\a\_tasks\versioncounter_84f23c57-8c65-4709-bc94-5cbd44e96a99\1.1.4\run-task.ps1: line 95
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Net.WebException: The remote server returned an error: (404) Not Found.
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[error]The remote server returned an error: (404) Not Found.
##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (404) Not Found.
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: Version number counter
```

Any idea why this error happens?

**Comment by maikvandergaag** [comment]
what are the exact permissions that you gave to the DevOps pAty?

**Comment by jlundstocholm** [comment]
> what are the exact permissions that you gave to the DevOps pAty?

Hi,

Thanks for your guick response :-) 

I had just given it access to execute the build pipelines, but I have now added "read/write" on repos as well. However, it gives me the same error.

**Comment by jlundstocholm** [comment]
Permissions for PAT

![image](https://user-images.githubusercontent.com/683942/70417719-22221e80-1a62-11ea-899d-3076833ab26c.png)

**Comment by maikvandergaag** [comment]
could you also share some screenshots of your task configuration and we're you have specified the variable?

**Comment by jlundstocholm** [comment]
> could you also share some screenshots of your task configuration and we're you have specified the variable?

Sure :-)

Task configuration:

![image](https://user-images.githubusercontent.com/683942/70419610-10427a80-1a66-11ea-8e35-e20fe9ac8364.png)

Environment variable configuration:

![image](https://user-images.githubusercontent.com/683942/70419727-57307000-1a66-11ea-9dd5-341bb000b4e1.png)

**Comment by maikvandergaag** [comment]
> > could you also share some screenshots of your task configuration and we're you have specified the variable?
> 
> Sure :-)
> 
> Task configuration:
> 
> ![image](https://user-images.githubusercontent.com/683942/70419610-10427a80-1a66-11ea-8e35-e20fe9ac8364.png)
> 
> Environment variable configuration:
> 
> ![image](https://user-images.githubusercontent.com/683942/70419727-57307000-1a66-11ea-9dd5-341bb000b4e1.png)

HI,

You should the following version format [major].[minor].[patch]. I haven't tested it yet with a four digit version number. could you check if that helps?

**Comment by jlundstocholm** [comment]
> > > could you also share some screenshots of your task configuration and we're you have specified the variable?
> > 
> > 
> > Sure :-)
> > Task configuration:
> > ![image](https://user-images.githubusercontent.com/683942/70419610-10427a80-1a66-11ea-8e35-e20fe9ac8364.png)
> > Environment variable configuration:
> > ![image](https://user-images.githubusercontent.com/683942/70419727-57307000-1a66-11ea-9dd5-341bb000b4e1.png)
> 
> HI,
> 
> You should the following version format [major].[minor].[patch]. I haven't tested it yet with a four digit version number. could you check if that helps?

Oh sorry ... that is my bad. I had to disable the extension/action step and revert to the 1.1.0.7 version number to get the pipeline to work.

If I use the format 1.1.0.7, the extension tells me that the format is wrong. If I use e.g. 1.1.0, the exception above happens.

Below is a current screenshot when using the correct format.

![image](https://user-images.githubusercontent.com/683942/70420253-9f9c5d80-1a67-11ea-9e2c-5b362ac8b808.png)


I apologize for the confusion.

**Comment by maikvandergaag** [comment]
@jlundstocholm: To eliminate the issues could you give the PAT full control temporally and try again?

I think I left something out of the documentation.

**Comment by jlundstocholm** [comment]
> @jlundstocholm: To eliminate the issues could you give the PAT full control temporally and try again?
> 
> I think I left something out of the documentation.

It has now full access. The result is the same.  :-(

Do I need to do something with the account I created the PAT with - permission-wise?

**Comment by maikvandergaag** [comment]
No that is not nessary what kind of agents are you using?

**Comment by jlundstocholm** [comment]
> No that is not nessary what kind of agents are you using?

![image](https://user-images.githubusercontent.com/683942/70424162-315b9900-1a6f-11ea-85aa-f1bf327d5383.png)

**Comment by maikvandergaag** [comment]
You removed the organization name and project from this line:

##[debug]PUT https://dev.azure.com/<removed><removed>/_apis/build/definitions/1?api-version=4.1 with -1-byte payload

Did you exedantly remove the / or wasn't it there

**Comment by jlundstocholm** [comment]
> You removed the organization name and project from this line:
> 
> ##[debug]PUT https://dev.azure.com//_apis/build/definitions/1?api-version=4.1 with -1-byte payload
> 
> Did you exedantly remove the / or wasn't it there

I removed it ...

**Comment by maikvandergaag** [comment]
Thank you for the raw input.

The strange thing is that the Get is working and the PUT is failing. I will have to investigate further what is going wrong there.

**Comment by jlundstocholm** [comment]
> Thank you for the raw input. The strange thing is that the Get is working and the PUT is failing. I will have to investigate further what is going wrong there. 

Thank you :-) . Let me know if there is anything I can do to help. I really appreciate your help!

Also - why does it try to access the repo? I would expect it to only access the variables?

**Comment by maikvandergaag** [comment]
Yes that is strange as well, but I think that is related to the error message. As you can see in the powershell scripts within the repository there is no connection with the repository the only things we use are the buildin API.

Could you maybe try one thing for me. Do not think this will change anything, but in the variables configuration you have set the checkbox: that you can change the value when queued.

**Comment by jlundstocholm** [comment]
> No that is not nessary what kind of agents are you using?

Hi,

I am absolutely positive that is is a permission issue on the PAT. I could not leave the thought alone yesterday as it occurred to me that a user should not be able to create a PAT and elevate the permissions on it higher than the permissions on the user itself.

So I created a new PAT using my own account instead of the service account we would like to use. I am org admin on the Azure DevOps organization.

Now everything works :-)

I will try to figure out the required permissions on the PAT and if I find an answer, I will update this issue. If you find the answer - please share as well ;-)

/Jesper

**Comment by camilopedroso** [comment]
Hi all!

In my case, I'm able o see that the variable it's been updated accordingly, but, I thought it would change the DLL version and it isn't the case, because I'm trying to get the version using 
GetType().Assembly.GetName().Version.ToString(); and the version is always 1.0.0.0.
What I'm doing wrong?

Cheers!
