### ISSUE TITLE
Update-PowerBIDatasetDatasource with UpdateAll = false fails for PowerBI Reports with DirectConnect to SSAS

### ISSUE THREAD

**Issue by GullbrandGillund** [maikvandergaag/msft-extensions#150]
We are using Power BI Reports with DirectConnect to SSAS OnPrem.

The component is failing for single dataset update because the $GroupPath is part of the URL.

I have tested the URL in this link:
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasources#code-try-0

I am not sure if $GroupPath is needed for DataSets of type Import.

**Comment by maikvandergaag** [comment]
@GullbrandGillund:

Could you give me some more information? Like screenshots and steps to reproduce?

**Comment by GullbrandGillund** [comment]
![DevOps_StepsInTaskGroup_UpdateDataSource](https://user-images.githubusercontent.com/59838055/72328821-f115b900-36b3-11ea-96dd-85211510b619.jpg)
![DevOps_UpdateDataSource](https://user-images.githubusercontent.com/59838055/72328823-f115b900-36b3-11ea-9be7-d0c64bce7762.jpg)
![Dataset_UpdateDatasources](https://user-images.githubusercontent.com/59838055/72329038-536eb980-36b4-11ea-9319-e992d0bc9de5.jpg)

Hi, see attached pictures. The Dataset_UpdateDatasources is using the API in this link: https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasources#code-try-0

Regards Gullbrand

**Comment by maikvandergaag** [comment]
@GullbrandGillund : Why did you close the issue?

In my module it uses this api:
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasourcesingroup

It uses the datasets groups. Could you share a screenshot of the powerbi side

**Comment by GullbrandGillund** [comment]
@maikvandergaag 
Hi, sorry clicked on wrong button.

Update data sources in group does not work for SSAS DirectConnect. Datasets - Update Datasources In Group

But Datasets - Update Datasources is working for one dataset update with SSAS Direct Connect: https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasources#code-try-0

Could you use Datasets - Update Datasources when UpdateAll is false?

Regards Gullbrand

**Comment by maikvandergaag** [comment]
I will need to check that but I think that will break the functionality for other datasets. Do you maybe have a dummy report with a dataset you are mentioning for me to test

**Comment by GullbrandGillund** [comment]
Hi

Attached is Power BI using SSAS cube BISM Jira with Direct Connect.
The report is not displaying data because of filter on Project = Dummy.

Was not able to upload Power BI file to Github.

Regards
Gullbrand

**Comment by GullbrandGillund** [comment]
Hi, here is the Power BI file zipped.
Regards Gullbrand
[JI01_001 DWH Main Project Plan.zip](https://github.com/maikvandergaag/msft-extensions/files/4058956/JI01_001.DWH.Main.Project.Plan.zip)

**Comment by GullbrandGillund** [comment]
Hi

It is working fine.
The problem was missing \ between server and instance. (Escaping \)
Example servername\\instansename

Regards Gullbrand
