### ISSUE TITLE
Azure Key Vault actions - ##[error]Cannot bind argument to parameter 'VariableValue' because it is null.

### ISSUE THREAD

**Issue by rsch006** [maikvandergaag/msft-extensions#151]
I'm trying to use "Get Certificate Uri" and seeing below error. The certificate is valid and present in the KV. Is there something which i'm doing it wrong?

 ##[error]Cannot bind argument to parameter 'VariableValue' because it is null.

**Comment by maikvandergaag** [comment]
could you share your configuration and maybe some screenshots

**Comment by rsch006** [comment]
![Capture1](https://user-images.githubusercontent.com/18110938/72467809-5b585780-37a1-11ea-8af3-88b2d295b38f.JPG)
![Capture](https://user-images.githubusercontent.com/18110938/72467810-5b585780-37a1-11ea-96e9-30ae933605ea.JPG)

The taks works if the Variable Name is like $(output1). But the results are not saved in it.

**Comment by maikvandergaag** [comment]
@rsch006 : Did you have any progress regarding this issue?

**Comment by maikvandergaag** [comment]
No more comments so closing this issue
