### ISSUE TITLE
Power BI Actions: update Datasource credentials

### ISSUE THREAD

**Issue by garimpeirodouniverso** [maikvandergaag/msft-extensions#152]
Hello @maikvandergaag ,

I could not find in Power BI Actions something related to updating Datasource credentials. I see we are able to update the Datasource to target another Database and Server, but without changing the credentials we are not able to proceed to refresh the datasets (we are using Import method with an Azure SQL database).

There is an API to do so, called "Gateways - Update Datasource" (https://docs.microsoft.com/pt-br/rest/api/power-bi/gateways/updatedatasource).

Am I missing something and this feature is already implemented?

Thanks, and great project, very helpful!

**Comment by maikvandergaag** [comment]
@garimpeirodouniverso that is correct I have that feature under development. The feature will support directqueries.

if you want I can give you access to the beta by providing me your organization name.

**Comment by garimpeirodouniverso** [comment]
@maikvandergaag thanks for the prompt response!!

As a matter of fact, we do not intend to use Direct Queries in our reports, we must still use the Import method. The thing is, even with the Import method we still need to update the Datasource credentials, otherwise we are not able to perform dataset refreshes.

So, for clarification sake, is this feature of updating credentials aimed only to Direct Queries or is it going to also affect Import datasets?

Thank you again!

**Comment by loopfish** [comment]
@maikvandergaag hi Maik, thank you for publishing these tasks. I too am in the process of setting up a pipeline in DevOps to completely provision a Power BI workspace, with reports and datasets, but need to parameterize the dataset connection using pipeline variables, and I am stuck at this stage: 
![image](https://user-images.githubusercontent.com/39245344/75042589-8c216000-54b6-11ea-82bb-b2f3d9af5087.png)
I need to define the credentials for the updated connection. You mention you have a beta for a solution? What would that involve?
Thanks, Sam
