### ISSUE TITLE
Power BI Actions: allow Datasource update without OldServer and OldDatabase

### ISSUE THREAD

**Issue by garimpeirodouniverso** [maikvandergaag/msft-extensions#154]
Hello @maikvandergaag ,

Another feature that would be interesting would be to allow the update of Datasources without preemptively knowing the OldServer and OldDatabase. The scenario is as follows:

- the reports developer downloaded the .pbix files from the repository
- they will connect to some database to perform the changes to the reports (it could be any development database, we don't know which one, it's up to the developer)
- after changes made to the .pbix files, they commit and push the changes to the master branch
- CI/CD should run and deploy the .pbix files to the Production Workspace (with datasources updated to target Production database, of course)

In this scenario, CI/CD script does not know the original server + database for the .pbix, it just knows the "NewServer" and "NewDatabase" (i.e., Production database).

So maybe we could have a flag in "UpdateDatasource" action to update all the datasources of the target Dataset (given that OldServer and OldDatabase will not be provided). The script is able to loop through all Datasources within the Dataset and update the connection details then.

Thanks!

**Comment by loopfish** [comment]
I totally agree with this. I don't know what the old server/database will be.

**Comment by maikvandergaag** [comment]
@garimpeirodouniverso: that would be an option I will need to investigate this. The API works in a way that you will have to use selectors to get the correct Datasource. This scenarion would not work for a dataset with multiple datasources for example.

In a few weeks I will have more time as I have some personal stuff I need to figure out at this moment will keep you posted

**Comment by garimpeirodouniverso** [comment]
@maikvandergaag you are correct about the scenario with multiple datasources per dataset.

In my case I am looping through all datasources for the given dataset and changing all of them to the desired datasource.

Maybe we could warn the developer that this is the behavior when they don't provide the OldServer and OldDatabase, i.e., all datasources within that dataset will be updated to the NewServer and NewDatabase (which I think will cover the majority of use cases) . In the other hand, if the developer indeed has different datasources from different databases within the same dataset, then there is no magic: they will have to provide OldDatabase and OldServer.

**Comment by zbroinx** [comment]
> @maikvandergaag you are correct about the scenario with multiple datasources per dataset.
> 
> In my case I am looping through all datasources for the given dataset and changing all of them to the desired datasource.
> 
> Maybe we could warn the developer that this is the behavior when they don't provide the OldServer and OldDatabase, i.e., all datasources within that dataset will be updated to the NewServer and NewDatabase (which I think will cover the majority of use cases) . In the other hand, if the developer indeed has different datasources from different databases within the same dataset, then there is no magic: they will have to provide OldDatabase and OldServer.

@garimpeirodouniverso 
Did you managed to update the datasource and bind to the correct gateway? If yes, how?
I'm having this problem: https://github.com/maikvandergaag/msft-extensions/issues/262

**Comment by maikvandergaag** [comment]
Added a new task that could help with this. Is publihed as beta if you like the beta plese let me know
