### ISSUE TITLE
PowerBI Actions: Update all datasources fails if you have used Usage Metrics Reports

### ISSUE THREAD

**Issue by leinoaa** [maikvandergaag/msft-extensions#155]
Howdy @maikvandergaag !

We were moving towards changing report data sources on workspace basis and noticed that the "Update all datasources in workspace the datasource name will be ignored" -selection will always fail at some point if you have ever used or opened a Usage Metrics Report. We were using a service principal for the task. Error message received: "This operation is only supported for the dataset owner".

Since it doesn't make any sense to change the data source (and you can't while using a service principal at least) for UMR-reports they should be ignored when changing all datasources for a particular workspace. There are two types of UMR-reports, at least based on the data sets. Also these data sets can be invisible on the Power Bi Service -site, so you can't trust that list so you must use the API to verify each workspace's data sets. 

These data set's name for UMR-reports seem to have to two name types "Report Usage Metrics Model" and "Usage Metrics Report", regardless of the name you provide for your UMR-report. So if you could automatically ignore these when running through the data sets and updating them it would be perfect. Or at least have an option to ignore those names / UMR data sets in general :)

Thanks!

**Comment by maikvandergaag** [comment]
I will try to check this functionality. Could you maybe help / point out to me how to create a dataset like that?

**Comment by leinoaa** [comment]
Gladly! And now what you mentioned, I found a third data set, which is a UMR-report for dashboards with a name "Dashboard Usage Metrics Model". 

So in your workspace, go to Dashboards or Reports -page. On those pages under Actions the first selection provides you with "View usage metrics report". This will create a UMR for you which you can save a copy of to that particular workspace and modify it also.

Power BI Service:
![image](https://user-images.githubusercontent.com/60613509/73663629-9ebe2b80-46a6-11ea-9341-540d289cec3f.png)

API and names of data sets:
![image](https://user-images.githubusercontent.com/60613509/73663762-dcbb4f80-46a6-11ea-80d6-f5ee8a379149.png)

**Comment by maikvandergaag** [comment]
Great, will look at it when I have the time. There are some personal related stuff at this moment. I will do my best

**Comment by maikvandergaag** [comment]
Issue seems to be resolved if you have any updates please let me know
