### ISSUE TITLE
Passing Build number to triggered pipeline

### ISSUE THREAD

**Issue by chakaSA** [maikvandergaag/msft-extensions#156]
Hi There

Currently I leave the Build Number field empty and works great to use the latest build version.
However, the parent pipeline might not use the latest build and would like to pass this build number to the child pipeline being triggered.

The tip that pops up does not give and example and its not clear to me how to use this field.
Can I use a variable eg $(Build.BuildNumber), to get the build number used in this pipeline and this will be passed on to the triggered pipeline to use?

Thanks
Jacques

**Comment by chakaSA** [comment]
Seems I had a rogue character, re-entering the variable it seems to work so question answered I think

**Comment by maikvandergaag** [comment]
Great!
