### ISSUE TITLE
Service principle authentication: The remote server returned an error: 401

### ISSUE THREAD

**Issue by hoang08** [maikvandergaag/msft-extensions#157]
Thank you for this useful extension.  Unfortunately my org uses 2 factors authentication so I am unable to use User authentication.  These are the steps I did to enabled principle authentication:

1. Create an app in AAD
2. Add the app to the workspace as an admin in PowerBi.com
3. Create a service connection in DevOps with option Service Principle
4. Create a task to add a user to the workspace

I test run this and I get the error: The remote server returned an error: (401) Unauthorized.

Any idea how I can debug this or any step I might be missing?

**Comment by maikvandergaag** [comment]
@hoang08: Are you using tthe correct group types? And did you do a test yourself with using the API

**Comment by hoang08** [comment]
For group type, do you mean between user and service principle option?  Yes, i chose service principle.  Can you give me some ideahow to test the api with the key?

**Comment by maikvandergaag** [comment]
I meant the workspace type within PowerBI you have version 1 and 2. the groups should be of version 2. Do you get a 401 on every action?

API can be tested with powershell

**Comment by hoang08** [comment]
I am not sure what version I have, how do I check that?  Its 401 on all actikns. I will give powershell a try to test it out.

**Comment by rstones450** [comment]
@hoang08 - Hello, It appears I am facing a similar issue as you are. Just wondering if you were able to resolve yours? If so appreciate any pointers.

<I have an open issue on (189)>

Thank You.

**Comment by maikvandergaag** [comment]
Duplicated with issue #189 will close this one. It is something in the configuration of the service principal.
