### ISSUE TITLE
Scheduling Dataset refresh/taking over DatSets w SPN

### ISSUE THREAD

**Issue by Sam010203** [maikvandergaag/msft-extensions#160]
This extension has been great so for  for me. But when power BI is uploaded using Service principle, and other user takes over data set to schedule refresh, the redeployment would fail saying SPN is not data owner. Is there a way to schedule the refresh after deployment? or Can SPN takes over data set before deploying ?  I guess I am asking for new feature 
1.) Action to take over data set
 2.) Action to Add Scheduled Refreshes

**Comment by BobJMW** [comment]
The option to take over a data set with SPN would be a welcome addition to this already great extension!

**Comment by nitmatgeo** [comment]
@maikvandergaag  Coming soon! By this weekend will share the code. Tested locally it's working.

**Comment by BobJMW** [comment]
Awesome! I will block my agenda for monday morning to check it out. :)

**Comment by maikvandergaag** [comment]
Take over dataset is released in the beta version.

**Comment by nitmatgeo** [comment]
@Sam010203 Cheers... Enjoy the new version ☺️
Isn't it @maikvandergaag ? This part of issue can be closed right? Maybe scheduled refresh isn't..

**Comment by maikvandergaag** [comment]
Scheduled refresh isn't added but the rest is.

**Comment by BobJMW** [comment]
Maybe I got off by the 'take over dataset', but _where_ could I take over the dataset with a SPN?

**Comment by maikvandergaag** [comment]
The SPN depends on the service connection you use. The action "Take dataset ownership" will take the ownership

**Comment by BobJMW** [comment]
Thanks! I am happy to confirm that a successful dataset take over has been executed.
