### ISSUE TITLE
[error]Dataset doesn't contain a datasource that matches selector #1

### ISSUE THREAD

**Issue by jahirb4u** [maikvandergaag/msft-extensions#161]
Hi,

What are the possibilities for below issue 

[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups
[debug]GET https://api.powerbi.com/v1.0/myorg/groups with 0-byte payload
[debug]received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true
[debug]Trying to find workspace: WF_STAGING
[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups/ce8b8838-4173-4f9e-a92d-5bcdfaa33e79/datasets
[debug]GET https://api.powerbi.com/v1.0/myorg/groups/ce8b8838-4173-4f9e-a92d-5bcdfaa33e79/datasets with 0-byte payload
[debug]received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true
[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups/ce8b8838-4173-4f9e-a92d-5bcdfaa33e79/datasets/132743ea-dc89-4517-aae5-39f74490e87c/Default.UpdateDatasources
[debug]POST https://api.powerbi.com/v1.0/myorg/groups/ce8b8838-4173-4f9e-a92d-5bcdfaa33e79/datasets/132743ea-dc89-4517-aae5-39f74490e87c/Default.UpdateDatasources with -1-byte payload
[debug]Leaving C:\Agent\DockerPool\Agent_1\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.0.9\run.ps1.
[debug]Caught exception from task script.
[debug]Error record:
[debug]Invoke-API : Dataset doesn't contain a datasource that matches selector #1
[debug]At C:\Agent\DockerPool\Agent_1\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\4.0.9\ps_modules\PowerBi\PowerBi.psm1:298 char:9
[debug]+         Invoke-API -Url $url -Method "Post" -AccessToken $AccessToken ...
[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-API

Thanks,
Jahir

**Comment by maikvandergaag** [comment]
If you would like any further assistant please reopen the issue
