### ISSUE TITLE
Service connection (with service principle)

### ISSUE THREAD

**Issue by Styxxy** [maikvandergaag/msft-extensions#162]
It would be nice if a "verify" button is available on the service connection creation pane, like with the Azure Resource Manager service connection to verify the configured service principle.

Screenshot from Azure Resource Manager service connection creation pane:
![screenshot azure resource manager serviceconnection](https://user-images.githubusercontent.com/1635825/77519406-b6808780-6e7f-11ea-807c-21d21a84d4d6.png)

**Comment by maikvandergaag** [comment]
I do not see any options at this moment to add this functionality. When it is possible in the feature I will try to add it
