### ISSUE TITLE
Power BI Actions Steps Fails in Azure DevOps

### ISSUE THREAD

**Issue by satishjb** [maikvandergaag/msft-extensions#163]
I keep getting this error I have made necessary changes to permissions and grants yet it failed. Infact I have created new account in Azure just to validate the same still fails. Kindly let me know what I could be missing.

User Principal Error

##[error]Exception calling "GetResult" with "0" argument(s): "AADSTS700016: Application with identifier '***' was not found in the directory 'something.onmicrosoft.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

Service Prinical

**Comment by aleex-bro** [comment]
Are you using the applicationid or the objectid for the SPN in DevOps ? I got exactly the same error message while using objectid.

**Comment by hnjames9** [comment]
I get this same error.  Is it because my userprincipla has MFA enabled?

**Comment by maikvandergaag** [comment]
@hnjames9  yes it is. Your user principal can not use MFA it is mentioned in the docs
