### ISSUE TITLE
PowerBI - Upload dataset works, Upload Report does not work

### ISSUE THREAD

**Issue by aleex-bro** [maikvandergaag/msft-extensions#165]
Hello,

previously I used version 2.x and was successfully able to upload datasets and reports using credentials. Now we switched to SPNs. We upgraded to 4.x. I am still using the same task (Upload PowerBI Report) but unfortunately I am not able to upload reports although datasets can be successfully uploaded to the PowerBI Workspace.

Getting Error 404 - Bad request.

Any advice ?:)

**Comment by aleex-bro** [comment]
@maikvandergaag : Hi Maik, could you please take a look on that or do you need any further information ?

**Comment by maikvandergaag** [comment]
What kind of group are you using to publish your reports, you need to use version 2 when using a SPN

**Comment by aleex-bro** [comment]
@maikvandergaag : Hi Maik, first of all thank you a lot for your reply. Unfortunately, I don't see any options to use version 2 ? We had to install the extension on a new DevOps and there we just have version 4 available and SPNs are just available in version 4.x ?

**Comment by maikvandergaag** [comment]
It’s about the group type within PowerBI, at some point they created new PowerBI group types SPNs only support the new group types within PowerBI

Groetjes,

Maik van der Gaag
________________________________
Van: aleex-bro <notifications@github.com>
Verzonden: Tuesday, April 7, 2020 11:14:08 AM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] PowerBI - Upload dataset works, Upload Report does not work (#165)


@maikvandergaag<https://github.com/maikvandergaag> : Hi Maik, first of all thank you a lot for your reply. Unfortunately, I don't see any options to use version 2 ? We had to install the extension on a new DevOps and there we just have version 4 available and SPNs are just available in version 4.x ?

**Comment by aleex-bro** [comment]
@maikvandergaag : Could you provide me any kind of document references or could you explain it further ?

I really appreciate your help.

**Comment by maikvandergaag** [comment]
https://docs.microsoft.com/en-us/power-bi/service-new-workspaces

Met vriendelijke groet,

Maik van der Gaag

**Comment by aleex-bro** [comment]
Hi Maik,

Thanks for your reply. Basically we are using the new workspace but it still doesn't work. It works perfectly fine for datasets but not for reports. 

Maybe we could have a quick Teams call ?

**Comment by maikvandergaag** [comment]
Hi Alex,

That can be arranged.

Met vriendelijke groet,

Maik van der Gaag

**Comment by aleex-bro** [comment]
Hi Maik,

Thanks a lot I wrote you a message on Microsoft Teams. I highly appreciate your help.

**Comment by aleex-bro** [comment]
Hi Maik,

have you been able to see my message on Teams ? I don't whether I picked the right e-mail address. It would be awesome if you could text me back. Thanks a lot in advance.

**Comment by maikvandergaag** [comment]
Hi alexx haven't received your message
