### ISSUE TITLE
Power BI Actions - Update parameters

### ISSUE THREAD

**Issue by vdbosschekoen** [maikvandergaag/msft-extensions#172]
Hi,
Is there a feature on your list to have the option to change parameters after deployment of a dataset?
We have a few datasets that are using reports and it should be nice to have an option to change them.

Thanks in advance.

**Comment by maikvandergaag** [comment]
Do not think I have that on my list already could you maybe share more information?

**Comment by vdbosschekoen** [comment]
Oke will do, give me a few days to make an example

**Comment by vdbosschekoen** [comment]
I have sent you an email with more details and example. 
Hope this will help you

**Comment by rajrao** [comment]
Is this something I could **try** and implement and submit a PR for?

**Comment by vdbosschekoen** [comment]
I have created a version that is allowed to update parameters. But the setup is more generic, which allows us to do upload and change stuff like parameters, datasources,... based on a config file
Will try to make a version that can be implemented in the power bi action

**Comment by maikvandergaag** [comment]
@rajrao : yes off course this is why it is a opensource extension. Please do, as I do not have the time soon to do the adjustments.

If you have questions do not hesitate to ask

**Comment by maikvandergaag** [comment]
> I have created a version that is allowed to update parameters. But the setup is more generic, which allows us to do upload and change stuff like parameters, datasources,... based on a config file
> Will try to make a version that can be implemented in the power bi action

That would be great!

**Comment by rajrao** [comment]
@vdbosschekoen Can I help in any way? I don't want to duplicate effort if you already have something ready to go (or even if its the start, maybe I can help complete it)

**Comment by vdbosschekoen** [comment]
@rajrao i will try to create a version that will fit in the power bi actions. My version is different because it is using a config file to control everything.
I will try to do this as soon as possible
