### ISSUE TITLE
UpdateDatasource ends in error Multiple datasources not supported in V3 models

### ISSUE THREAD

**Issue by jos1977** [maikvandergaag/msft-extensions#173]
Hi,

When we try update a sql datasource in powerbi with the 'UpdateDatasource'  we end up with an error 'Multiple datasources not supported in V3 models' . This powerbi report contains 2 datasources, sharepoint and sql. We did manage to get another report working which only contained the sql datasource.

I cant find anything on the internet about this error, do you have any clue what this means?

Regards,

Jos Eilers

**Comment by maikvandergaag** [comment]
If you need any further assistance regarding this issue please let me know and open the issue again
