### ISSUE TITLE
Unable to update the Databricks connection of a Power BI report.

### ISSUE THREAD

**Issue by ambinotty** [maikvandergaag/msft-extensions#174]
We wanted to update the databricks cluster URL which we have environment specific. we tried with existing connect types and no luck. please share if we have option to replace the same on a specific report.

**Comment by maikvandergaag** [comment]
Do you have any information regarding this?

**Comment by ambinotty** [comment]
Sure maikvandergaag!

We are using parameter to control databricks URL in the PBI file. So, having option to update the dataset parameter can achieve our requirement. appreciate your help!

**Comment by maikvandergaag** [comment]
Will not be incorporated within the extension at this moment. Will be happy to support a pull request for this addition
