### ISSUE TITLE
How can I retrieve Group ID and Report IDs for the actions like Publish report or Creation of Group.

### ISSUE THREAD

**Issue by NimNagpal** [maikvandergaag/msft-extensions#179]
Hello Maik,

I have used the PowerBI actions task where Power Bi workspace is created and a report is published. Post this action I want to pass the GroupID (WorkspaceID) and the Report ID to store in a file. 

Is there are way to get these IDs as return variables?  (So I can further utilize them)

Thank you for your work.

**Comment by maikvandergaag** [comment]
Nice suggestion will mark it as a feature request!

**Comment by maikvandergaag** [comment]
The following values will be returned as variables in the next release which I will be publishing this week:

* PowerBIActions.ReportId
*PowerBIActions.WorkspaceId
