### ISSUE TITLE
Invalid api version string

### ISSUE THREAD

**Issue by ScottColson** [maikvandergaag/msft-extensions#181]
I started using this component a few weeks ago and it was working perfectly. Now my jobs are failing with a 401 error and message "Invalid api version string: \"4.1.\". Api version string must be in the format: {Major}.{Minor}[-preview[.{ResourceVersion}]]."

I checked the logs and the component seems to be including a trailing period after 4.1. When I use the URL directly with out the trailing period I get back what looks like expected json data.

**Comment by ScottColson** [comment]
![image](https://user-images.githubusercontent.com/4977127/83769834-302db200-a635-11ea-9700-c125c1dbc812.png)

**Comment by maikvandergaag** [comment]
Hi scot,

The dot is included in the error message. The 401 means that the call is unauthorized. Please check the PAT you are using.

Groetjes,

Maik van der Gaag
________________________________
Van: Scott Colson <notifications@github.com>
Verzonden: Thursday, June 4, 2020 4:30:39 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Invalid api version string (#181)


[image]<https://user-images.githubusercontent.com/4977127/83769834-302db200-a635-11ea-9700-c125c1dbc812.png>

**Comment by ScottColson** [comment]
I've previously recreated the PAT and even extended its security to full control but will try again. Thanks.

**Comment by ScottColson** [comment]
Got it working. This time I recreated the link to my azure key vault. Really appreciate the tool you've made. Thank you!
