### ISSUE TITLE
PowerBI Action not updating the PBIX.

### ISSUE THREAD

**Issue by NimNagpal** [maikvandergaag/msft-extensions#182]
Hello Maik,

To my surprise, the task completes the action of Upload/Publish the PBIX report BUT when I check it in actual Report is not uploaded in the powerBI Portal. 

![image](https://user-images.githubusercontent.com/31670186/84655638-36f7d700-af09-11ea-9fec-969cd7694df4.png)
Missing in the portal.
![image](https://user-images.githubusercontent.com/31670186/84655724-5db60d80-af09-11ea-828e-90b94381bccb.png)

**Comment by maikvandergaag** [comment]
@NimNagpal: Could you share some more information about your configuration and security setup?
