### ISSUE TITLE
Powerbi action for .gov

### ISSUE THREAD

**Issue by bmnyc0923** [maikvandergaag/msft-extensions#183]
Hi 
i think your extension points towards app.powerbi.com . Can you please suggest how can we make this work for https://app.powerbigov.us/ . when we try your extension it always fails with authentication errors

**Comment by maikvandergaag** [comment]
I would be happy to test, but I do not have an environment for governance. Do you know the api endpoint for goverannce, I could create a Beta version for you to test.

**Comment by maikvandergaag** [comment]
Will continue this on issue #189 - as this is related.

**Comment by maikvandergaag** [comment]
Government support is added in V5 of the extension
