### ISSUE TITLE
[error]Unable to find type [VstsTaskSdk.TerminationException]

### ISSUE THREAD

**Issue by abdulkareem-incresol** [maikvandergaag/msft-extensions#185]
Hi,

I am getting the below technical error while running the pipeline with this 'Power BI Utility' extension. Could you please help me on this. Below is the complete log trace captured with System Diagnostics enabled. 

##[debug]Evaluating condition for step: 'PowerBI Utility'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
Starting: PowerBI Utility
==============================================================================
Task         : PowerBI Utility
Description  : Release Task of PowerBI Utility
Version      : 1.0.24
Author       : SDC BI bd
Help         : 
==============================================================================
Add-Type : Could not find file 
'D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\ps_modules\VstsTaskSdk\VstsTaskSdk.dll'.
At D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\ps_modules\VstsTaskSdk\VstsTaskSdk.psm
1:20 char:1
+ Add-Type -LiteralPath $PSScriptRoot\VstsTaskSdk.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand
 
##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
##[debug]Entering D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\run-task.ps1.
##[debug]Loading module from path 'D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\ps_modules\PowerBi\PowerBi.psm1'.
##[debug]Exporting function 'Invoke-API'.
##[debug]Exporting function 'Get-AADToken'.
##[debug]Exporting function 'Get-PowerBiGroup'.
##[debug]Exporting function 'Get-PowerBiReport'.

##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Unable to find type [VstsTaskSdk.TerminationException].
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
##[error]Unable to find type [VstsTaskSdk.TerminationException].
##[debug]Processed: ##vso[task.logissue type=error]Unable to find type [VstsTaskSdk.TerminationException].
##[error]Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\run-task.ps1'''))"'.
##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''D:\a\_tasks\power-bi-utility-task_4d5cf5df-4506-483d-bf89-cf17465fb98a\1.0.24\run-task.ps1'''))"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
Finishing: PowerBI Utility

**Comment by abdulkareem-incresol** [comment]
Hello,

Any help on this would be really appreciable.

**Comment by maikvandergaag** [comment]
In what kind of scenario are you using the extension?

**Comment by abdulkareem-incresol** [comment]
Hi,

Our requirement is to automate a process of creating a workspace and publish a report (using a reference .pbix file but with different datasource configurations) on the newly created workspace. For this purpose, we need to modify the pbix file to change the database schema in its datasource configurations so that the newly published report points to new database schema.

Kindly note the database type is Sql.

**Comment by maikvandergaag** [comment]
@abdulkareem-incresol are you still having this issue?
