### ISSUE TITLE
ability to select release# and stage within the release

### ISSUE THREAD

**Issue by valerie-abb** [maikvandergaag/msft-extensions#186]
This extension triggers the creation of a new release in the destination pipeline, However, we are unable to specify an already created release#  as well as the manual stage to run within the release itself.
Wonder whether there is any plan to add these features or if there is a workaround solution to achieve this.

**Comment by JBoothUA** [comment]
THIS SHOULD BE THE NUMBER 1 PRIORITY!!!  HOW CAN YOU KICKOFF A PIPELINE AND NOT SPECIFY WHAT STAGE IT GOES TO??  IT MAKES NO SENSE TO NOT SUPPORT THIS.

**Comment by maikvandergaag** [comment]
Hi Jesse thanks for your comment. I do not appreciate the capitalized letters, as this a effort in my free time.

Currently do not have an idea If it is build in if it is not you can add it your self and file a pull request, other wise I will mark it as feature request and add it when I have time

Groetjes,

Maik van der Gaag
________________________________
Van: Jesse Booth <notifications@github.com>
Verzonden: Wednesday, August 5, 2020 11:03:35 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] ability to select release# and stage within the release (#186)


THIS SHOULD BE THE NUMBER 1 PRIORITY!!! HOW CAN YOU KICKOFF A PIPELINE AND NOT SPECIFY WHAT STAGE IT GOES TO?? IT MAKES NO SENSE TO NOT SUPPORT THIS.

**Comment by maikvandergaag** [comment]
This features is included in the release of today
