### ISSUE TITLE
"SQLDirect" Feature

### ISSUE THREAD

**Issue by OutKa5t** [maikvandergaag/msft-extensions#187]
Hi, 

Are you going to publish the changes you have made to allow "SQLDirect": "Update SQL Direct Query String"?

Thanks

**Comment by maikvandergaag** [comment]
Changes will be published in the next release this week! The extension will have an action called: Update SQL Direct Query String

**Comment by OutKa5t** [comment]
Any update on this? It hasnt made it to the Marketplace yet.
