### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by Santhoshnt** [maikvandergaag/msft-extensions#188]
Started using the Power BI Action to publish PBIX to PowerBI workspace. Have the service principal and locally tested using Powershell script that the REST API call to publish is working but when using the Power BI Action Agent job, getting 400 bad request.

2020-07-28T20:59:22.0777431Z Importing PowerBI File
2020-07-28T20:59:22.6161562Z ##[error]The remote server returned an error: (400) Bad Request.

**Comment by maikvandergaag** [comment]
Could you share some more information about the configuration?

Groetjes,

Maik van der Gaag
________________________________
Van: Santhoshnt <notifications@github.com>
Verzonden: Wednesday, July 29, 2020 10:17:40 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [maikvandergaag/msft-extensions] The remote server returned an error: (400) Bad Request. (#188)


Started using the Power BI Action to publish PBIX to PowerBI workspace. Have the service principal and locally tested using Powershell script that the REST API call to publish is working but when using the Power BI Action Agent job, getting 400 bad request.

2020-07-28T20:59:22.0777431Z Importing PowerBI File
2020-07-28T20:59:22.6161562Z ##[error]The remote server returned an error: (400) Bad Request.
