### ISSUE TITLE
Power BI Action : 401 Unauthorized.

### ISSUE THREAD

**Issue by rstones450** [maikvandergaag/msft-extensions#189]
Hello,

I apologize if this question has already been posted. I did search the forum, however was unable to find a satisfactory response.

Here are some details of our setup.

1. Ours is a single-tenant 
2. We did create the Service Principal + Group. 
3. Assigned Service Principal to Power-BI Workspace as Admin
4. Using ADO Repos/GIT 
5. Trying to automate the deploy process using Service Principal. Did create the Service Connection using the required id/secret token.

Here's the log that we observe.

![image](https://user-images.githubusercontent.com/69052108/89080478-93df0d80-d34e-11ea-88a8-8d739c234122.png)

Appreciate any pointers for us to debug.  Thank You.

**Comment by maikvandergaag** [comment]
Looks like it had problems while getting the PowerBI workspace information. Could you maybe share more information on the configuration?

For example did the task create the group? And if so does the sp has access on it? Next to that is the group a v2 workspace

Groetjes,

Maik van der Gaag
________________________________
Van: rstones450 <notifications@github.com>
Verzonden: Friday, July 31, 2020 11:58:25 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [maikvandergaag/msft-extensions] Power BI Action : 401 Unauthorized. (#189)


Hello,

I apologize if this question has already been posted. I did search the forum, however was unable to find a satisfactory response.

Here are some details of our setup.

  1.  Ours is a single-tenant
  2.  We did create the Service Principal + Group.
  3.  Assigned Service Principal to Power-BI Workspace as Admin
  4.  Using ADO Repos/GIT
  5.  Trying to automate the deploy process using Service Principal. Did create the Service Connection using the required id/secret token.

Here's the log that we observe.

[image]<https://user-images.githubusercontent.com/69052108/89080478-93df0d80-d34e-11ea-88a8-8d739c234122.png>

Appreciate any pointers for us to debug. Thank You.

**Comment by rstones450** [comment]
Much appreciate your response.

#1 Yes, it's a V2 Workspace

#2 Yes, I first added Service Principal (and to troubleshoot - you know trying multiple options) as the Admin the Workspace. Also added Group as an admin to the Workspace.

![image](https://user-images.githubusercontent.com/69052108/89188061-beee7a80-d563-11ea-854b-480e43dc5a8a.png)

Thank You.

**Comment by maikvandergaag** [comment]
Oké,

Could you also share some screenshots on your azure DevOps configuration?

Groetjes,

Maik van der Gaag
________________________________
Van: Stones R. <notifications@github.com>
Verzonden: Monday, August 3, 2020 3:33:37 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Power BI Action : 401 Unauthorized. (#189)


Much appreciate your response.

#1<https://github.com/maikvandergaag/msft-extensions/pull/1> Yes, it's a V2 Workspace

#2<https://github.com/maikvandergaag/msft-extensions/pull/2> Yes, I first added Service Principal (and to troubleshoot - you know trying multiple options) as the Admin the Workspace. Also added Group as an admin to the Workspace.

[image]<https://user-images.githubusercontent.com/69052108/89188061-beee7a80-d563-11ea-854b-480e43dc5a8a.png>

Thank You.

**Comment by rstones450** [comment]
May I know what details you are looking for? **ADO Configuration**

1. Service Connection in ADO(?); Or
2. Azure Active Directory (App Registration/Client Secret) Setup(?); Or
3. Release-Pipeline(?)

Please suggest. Just want to make sure what's expected. 

Thank You.

**Comment by maikvandergaag** [comment]
Firstly 1 or 2 but there could also be an error with the app for example. What kind of app are you using and can you authenticate with your app

Groetjes,

Maik van der Gaag
________________________________
Van: Stones R. <notifications@github.com>
Verzonden: Monday, August 3, 2020 6:59:06 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Power BI Action : 401 Unauthorized. (#189)


May I know what details you are looking for? ADO Configuration

  1.  Service Connection in ADO(?); Or
  2.  Azure Active Directory (App Registration/Client Secret) Setup(?); Or
  3.  Release-Pipeline(?)

Please suggest. Just want to make sure what's expected.

Thank You.

**Comment by rstones450** [comment]
Firstly, much appreciate for taking time and actively responding to my posts. Really appreciate it. 

Another would like to point out that this is a learning experience for us, so if any responses doesn't make sense, please feel free to call it out! 

1. What kind of app are you using
[SP] I am sorry, I didn't get your question. While registering for the App, we opted for the first option. Is this what you were referring to - "kind of App"? If it isn't, appreciate if you could elaborate.
![image](https://user-images.githubusercontent.com/69052108/89214689-e6a60880-d58c-11ea-8dee-8190c3395e93.png)

2. Can you authenticate with your app?
[Sp] Are you referring to Authentication in (1) or (2) to in the below screenshot? We created a Client Secret and used it for Authentication in the Service Connection.
![image](https://user-images.githubusercontent.com/69052108/89215061-8ebbd180-d58d-11ea-9177-1a6c65418746.png)


Below are the requested screenshots. 

**

### - Service Connection on ADO

**

![image](https://user-images.githubusercontent.com/69052108/89213670-0f2d0300-d58b-11ea-89db-08f0877b26f3.png)

![image](https://user-images.githubusercontent.com/69052108/89213639-03414100-d58b-11ea-8414-0ee2abd2a022.png)

![image](https://user-images.githubusercontent.com/69052108/89213777-38e62a00-d58b-11ea-93b9-0f09732096e1.png)

![image](https://user-images.githubusercontent.com/69052108/89213806-48657300-d58b-11ea-853e-c45f9abe744d.png)

### **Azure Active Directory**

### **App Registration.**
![image](https://user-images.githubusercontent.com/69052108/89213955-882c5a80-d58b-11ea-98f2-2b2ee0322227.png)

Question on the below setup. Do I need to provide our Power-BI Tenant URL at "1" in the below screenshot? 
![image](https://user-images.githubusercontent.com/69052108/89214161-eb1df180-d58b-11ea-9cd5-a79954fd2d0a.png)

![image](https://user-images.githubusercontent.com/69052108/89214266-1dc7ea00-d58c-11ea-844c-62450987b394.png)

### ADO - Release Pipeline.

![image](https://user-images.githubusercontent.com/69052108/89214395-5d8ed180-d58c-11ea-851f-a11b65a6f0d3.png)

**Comment by maikvandergaag** [comment]
What value did you fill in for the service principal key?

Groetjes,

Maik van der Gaag
________________________________
Van: Stones R. <notifications@github.com>
Verzonden: Monday, August 3, 2020 8:34:52 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Power BI Action : 401 Unauthorized. (#189)


Firstly, much appreciate for taking time and actively responding to my posts. Really appreciate it.

Another would like to point out that this is a learning experience for us, so if any responses doesn't make sense, please feel free to call it out!

  1.  What kind of app are you using
[SP] I am sorry, I didn't get your question. While registering for the App, we opted for the first option. Is this what you were referring to - "kind of App"? If it isn't, appreciate if you could elaborate.
[image]<https://user-images.githubusercontent.com/69052108/89214689-e6a60880-d58c-11ea-8dee-8190c3395e93.png>

  2.  Can you authenticate with your app?
[Sp] Are you referring to Authentication in (1) or (2) to in the below screenshot? We created a Client Secret and used it for Authentication in the Service Connection.
[image]<https://user-images.githubusercontent.com/69052108/89215061-8ebbd180-d58d-11ea-9177-1a6c65418746.png>

Below are the requested screenshots.

**

- Service Connection on ADO

**

[image]<https://user-images.githubusercontent.com/69052108/89213670-0f2d0300-d58b-11ea-89db-08f0877b26f3.png>

[image]<https://user-images.githubusercontent.com/69052108/89213639-03414100-d58b-11ea-8414-0ee2abd2a022.png>

[image]<https://user-images.githubusercontent.com/69052108/89213777-38e62a00-d58b-11ea-93b9-0f09732096e1.png>

[image]<https://user-images.githubusercontent.com/69052108/89213806-48657300-d58b-11ea-853e-c45f9abe744d.png>

Azure Active Directory
App Registration.

[image]<https://user-images.githubusercontent.com/69052108/89213955-882c5a80-d58b-11ea-98f2-2b2ee0322227.png>

Question on the below setup. Do I need to provide our Power-BI Tenant URL at "1" in the below screenshot?
[image]<https://user-images.githubusercontent.com/69052108/89214161-eb1df180-d58b-11ea-9cd5-a79954fd2d0a.png>

[image]<https://user-images.githubusercontent.com/69052108/89214266-1dc7ea00-d58c-11ea-844c-62450987b394.png>

ADO - Release Pipeline.

[image]<https://user-images.githubusercontent.com/69052108/89214395-5d8ed180-d58c-11ea-851f-a11b65a6f0d3.png>

**Comment by rstones450** [comment]
Hello,

As recommended in the instructions, we created a new Client Secret for SP and the value in (1) below was used as Service Principal Key.

Thank You.

![image](https://user-images.githubusercontent.com/69052108/89224829-c67f4500-d59e-11ea-927e-439154901e33.png)

**Comment by maikvandergaag** [comment]
Oké, that seems right, regarding the authentication I meant are you able to retrieve a token from Azure Ad for that application and you that token for for example a get PowerBI operation.

For as far as I can see now your current configuration looks oké! There is or an error in the extension which I can’t imagine because I then would have multiple other issues regarding this, but there must be something small in the configuration, what you could do is also check the other issues because there was someone with the similar issue a few months ago.

I’m back from vacation in a week I then have more resource to assist you.

Groetjes,

Maik van der Gaag
________________________________
Van: Stones R. <notifications@github.com>
Verzonden: Monday, August 3, 2020 10:34:46 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Power BI Action : 401 Unauthorized. (#189)


Hello,

As recommended in the instructions, we created a new Client Secret for SP and the value in (1) below was used as Service Principal Key.

Thank You.

[image]<https://user-images.githubusercontent.com/69052108/89224829-c67f4500-d59e-11ea-927e-439154901e33.png>

**Comment by rstones450** [comment]
Much appreciate your inputs so far. Will keep digging through the issue. Have a good time off! 

Thank You.

**Comment by rstones450** [comment]
Hello,

Thought I would post.

_"Oké, that seems right, regarding the authentication I meant are you able to retrieve a token from Azure Ad for that application and you that token for for example a get PowerBI operation."_

Not sure if this is what you meant, but I followed the link.

https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-oauth-code

I followed the instructions here.
![image](https://user-images.githubusercontent.com/69052108/89663193-d21e8480-d89a-11ea-910a-adbb8c04b2ad.png)

This is my link.
https://login.microsoftonline.com/<my Tenant-ID>/oauth2/authorize?client_id=<Application-ID>&response_type=code&scope=user_impersonation

And it did take me to the Power-BI Workspace Screen. So my assumption is that the Client-ID is working.

Thought I would post my observation. I'll keep troubleshooting. 

Thanks!

**Comment by maikvandergaag** [comment]
This looks kind off right but the authentication used by the provider isn’t using that scope.

Groetjes,

Maik van der Gaag
________________________________
Van: Stones R. <notifications@github.com>
Verzonden: Friday, August 7, 2020 5:45:26 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Power BI Action : 401 Unauthorized. (#189)


Hello,

Thought I would post.

"Oké, that seems right, regarding the authentication I meant are you able to retrieve a token from Azure Ad for that application and you that token for for example a get PowerBI operation."

Not sure if this is what you meant, but I followed the link.

https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-oauth-code

I followed the instructions here.
[image]<https://user-images.githubusercontent.com/69052108/89663193-d21e8480-d89a-11ea-910a-adbb8c04b2ad.png>

This is my link.
https://login.microsoftonline.com//oauth2/authorize?client_id=&response_type=code&scope=user_impersonation

And it did take me to the Power-BI Workspace Screen. So my assumption is that the Client-ID is working.

Thought I would post my observation. I'll keep troubleshooting.

Thanks!

**Comment by maikvandergaag** [comment]
Did you also complete this step in the guide:

![image](https://user-images.githubusercontent.com/9531411/90218013-05b15f80-de03-11ea-8b32-8daf5678b9f5.png)

**Comment by maikvandergaag** [comment]
Did you also consider these points:

- Service principal only works with new workspaces.
- My Workspace isn't supported when using service principal.
- Dedicated capacity is required when moving to production.
- You can't sign into the Power BI portal using service principal.
- Power BI admin rights are required to enable service principal in developer settings within the Power BI admin portal.
- Embed for your organization applications can't use service principal.
- Dataflows management is not supported.
- Service principal currently does not support any admin APIs.
- When using service principal with an Azure Analysis Services data source, the service principal itself must have an Azure - - 
 - Analysis Services instance permissions. Using a security group that contains the service principal for this purpose, doesn't work.

**Comment by rstones450** [comment]
Hello!

-------------------------------------------------------------------------------------
1. Yes, I did add the AAD Group which I created to the Power BI Admin Role.

2. Responses for the below are marked with.
_Service principal only works with new workspaces._
Yes. It's a new workspace ("sppowerbidemo"). I created a new workspace just to test this ADO Flow.

_My Workspace isn't supported when using service principal._
Yes. It isn't "My Workspace". It's, as given in my screenshots, "sppowerbidemo" 

_Dedicated capacity is required when moving to production._
Not sure, what "production" means here. I am testing with sample workspace created in my powerbi service. However I do see "dedicated capacity" turned off.

![image](https://user-images.githubusercontent.com/69052108/90415083-38af5980-e076-11ea-9c5f-273d62c1e377.png)

_You can't sign into the Power BI portal using service principal._
Yes, I am not using SP to signin.

_Power BI admin rights are required to enable service principal in developer settings within the Power BI admin portal._
Yes, I had my Admin add AAD Group to the Admins. Also, I was able to Add the AAD-Group and the SPs to the Workspace - sppowerbidemo, as admins too. 

![image](https://user-images.githubusercontent.com/69052108/90415268-790ed780-e076-11ea-991d-14d57c558713.png)

_Embed for your organization applications can't use service principal._
Noted. We aren't looking towards using this feature either.

_Dataflows management is not supported._
Noted. We aren't looking towards using this feature either.

_Service principal currently does not support any admin APIs._
Noted. We aren't looking towards using this feature either.

_When using service principal with an Azure Analysis Services data source, the service principal itself must have an Azure - -
Analysis Services instance permissions. Using a security group that contains the service principal for this purpose, doesn't work._
Both the above are not-applicable in our case.

-----------------------------------------------------------------------------------------

Additional observation.

I see that in the issue (183) there was a comment about endpoint for Government Tenant. Ours too is a government tenant, not sure how this is impacting the connections.

Thank You.

**Comment by maikvandergaag** [comment]
As mentioned the governance part could be the case. I think but I am not sure that it uses different api urls to do the actions do you know that maybe.

If that is the case I could adjust the extension to also work with the governance api's

**Comment by rstones450** [comment]
Much appreciate your follow up and the potential inclusion of Government APIs. Will be looking forward to an update.

I have a question, should have asked earlier. In your comment, you mentioned 'provider' & 'scope'

This may seem a dumb question, but may I know what you meant by "Provider" and also, the other possible options for "Scope"?

![image](https://user-images.githubusercontent.com/69052108/90437725-745b1b00-e098-11ea-8324-07d10c9c75f6.png)

Thank You.

**Comment by maikvandergaag** [comment]
That all belongs to how you authenticate. At the moment I'm investigating how the connection to a governance tenant is different I will keep you posted and will work further on this issue and close the other (#183 ).

**Comment by maikvandergaag** [comment]
@rstones450: I have investigated a few things but would also like to test some things out so that I can add it to the extension, could we maybe discuss options for testing?

**Comment by rstones450** [comment]
Much appreciate your follow up. 

Please do let me know what kind of options you are looking at for testing.

Thank You.

**Comment by maikvandergaag** [comment]
Shall we discuss that via mail? Info @ msftplayground . com

**Comment by rstones450** [comment]
@maikvandergaag  - I just did. Thank You.

**Comment by maikvandergaag** [comment]
Government support is added to the extension.
