### ISSUE TITLE
Multiple Build and Release trigger 

### ISSUE THREAD

**Issue by kumarkaran1** [maikvandergaag/msft-extensions#190]
can we trigger at time multiple builds and release  .. 
it will be great if we will get multiple checkbox to select build and release

**Comment by maikvandergaag** [comment]
Will add this to the feature request.

Groetjes,

Maik van der Gaag
________________________________
Van: kumarkaran1 <notifications@github.com>
Verzonden: Monday, August 3, 2020 10:53:00 AM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [maikvandergaag/msft-extensions] Multiple Build and Release trigger (#190)


can we trigger at time multiple builds and release ..
it will be great if we will get multiple checkbox to select build and release

**Comment by maikvandergaag** [comment]
Checked the posibility but when you would like this you should add the extensions 2 times to the flow
