### ISSUE TITLE
Accessing WS metadata exchange failed

### ISSUE THREAD

**Issue by GerardLarwa** [maikvandergaag/msft-extensions#192]
Hi. I'm trying to publish pbix report, but still receiving following error. AAD app has been registered by PowerBI service: [dev.powerbi.com/apps](url). Authentication is based on service AAD user, MFA disabled.

`
[...]
System.Management.Automation.MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed" ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (BadRequest). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: : Unknown error
[...]
Exception calling "GetResult" with "0" argument(s): "accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed"
]Processed: ##vso[task.logissue type=error]Exception calling "GetResult" with "0" argument(s): "accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed"
`

AAD API permissions:
![image](https://user-images.githubusercontent.com/44910018/90118372-6f286400-dd58-11ea-9a2d-4e8a84001d86.png)

**Comment by maikvandergaag** [comment]
This indicated that there is something wrong with your report, could you try it with a really simple report?

**Comment by GerardLarwa** [comment]
I think it's not a problem with report. It happened even with a sample report provided by Microsoft. The error is occurred at the same beginning, during AAD authentication I suppose.

**Comment by maikvandergaag** [comment]
Could you add the variable System.Debug with the value true to your pipeline and send me a screenshot of the run?

**Comment by GerardLarwa** [comment]
![image](https://user-images.githubusercontent.com/44910018/90488682-8db5a300-e13c-11ea-83f1-1fe368214cb4.png)

**Comment by maikvandergaag** [comment]
Does the user has MFA activated?

**Comment by GerardLarwa** [comment]
Nope, it's a service user and according to my organization policy all service users have MFA disabled.

**Comment by maikvandergaag** [comment]
Can you login to PowerBI with that user account and password without MFA and create workspace?

Met vriendelijke groet,

Maik van der Gaag

**Comment by GerardLarwa** [comment]
Yes, I can. I have additional popup when logging in.

![image](https://user-images.githubusercontent.com/44910018/90508153-7801a700-e157-11ea-924f-89638cd77c97.png)

**Comment by maikvandergaag** [comment]
That looks like A ADFS pop-up and that is not supported. Then you will need to use the service principal authentication option.

Groetjes,

Maik van der Gaag
________________________________
Van: GerardLarwa <notifications@github.com>
Verzonden: Tuesday, August 18, 2020 1:35:41 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Accessing WS metadata exchange failed (#192)


Yes, I can. I have additional popup when logging in.

[image]<https://user-images.githubusercontent.com/44910018/90508153-7801a700-e157-11ea-924f-89638cd77c97.png>
