### ISSUE TITLE
Publishing Direct Query Reports cannot change connection string to reflect Datasource

### ISSUE THREAD

**Issue by BeSightDev** [maikvandergaag/msft-extensions#195]
We have a bunch of PowerBI reports we need to deploy on different workspaces , each workspace has it's own datasources ( On Premise Gateway ) and by now we change connection string in PowerBI Desktop before Publishing report in the correct WorkArea

We have setup a git repo and a DevOps pipeline with your addon but no way to publish a single report in 4 different stages changing at each stage the connection string to reflect the correct DataSet 

I've seen that direct query connection string change is a feature but cannot find it in the addon editing the stage in the pipeline release

We tried using Change Datasource Connection but probably it's not the correct action for Direct Query Reports with On Premise Gateways

Waiting

Thanks a lot :-)

Paolo

<img width="954" alt="Schermata 2020-08-25 alle 14 56 33" src="https://user-images.githubusercontent.com/58431175/91176897-363aa880-e6e3-11ea-8f8c-e6ce45e5d470.png">

**Comment by BeSightDev** [comment]
You see the same ad old and new server and database as long as this is first stage and in this case server and database are the same ... and it was also to make a try and see if it was working ...
Anyway also trying with different server and database does not work
It could be nice not to have the need to specify old server / old database ... getting this infos directly from the report itself
Tks

**Comment by BeSightDev** [comment]
<img width="1371" alt="Schermata 2020-08-25 alle 15 01 47" src="https://user-images.githubusercontent.com/58431175/91177829-967e1a00-e6e4-11ea-9164-efd8c551cf72.png">
<img width="1333" alt="Schermata 2020-08-25 alle 15 05 14" src="https://user-images.githubusercontent.com/58431175/91177832-97af4700-e6e4-11ea-8b22-a433c997a591.png">

**Comment by maikvandergaag** [comment]
@BeSightDev: I have a beta release of the extension with the DirectQuery option, but I'm not sure if it is possible with the gateway.

You can try if you want, If you would like access to the Beta version you can share your DevOps organizaiton name with my and I will give you the link to download the extension.

**Comment by tommasostocchialterna** [comment]
Hi @maikvandergaag, I am the DevOps working for BeSight. Our organization name is https://dev.azure.com/besight/. We would appreciate if you could share a Beta with us.

**Comment by BeSightDev** [comment]
Dear @maikvandergaag Tommaso wrote you upon my request :-) tks for your support we wait for the link of beta version to try
Tks 
Paolo

**Comment by maikvandergaag** [comment]
No problem, the extension is shared with your organization. You can install via the following link: https://marketplace.visualstudio.com/items?itemName=Development-vanderGaag.maikvandergaag-power-bi-actionsDev

**Comment by BeSightDev** [comment]
Thank you very much we will try and let you know 👍

**Comment by tommasostocchialterna** [comment]
@maikvandergaag if I follow the link I get
![image](https://user-images.githubusercontent.com/64259036/91280910-be728980-e787-11ea-8957-e5896fc0d253.png)

**Comment by maikvandergaag** [comment]
@tommasostocchialterna: could you try the following:
- login to your azure devops organization in a private session.
- From within Azure DevOps open the marketplace
- Check if you can find the extension with the following search: Development-vanderGaag.maikvandergaag-power-bi-actionsDev
or open the link in another tab and make sure you login with the account of azure devops.

**Comment by tommasostocchialterna** [comment]
Same result :(

**Comment by maikvandergaag** [comment]
Could you try again, it looks like there was something wrong with the sharing of the extension.

Met vriendelijke groet,

Maik van der Gaag

**Comment by BeSightDev** [comment]
I'm sorry to tell you that does not work
We will investigate trying with Postman the sending of the commands for REST API 
With Update SQL Connection String we get Error 400 Invalid Operation

**Comment by maikvandergaag** [comment]
That would be great if I know the correct API connection and payloads I am able to build it in

Groetjes,

Maik van der Gaag
________________________________
Van: BeSightDev <notifications@github.com>
Verzonden: Wednesday, August 26, 2020 7:07:06 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Publishing Direct Query Reports cannot change connection string to reflect Datasource (#195)


I'm sorry to tell you that does not work
We will investigate trying with Postman the sending of the commands for REST API
With Update SQL Connection String we get Error 400 Invalid Operation
