### ISSUE TITLE
powerbi update parameters on different tenants with different users on powerbi and backend crm

### ISSUE THREAD

**Issue by rajeshwar2kc** [maikvandergaag/msft-extensions#198]
Hi, 

can this  be used to update parameters if Powerbi and CRM( Backend datasource) are on different tenants and having different user ids( Ex powerbi report is published with userA existing on powerbi workspace and backend  CRM is a different user(userB)

**Comment by maikvandergaag** [comment]
Not sure a situation like that isn't tested at this moment so you should try.

My guess is that it will work because the extension only communicates with PowerBI and not with any other product.
