### ISSUE TITLE
Update SQL Direct Query String

### ISSUE THREAD

**Issue by nowag4000** [maikvandergaag/msft-extensions#202]
Hello,
I'm using the Action "Update SQL Direct Query String" from your PowerBi extension. 
I get the error "##[error]The remote server returned an error: (400) Bad Request.". 

My Connection String looks as follows: 
Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword; 

Is there already a fault or could it be something else?

Thanks for your help and the great PowerBi extension, it helps a lot. @maikvandergaag

**Comment by maikvandergaag** [comment]
Hi,

Try adding the following variable to the pipeline: “system.debug” with the value “true”. Then send me the log of the task and also a screenshot of the task configuration.

With regards,

Maik van der Gaag

**Comment by nowag4000** [comment]
Hi, 
 here is the screenshot and the log is in the txt-file.

Greetings Noah

[Log.txt](https://github.com/maikvandergaag/msft-extensions/files/5209270/Log.txt)
![Task Configuration](https://user-images.githubusercontent.com/63406312/92931279-85067300-f443-11ea-8e9e-38b441e327fd.PNG)

**Comment by maikvandergaag** [comment]
Have you tried other options. Last weeks I have been busy with a version to support the government cloud.

**Comment by nowag4000** [comment]
Hello,
I used the following PowerShell Script and it worked. 

[Script set credentials.txt](https://github.com/maikvandergaag/msft-extensions/files/5260801/Script.set.credentials.txt)

**Comment by maikvandergaag** [comment]
Hi nowag400,

Thank you for your script. It looks like you settings properties for the datagateway (is this correct) and not the SQL Connection string. I did not have an opportunity to test this is the current version of the extension.

But with your script I will be able to try to at it.
