### ISSUE TITLE
File name with special symbol

### ISSUE THREAD

**Issue by nitmatgeo** [maikvandergaag/msft-extensions#203]
**_Hi_** _Maik_**_,_** First of all thank you for the wonderful effort which even MS have not come forward so far. Applause :1st_place_medal: 
Recently, I observed 2 things-
**1.** Checking if Workspace already created works only if the Workspace was created using the plugin. (_No big deal for now, just felt so_)
**2.** The PBI file name having special characters like '&' is having an issue while getting published. The '&' seems to be misinterpreted as a URL parameter and thus the characters in the name after '&' are being excluded. Would appreciate if you could actually fix this ASAP. I assume this being a small change. Thanks in advance.
**Note:** I observed that the report is created in Filename 'P'.

![image](https://user-images.githubusercontent.com/71626368/93737700-7a956780-fc01-11ea-9c49-be88d260612b.png)

**Comment by maikvandergaag** [comment]
Hi @nitmatgeo,

The issues occurs when publishing for the second time. Then the system sees it for an additional parameter. The fix is in the system just doing the latest test.

**Comment by maikvandergaag** [comment]
Code is tested and is in the release pipeline at this moment

**Comment by nitmatgeo** [comment]
Thanks; will check and confirm. Also FYI for workspace I follow naming convention as "BI $Environment\$Department"; so while updating data source etc, the workspace invoke involves a "\". In case this was not handled earlier, please consider :)

**Comment by nitmatgeo** [comment]
Thanks; this is working great now. Also FYI for workspace I follow naming convention as "BI $Environment\\$Department"; so while updating data source etc, the workspace invoke involves a "\\". In case this was not handled earlier, please consider :)

BI $Environment(backslash)$Department

Also, updating **parameters** (variables) in data source of dateset.. is that already planned or should I raise it separately? Basically trying to avoid the OldDB & OldServer details in DataSource Update task.

**Comment by maikvandergaag** [comment]
If you could raise it seperatly that would be great. I'm first working on the implementation of government support. This will be a major update.

**Comment by nitmatgeo** [comment]
> If you could raise it seperatly that would be great. I'm first working on the implementation of government support. This will be a major update.

Yap, have raised it separately as an issue. Please let me know if any :) When I have time, I will also check if I can be helpful for the same.
