### ISSUE TITLE
PowerBI Workspace name does not allow spaces, datasets do

### ISSUE THREAD

**Issue by BobJMW** [maikvandergaag/msft-extensions#214]
When refreshing a data set the data set name can have spaces between characters, but the workspace name must be a single string. 
Would it be possible to allow spaces in the workspace name just like is possible with the data sets? This could be of great convenience to us, because we share workspaces with customers.

**Comment by nitmatgeo** [comment]
@BobJMW  I think I was able to create a workspace with space in it, I had used special characters as well. Did you include the name within "Work Space Name"?

If you still have issues, please share the task configuration screenshot and pipeline logs after setting system.debug variable in release pipeline and then setting the value as true.

**Comment by BobJMW** [comment]
Thank you for the quick reaction! I tested it again today on two different PBI workspaces and it seems to work fine. Maybe it was a hiccup or something, because removing the space from the name solved the issue earlier. 
We use the plugin quite a lot and we are are very happy with it, so glad this works now as well.

**Comment by maikvandergaag** [comment]
Great to hear @BobJMW and thanks for your response @nitmatgeo.

If there are any other things just let me know.
