### ISSUE TITLE
Feature Request Bind gateway & Datasources to Dataset

### ISSUE THREAD

**Issue by nitin-AET-Tankers** [maikvandergaag/msft-extensions#216]
@maikvandergaag Am back to trouble you again 😉  But no worries, I will also contribute depending on my schedules 😄 
**Intention:**
1. Get list of Gateways
2. Get GatewayID whose name is (in pipeline variable)
3. Get Datasources for that gatewayID
4. For each datasetID in a WorkSpace, the bind the datasource & gateway (generate a json body for post)

**Challenge**
The tricky thing here is, scenarios may differ; in my scenario, I have a same Gateway with 3 different data sources (_database_). I already have parameters to define the database in each dataset. In my case, I just need to lookup the database name in each dataset and then pick up the datasource for binding. I don't know which way it should be considered; **what's your recommendation?**
Is it okay if we have a JSON with- ServerURL, DatabaseName, GatewayName & DatasourceName AND lookup the Server & database mentioned in dataset and based on match with JSON bind the gateway. **Is this approach fine?**

**Comment by maikvandergaag** [comment]
Hi @nitin-AET-Tankers,

At the moment I have a lot of work on my plate. Will try to get back to you during the weekend. If I do not respond just ping me no problem.

Important thing for the extension is that it needs to be a generic situation that can be reused by others ass well.

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  I think currently there is a limitation to use this with SPN; this require Master Account Auth I guess. Any idea?
I will continue my analysis with master account for the time being 😄

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  An update:
One more function, I will be ready with Gateway as well. My scenario is applicable for SQL type only. To my understanding, I think SPN currently doesn't support; **if possible please help to confirm on this**.

_New Functions added:_
1. Get-PowerBIGateways
2. Get-PowerBIGatewayDataSources
3. Get-PowerBIDatasetDatasourcesInGroup
4. Get-PowerBIDatasetDatasourceInGroup

I am continuing my tests as Master Account for time being.

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Pull Req #217 FYA & Review 😄 

I was not getting result if I use SPN; Please take a look at the comments I added in the Pull request. Also help to update the JSON task of DevOps task.

**Comment by maikvandergaag** [comment]
I have just pushed out a beta version. I changed the Update method where i removed to take ownership. This should be done in a seperate action.

**Comment by maikvandergaag** [comment]
Beta should be there in 5 minutes

**Comment by nitin-AET-Tankers** [comment]
Is there a conflict? Other tasks prior to this were using SPN; first time I was trying Master Account; I saw below error- Any idea?

![image](https://user-images.githubusercontent.com/71818170/95447563-7e144700-0994-11eb-8619-1c2904c80f84.png)

**Comment by maikvandergaag** [comment]
Seems like a authentication issue, could you maybe share the log? And is the account using MFA?

**Comment by nitin-AET-Tankers** [comment]
[tasklog_10.log](https://github.com/maikvandergaag/msft-extensions/files/5347197/tasklog_10.log)
Please acknowledge i will be deleting this comment..

We use a user account thats marked as service account; So i dont think MFA.

**Comment by maikvandergaag** [comment]
Could you check the MFA part

**Comment by nitin-AET-Tankers** [comment]
> Could you check the MFA part

When I login I get a screen to setup mailID etc. That could be a reason?

**Comment by maikvandergaag** [comment]
Maybe, just checked the authentication within the extension and that runs perfectly. It could also be something in your service connection configuration.

**Comment by nitin-AET-Tankers** [comment]
But I am able to login I powershell manually by using 'Connect-PowerBIServiceAccount'.. Let me try disabling other tasks

**Comment by nitin-AET-Tankers** [comment]
![image](https://user-images.githubusercontent.com/71818170/95459421-35658980-09a6-11eb-812d-8a724d483815.png)

MFA isn't configured; maybe this screen is causign an issue?

**Comment by nitin-AET-Tankers** [comment]
Apologies, I think I missed the domain in username; I recreated the serviceConnectoin. It went through

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Please review and approve the pull request #220

**Comment by maikvandergaag** [comment]
Looks good, merged it to the beta branch will be deployed in 5 min. 5.2.7

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag When you merger to master, please add a ' (**dataset name within a single quote**); seems I have missed that for Dataset refresh. I think we are good to rollout; any issues will fix as we notice. 

Meanwhile I will check with a single dataset as well instead of $updateAll

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag I tried to refresh a particular dataset
![image](https://user-images.githubusercontent.com/71818170/95570491-9306de00-0a59-11eb-87cf-a94eb133b12c.png)

But ended up refreshing everything.. Did I mess up something? 😟

**Comment by maikvandergaag** [comment]
mhh that is strange do you have a log we fixed that yesterday

**Comment by nitin-AET-Tankers** [comment]
[tasklog_9.log](https://github.com/maikvandergaag/msft-extensions/files/5354379/tasklog_9.log)


@maikvandergaag  I will be removing this :D

**Comment by maikvandergaag** [comment]
@nitin-AET-Tankers I have changed the module code and that should be reflecting better in the task. The change also impacts the Gateway and Parameter action. If you could check those as well that would be great.

**Comment by nitin-AET-Tankers** [comment]
Sure will check @maikvandergaag ; Any idea about the issue?

**Comment by nitin-AET-Tankers** [comment]
Ownership: I think it skipped without processing. Rest I will Update

**Comment by nitmatgeo** [comment]
@maikvandergaag please let me know if you need my help

**Comment by maikvandergaag** [comment]
@nitmatgeo do you mean it didn't work. If yes could you share your logs again of the failed runs?

**Comment by nitin-AET-Tankers** [comment]
[tasklog_10 (1).log](https://github.com/maikvandergaag/msft-extensions/files/5358584/tasklog_10.1.log)
[tasklog_8.log](https://github.com/maikvandergaag/msft-extensions/files/5358585/tasklog_8.log)


Yes, it didn't work; seems it skipped executing 
@maikvandergaag Please acknowledge; i will be deleting this

**Comment by maikvandergaag** [comment]
@nitin-AET-Tankers: made a change, due to the change the write-host function was removed

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag 
I still do not see the logs.. same as in case of Ownership task. 
![image](https://user-images.githubusercontent.com/71818170/95651216-51d70280-0b1b-11eb-8d7d-bb0fd9084dd2.png)

**Comment by nitin-AET-Tankers** [comment]
Config:
![image](https://user-images.githubusercontent.com/71818170/95651239-919dea00-0b1b-11eb-80be-c30f67610d44.png)

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag I still do not see the logs across each dataset processing.. same issue for the Ownership task. 
Slightly held up that's why couldn't analyse deeply...

![image](https://user-images.githubusercontent.com/71818170/95652022-bba5db00-0b20-11eb-8120-e6116dfceddb.png)

**Comment by maikvandergaag** [comment]
Tested it again on my end and it seems to be fully working.

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag Are you able to see logs in Gateway task corresponding to each dataset?

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Fir updateAll it isn't working.. Line 103 { foreach ($dataset in $datasets) } of function {Update-PowerBIDatasetDatasourcesInGroup} $datasets is not defined; that's a reason. Will you be able to assist on this, please?
Similar fix needs for ownership as well...

**Comment by maikvandergaag** [comment]
The fixed should be in place. No idea what happened to that line

**Comment by nitin-AET-Tankers** [comment]
ok want me to test right?

**Comment by maikvandergaag** [comment]
if you can please

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Resolved for gateway.. but for Ownership the issue is there if I use UpdateAll. I can see you have included the line, I think I will have to locally run and debug...

**Comment by maikvandergaag** [comment]
@nitin-AET-Tankers the ownership issue was send later to the build and release pipeline. Just saw that it had a minor hiccup. Rebuilding at this moment give it a few minutes

**Comment by nitin-AET-Tankers** [comment]
@maikvandergaag  Cheers ✋ 
All success.. I was starting to break my head debugging and rightly saw your notification hehe..
So, we are ready for rollout right? 😆 
Cuz of gateway, I need to switch to Master Auth from SPN... Will update my tasks after the rollout 👍

**Comment by maikvandergaag** [comment]
It's is in the release process

**Comment by nitin-AET-Tankers** [comment]
Many thanks, will update if any issues 👍
