### ISSUE TITLE
Deployment Issue with Service Connection

### ISSUE THREAD

**Issue by paulkeys2** [maikvandergaag/msft-extensions#223]
Hi,

We have an issue with the service connection; posted in developer community on the link below;

https://developercommunity.visualstudio.com/content/problem/1216174/deployment-pipeline-not-working.html

Would you be able to provide any guidance?

**Comment by maikvandergaag** [comment]
Off course how do you have it configured at this moment.

**Comment by paulkeys2** [comment]
Thanks for responding. We currently have it configured to use a service principal which has admin access to the Power BI workspace we are trying to deploy in to.  We can't use username/password due to MFA restrictions

**Comment by maikvandergaag** [comment]
@paulkeys2 oke that sounds good. Did you follow this guide: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-service-principal

And did you try to let the service principal create the workspace?

Could you besides that info send me the logs with the system.debug variable set to true.

**Comment by paulkeys2** [comment]
@maikvandergaag we have the service principal settings applied in the tenant as per that guide.  Will the process only work if it's a workspace created by the service principal?

I've emailed you the logs, let me know if any further info required

**Comment by maikvandergaag** [comment]
You should try it as there are specific prerequisites for the service principals

**Comment by paulkeys2** [comment]
OK thanks, will try that and report back

**Comment by maikvandergaag** [comment]
What is also important is to check the configuration of the service connection. Make sure you have selected the correct cloud type.

**Comment by paulkeys2** [comment]
Hi, we got a little further when we created a workspace with the Service Principal and attempted to publish into that.

I've emailed you the updated debug logs if you can take a look

**Comment by uchitha** [comment]
@paulkeys2 I have recently got this to work without many issues. Please let me know if I can be of any help. (I setup a brand new tenant and service principals for this)

**Comment by Ragunath452** [comment]
> @paulkeys2 I have recently got this to work without many issues. Please let me know if I can be of any help. (I setup a brand new tenant and service principals for this)

can you help us on this ?

**Comment by maikvandergaag** [comment]
What issues are you having @Ragunath452
