### ISSUE TITLE
AZ_ResourceNotFound0

### ISSUE THREAD

**Issue by bahadir-be** [maikvandergaag/msft-extensions#225]
![image](https://user-images.githubusercontent.com/62173919/96151507-c0490580-0f0b-11eb-9cc3-61fef486e3ea.png)

Regarding : Publish Stream Analytics 

I have received this error message, but Stream Analytics on there.

![image](https://user-images.githubusercontent.com/62173919/96151709-0605ce00-0f0c-11eb-93b6-b4ba718a2b21.png)

What is wrong?
Thanks

**Comment by maikvandergaag** [comment]
Hi Bahadir,

Do I understand you correctly that the Stream analytics job is published but it still throws the error? Is the Job correct?

Could you maybe rerun the pipeline with the variable System.debug with the value true added to the pipeline?

Met vriendelijke groet,

Maik van der Gaag

**Comment by bahadir-be** [comment]
Hallo Maik,
Yes indeed.
Stream analytics job ( name : DevopsTest ) is active and stopped.

![image](https://user-images.githubusercontent.com/62173919/96163154-cf36b480-0f19-11eb-9d1e-03578595e68e.png)

**Comment by bahadir-be** [comment]
[tasklog_13.log](https://github.com/maikvandergaag/msft-extensions/files/5398133/tasklog_13.log)
Please see attachment

**Comment by maikvandergaag** [comment]
How does the resource group look like were it tries to publish to? And could you share a screenshot of the task?

**Comment by bahadir-be** [comment]
Maik,
Thanks for your feedback.
you can see on below;
![image](https://user-images.githubusercontent.com/62173919/96431861-65155c80-1204-11eb-8933-16a10162fb6c.png)

![image](https://user-images.githubusercontent.com/62173919/96432060-a9086180-1204-11eb-9869-0c6c9a6aa036.png)

**Comment by bahadir-be** [comment]
@maikvandergaag what do you think?

**Comment by maikvandergaag** [comment]
Any progress on this
