### ISSUE TITLE
Action Add users to workspace: Cannot add multiple users to a new workspace

### ISSUE THREAD

**Issue by BobJMW** [maikvandergaag/msft-extensions#226]
Hi,

Unfortunately I cannot add multiple users as an Admin to a new created workspace. One user is fine, but when I try to add multiple it doesn't work. 

The image below shows the configuration of the PowerBI task.
![add user example](https://user-images.githubusercontent.com/71691528/96447601-6fd6ee00-1212-11eb-90e8-dc9b570408a1.png)

According the additional information a comma ',' should separate the emails. Is that right?

The error message in the log says that a user is not found. However if I place that user in the first position it is found.

**Comment by AmandineYborra** [comment]
Hi BobJMW,

I had the same problem and I fix this with delete the space after every comma. 
There should not be a single space between email

**Comment by maikvandergaag** [comment]
@AmandineYborra: thanks for your help. Will try to get this out of the extension. @BobJMW do you maybe have the log for me to see what is going wrong.

**Comment by BobJMW** [comment]
@maikvandergaag please find the log files attached. Hopefully they help you solving the issue
[ReleaseLog.zip](https://github.com/maikvandergaag/msft-extensions/files/5671195/ReleaseLog.zip)

**Comment by maikvandergaag** [comment]
@BobJMW: 

Could you remove the space, and if it does not work add the system.debug variable with the value true to the pipeline and send met a screenshot of the configuration and the log.
