### ISSUE TITLE
Error while updating Parameter value of Pbix dataset in Power BI

### ISSUE THREAD

**Issue by Sim1266** [maikvandergaag/msft-extensions#227]
Hi,

I am getting below error while trying to update the parameter of the pbix dataset. I am using action 'Update Parameters'. Could you please assist?

**Error : "Cannot bind argument to parameter 'Set' because it is null"**

**Comment by joaovictormelo42** [comment]
Hi! Did you get the solution of this problem? I have the same return, but in the Take Ownership Action, and my parameter is 'DataSet'.

**Comment by maikvandergaag** [comment]
Could you send the log file?

**Comment by joaovictormelo42** [comment]
> Could you send the log file?

Hi Maik, i figure out whats happening, i'm sorry to being late on my answer here. But thank you anyway!

**Comment by maikvandergaag** [comment]
Could you add it to the issue?

**Comment by joaovictormelo42** [comment]
My problem was happening because i forgot to use " " on the name of my variable in the powershell cmd.
