### ISSUE TITLE
"MultiPartMimeStreamFormatException","pbi.error"

### ISSUE THREAD

**Issue by ssorokoski** [maikvandergaag/msft-extensions#230]
I have been working on this for quite a while and I simply cannot upload a .pbix file to a workspace. I am running this locally and am using the new powerbi-endpoint-type-consolidated connection type with spn. I am also able to successfully execute the  Get-PowerBIWorkspace function and return a workspace however I cannot upload a file. 

I always receive this error: 

{"error":{"code":"MultiPartMimeStreamFormatException","pbi.error":{"code":"MultiPartMimeStreamFormatException","parameters":[],"details":[],"exceptionCulprit":1}}}

I have tried changing the Content-Type in the $powerBiBodyTemplate but no change.

Any thoughts?

Thanks,

**Comment by maikvandergaag** [comment]
@ssorokoski: Just to be certain if the upload functionality works correctly did you try it with a powerbi report with no data in it?

**Comment by ssorokoski** [comment]
Thanks for the response, yes I did try it with a blank report as well. Same error.

**Comment by maikvandergaag** [comment]
Then there should be something wrong with the configuration of the task or the reports you are making does it work when you upload them manually?

**Comment by maikvandergaag** [comment]
And otherwise send the log file with the variable system.debug true to me to investigate

**Comment by ssorokoski** [comment]
Thanks, I am just running it locally from my machine and I receive this error. Also I sent you an email with the logs.

Thanks,

**Comment by ssorokoski** [comment]
So after allot of random testing and guessing I was able to track down the issue, however I don't fully understand it...... I will give some more details in case someone else is struggling with the same issue. 

So I downloaded the repo and was creating a simple PowerShell script to test the various functions, now I was able to successfully execute the Connect-PowerBIServiceAccount and Get-PowerBIWorkspace commands and both executed fine. However whenever trying to publish a file I would always get the error: 

{"error":{"code":"MultiPartMimeStreamFormatException","pbi.error":{"code":"MultiPartMimeStreamFormatException","parameters":[],"details":[],"exceptionCulprit":1}}}

Also when testing this extension from the pipeline in DevOps it uploads a file just fine, so I thought that maybe there was a slight difference between the repo and market place. Since our DevOps agents run on a VM I took a copy of the task files to compare to the repo. Everything was the same, however when running a File * inside the PowerBi directory I did notice:

Repo File: ASCII text
VM Task File: ASCII text, with CRLF line terminators

So the difference is the UNIX vs Windows files. So I just replaced my powerbi.psm1 file with the one from the VM and I was able to successfully publish a file. I still don't understand why it would cause the above error though.

**Comment by maikvandergaag** [comment]
Oké, so you are running a custom build build agent, what kind of build agent do you have?

**Comment by ssorokoski** [comment]
Just a Windows VM, with VS 2019 and running Agent version 2.173.0

**Comment by maikvandergaag** [comment]
Will try to setup a build agent this weekend to check what is happening

Groetjes,

Maik van der Gaag
________________________________
Van: ssorokoski <notifications@github.com>
Verzonden: Thursday, October 22, 2020 8:50:54 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] "MultiPartMimeStreamFormatException","pbi.error" (#230)


Just a Windows VM, with VS 2019 and running Agent version 2.173.0

**Comment by maikvandergaag** [comment]
Issue should be fixed
