### ISSUE TITLE
Dataset Refresh refreshing more than the single dataset defined.

### ISSUE THREAD

**Issue by awilbourn** [maikvandergaag/msft-extensions#231]
using 5.* notice that when the refresh is executed it is kicking off more than one dataset even though the checkbox to update all is not checked. 

![image](https://user-images.githubusercontent.com/11730606/97001360-41a12900-1506-11eb-9305-9cdef70c3eec.png)

**Comment by maikvandergaag** [comment]
Issue should be fixed. When not the case please add : System.debug with value true to your pipeline. and send the log

**Comment by awilbourn** [comment]
I scrapped your task and just using powershell myself as I did not know how long it would take to resolve. 


On Dec 9, 2020, at 10:34 AM, Maik van der Gaag <notifications@github.com> wrote:

﻿
Issue should be fixed. When not the case please add : System.debug with value true to your pipeline. and send the log
