### ISSUE TITLE
VersionCounter: support linux build agents

### ISSUE THREAD

**Issue by bjornbouetsmith** [maikvandergaag/msft-extensions#232]
Hi,

I have been using your extension for a while on my personal TFS server - and its working great.
I am now in the process of building some .NET core code that will run on a linux server, so I decided to install a tfs build agent on a linux machine, so I could ensure that tests etc run in the correct environment.

But when I queue a build the extension fails with:

The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

I have installed powershell on the linux machine - so is it possible to update the extension so it does not use windows specific powershell like the error message states?

**Comment by bjornbouetsmith** [comment]
I just looked at the powershell folder for the extension - and my guess is that the problem is that you have a couple of dll's. But I am just guessing.

**Comment by bjornbouetsmith** [comment]
@maikvandergaag Did you close this because you have fixed the issue, or just because you dont care and do not want to support linux build agents?

**Comment by maikvandergaag** [comment]
There is another one open for Linux support. When I have the time I will try to pick it up
