### ISSUE TITLE
File not saving to variable despite being properly read. 

### ISSUE THREAD

**Issue by xiphoss1** [maikvandergaag/msft-extensions#233]
I tried to get the proper the result of the "File Content to Output Variable" extension, but no luck so far. I am inputing a file that only has the app version in it. When i execute task, the file content is properly read, but variable isn't being updated. I have also included screenshots underneath to provide info about the task, variable and the output. Can you help me in understanding what i did wrong, or is this issue with the extension itself? 

![1issue](https://user-images.githubusercontent.com/46416972/97283493-36b90200-1840-11eb-8d37-24fd6f62052e.png)

![2issue](https://user-images.githubusercontent.com/46416972/97282135-96aea900-183e-11eb-9fd5-4ee874c2abf2.png)

![3issue](https://user-images.githubusercontent.com/46416972/97282147-97dfd600-183e-11eb-8161-108b32247545.png)

**Comment by maikvandergaag** [comment]
Its sets the variable that you can use during the execution time of the stage. It does not set the variable in the pipeline.
