### ISSUE TITLE
Can't Publish the Pbix file to service with The remote server returned an error: (400) Bad Request error

### ISSUE THREAD

**Issue by suresheeraveni-2006** [maikvandergaag/msft-extensions#234]
We have used Power BI Actions for CICD job to publish Pbix file. But failing with the below errors:
Error Messages:
The remote server returned an error: (400) Bad Request.

Failed to get ADAL token: Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Federated service at https://federation.gsk.com/idp/sts.wst?TokenProcessorId=pfusernametp returned error: ID3242

Thanks & Regards,
Suresh Eeraveni

**Comment by maikvandergaag** [comment]
Please update to the correct version
