### ISSUE TITLE
Publish-PowerBIFile fails if only dataset exists and no report

### ISSUE THREAD

**Issue by thoesk** [maikvandergaag/msft-extensions#237]
Function Publish-PowerBIFile checks for existing report with the same name. But the upload fails if the report is missing but a dataset with the same name exits. 

Can you add check for existing dataset also and delete/rename that dataset before uploading?

**Comment by maikvandergaag** [comment]
@thoesk: off course never had that situation. I have added it as a feature request.

**Comment by maikvandergaag** [comment]
We have an additional feuture in Beta now. will be tracked at #244
