### ISSUE TITLE
Error when updating parameters 

### ISSUE THREAD

**Issue by okarabulut** [maikvandergaag/msft-extensions#239]
I get the following error for the "Update parameters" action. The json object is correctly formatted.  Am I missing something?

`##[error]Dataset parameter at position 1 is invalid in a5d0ac4e-39c6-4a5a-9c44-1263883a4d36. Reason: ActionNotSupported`

Update parameter json:
```

[
    {
      "name": "Snowflake Server",
      "newValue": "xxx"
    },
    {
      "name": "Snowflake Warehouse",
      "newValue": "xxx"
    },
{
      "name": "Snowflake Database",
      "newValue": "xxx"
    },
{
      "name": "User Organization API",
      "newValue": "https://xxx"
    }
]
```

**Comment by maikvandergaag** [comment]
could you place a system.debug with the value true in the pipeline variables

**Comment by shimon893** [comment]
Had same issue, that is problem in report configuration:
![image](https://user-images.githubusercontent.com/16742699/102146764-dcb0e200-3e69-11eb-876c-1e88e078f940.png)
https://community.powerbi.com/t5/Developer/Set-Parameters-API-returning-error-Dataset-Parameters-list-is/td-p/396534
Also parameter as well as dataset must meet following requirements (restrictions of Update Dataset API):
![image](https://user-images.githubusercontent.com/16742699/102192729-72289200-3ebb-11eb-806e-a1e3f52c3913.png)
