### ISSUE TITLE
Pass Group ID for Workspace

### ISSUE THREAD

**Issue by jknix** [maikvandergaag/msft-extensions#24]
Certain workspaces (particularly those with spaces in their names) seem to have issues. This could be avoided if there were a way to specify the group/workspace ID instead of the group name in the actions settings. Thoughts?

**Comment by jknix** [comment]
I discovered an additional possible bug while looking into this. It looks like the check for conflicts on publish only reviews reports. This can cause problems in situations where one would want to publish an updated dataset for "mydata.pbix", and there is no report in the workspace for "mydata.pbix". Because there is no report, the process assumes there's no conflict and no overwrite. Once it attempts to publish a dataset, it seems to encounter a conflict it did not expect and fail.

**Comment by alim92** [comment]
I can also see this problem, I tried using groupId instead and it worked.

**Comment by maikvandergaag** [comment]
Hi @jknix,

Do these issues still appear? At the moment I'm working on a updated version with some large changes. Are you able to check when the release is done?
