### ISSUE TITLE
Deploy fails when report has been deleted , but the dataset is still in the workspace

### ISSUE THREAD

**Issue by ssisjoost** [maikvandergaag/msft-extensions#244]
When you have a pbix file with only a dataset and no reports (the dataset is used in other reports) we delete the 'dummy' report. Now the next deploy will fail because it only checks if there is a report available. It ignores the existing dataset.

**Comment by maikvandergaag** [comment]
Hi Joost, will look into this issue. As i'm not a PowerBI export could you assist in some way?

**Comment by ssisjoost** [comment]
> Hi Joost, will look into this issue. As i'm not a PowerBI export could you assist in some way?

**Yes no problem (I will send you an email). To replicate this:**
1) publish a random report
2) delete the report but leave the dataset
3) publish the report again (with Power BI Actions)

**Possible cause:**
It checks whether it can find the report. If it does $nameConflict becomes "Overwrite" else it becomes "Abort". Now it tries to deploy the report (not existing in workspace) and dataset (still in workspace) with -Conflict set to "Abort"

**Possible solution:**
Also check whether it can find the dataset with Get Datasets In Group https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/getdatasetsingroup

**Comment by maikvandergaag** [comment]
Thanks Joost for the additional information. If I understand your process correctly you want to overwrite the dataset without the report being in PowerBI. Will see what I can do I think I will have some time tomorrow

**Comment by ssisjoost** [comment]
We have an additional PowerShell activity deleting the 'dummy' reports after the deployment step. We don't want the dummy reports 'polluting' the workspace. So one dataset can be used by multiple reports. The dataset and reports can be developed by different people. 

The deployment process will always deploy both the report and dataset. It is not necessary to do the deletes within the deployment step. It's just to hard to find a way to find reports that are 'dummy' reports. Some people will use a naming conventions for this. The restapi doesn't have a method to check whether a report is empty.

**Comment by ssisjoost** [comment]
Also see issue #237

**Comment by AmalJacob1** [comment]
Even i face the same issue.
How to handle this?

**Comment by maikvandergaag** [comment]
Build a solution into the extension and have it available in a beta version. Would you be open to test?

**Comment by ssisjoost** [comment]
Yes, let me know how we can add this new beta version to our devops project...

**Comment by maikvandergaag** [comment]
in production
