### ISSUE TITLE
Suggestion: Delete reports/datasets from the workspace that are not in the repository

### ISSUE THREAD

**Issue by ssisjoost** [maikvandergaag/msft-extensions#245]
Not an issue, but a suggestion for an additional action:
To keep the workspace clean, we have a PowerShell step that compares the workspace reports and datasets with the PBIX files within the repository. If it is in the workspace, but not in the repos then we will delete both report and dataset from the workspace. Otherwise a report or dataset will never disappear because DevOps is often the only way to manage the workspace content.

**Comment by maikvandergaag** [comment]
Hi Joost, if you could share the code I can maybe incorporate it as an additional action in the extension when I have time.

**Comment by Joost-van-Rossum** [comment]
sampe code is in your mailbox

**Comment by maikvandergaag** [comment]
I have added an additional action to remove reports. It is currently in beta, would you mind testing it?

**Comment by ssisjoost** [comment]
No problem, I'm curious about what you have created. Let me know how to test it

**Comment by maikvandergaag** [comment]
If you share your organization url with me I can make it accessible.

**Comment by ssisjoost** [comment]
> If you share your organization url with me I can make it accessible.

see your email

**Comment by AmalJacob1** [comment]
@ssisjoost , @maikvandergaag 
But there is a minor drawback with this approach, once you delete the report of the dataset, then you cant download the .pbix file from power bi service, but then again if you are using version control then no big deal, just pointing out an observation from our testing.

**Comment by maikvandergaag** [comment]
Its moved to production

**Comment by vinayprakash893** [comment]
Can you please share the pipeline to achieve this

currently im using below but, its difficult to send all the deleted name, it should find form the repo 

- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
                displayName: 'Power BI Action: DeleteReport'
                condition: eq(variables['Demo_deleted'], True)
                inputs:
                  PowerBIServiceEndpoint: 'powerbi-actions'
                  Action: DeleteReport
                  WorkspaceName: 'Demo-workspace'
                  ReportName: 'Demofile-1'

**Comment by maikvandergaag** [comment]
What would you like to achieve deleting all the reports? Then you would have to write a powershell script to retrieve all reports save that in a variable and use that for the deleting.

**Comment by vinayprakash893** [comment]
In repo, im deleting the few files 
eg: out of 4 pbix files, i have deleted 2 files in repo , so those two should be removed from PowerBI workspace as well. 

im using the below script to get the diff which files got deleted
Write-Host "Source file '$sourceFile' does not exist. Marked for deletion..."
                    $destsubfolder = Split-Path $sourceFile
                    $deletedFolderPath = Join-Path $deletedfolder $destsubfolder
                    $dummyFileName = Split-Path $sourceFile -Leaf
                    $dummyFilePath = Join-Path $deletedFolderPath $dummyFileName
                    if (-not (Test-Path -Path $deletedFolderPath)) {
                        $null = New-Item -ItemType Directory -Path $deletedFolderPath
                    }
                    $null = New-Item -ItemType File -Path $dummyFilePath
                    }
                    
  
  but if i want to send these in the azure devops pipline, i cannot hardcode thevalues in the repot names, how do i pass dynamically with array or loop..?
  
  
  task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
    displayName: 'Power BI Action: DeleteReport'
    condition: eq(variables['Demo_deleted'], True)
    inputs:
    PowerBIServiceEndpoint: 'powerbi-actions'
    Action: DeleteReport
    WorkspaceName: 'Demo-workspace'
    ReportName: 'Demofile-1'

**Comment by vinayprakash893** [comment]
What was the solution provided to "[ssisjoost]" to delete reports from the powerBi workspace that are not in repository..?
