### ISSUE TITLE
Update gateway doesnt seem to work with SPN authentication, Any suggestions?

### ISSUE THREAD

**Issue by AmalJacob1** [maikvandergaag/msft-extensions#246]
Using Power Bi actions and its really helpful, we have a onprems oracle source, so tried to update the gateway using Power BI Actions using SPN, but it doesnt seem to work

**Comment by maikvandergaag** [comment]
Changing a gateway with an isn't supported at this time. So you would need to use a user.

**Comment by AmalJacob1** [comment]
ohh okay.
Our account uses Multi Factor authentication. So is there any alternative?

**Comment by maikvandergaag** [comment]
Yes making a specific service account without MFA
