### ISSUE TITLE
Conenction string for direct query is using old API

### ISSUE THREAD

**Issue by shimon893** [maikvandergaag/msft-extensions#247]
"Note: This API is deprecated and no longer supported"
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/setalldatasetconnectionsingroup

Maybe should be use same as: updatedatasourcesingroup
and support to do it with Gateway in same run

```
{
	updateDetails: [
    {
      "datasourceType": "Sql",
      "connectionDetails": {
        "server": "XXX",
        "database": "XXX"
      },
      "datasourceId": "XXX",
      "gatewayId": "XXX"
    }
  ]
}
```

**Comment by maikvandergaag** [comment]
Will look into it as soon as I have time

**Comment by camilosotomontoya** [comment]
+1
