### ISSUE TITLE
Passing variables during release creation

### ISSUE THREAD

**Issue by EugenMayer** [maikvandergaag/msft-extensions#251]
Is there any way to pass a variable during a release creation (the ones that are "settable during release time")

in a form 

```
az pipelines release create --definition-id=24 --variables "foo=bar"
```
This kind of blocks us from using `az pipelines create` - thanks!

**Comment by EugenMayer** [comment]
Just checking the REST api https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-6.0 and variables are able to be provided.

**Comment by maikvandergaag** [comment]
@EugenMayer: This is not supported yet in the extension will mark this as a feature request.

**Comment by matthewacme** [comment]
oh yes please, that would be nice if you added this feature

**Comment by EugenMayer** [comment]
@matthewacme IMHO I can only encourage you to implement the REST api using your own client - that is what we did. I do not expect this ticket to be anyway fast moving, you might wait for a year or years.

We used a Go based client which we wrapped the REST api with - in the end, a lot of things would have been missing anyway. There is a lot that the client really is not doing or offering.

**Comment by maikvandergaag** [comment]
Hi @EugenMayer, sorry I maintain these extensions in my free time. Meaning that I do not have the time of the world to add new functionalities.

You can always contribute by forking the repo and making a pull request.

**Comment by EugenMayer** [comment]
> Hi @EugenMayer, sorry I maintain these extensions in my free time. Meaning that I do not have the time of the world to add new functionalities.
> 
> You can always contribute by forking the repo and making a pull request.

If you have taken the above as an offense, please do not.  I do not expect anything from you and I am not allowed to do so frankly. 

It's totally fine that this feature is not implemented at all or very late - no hard feelings. If I would need it, I would implement it. But we decided to go with our own cli entirely and that is why I never contributed.

**Comment by maikvandergaag** [comment]
this is in production
