### ISSUE TITLE
Datasets - Bind To Gateway In Group

### ISSUE THREAD

**Issue by SevenOS** [maikvandergaag/msft-extensions#254]
To automate the entire DevOps flow, I need the Bind to Gateway In Group [https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/bindtogatewayingroup] functionality to be implemented, precisely to map the dataset gateway.

![image](https://user-images.githubusercontent.com/77367821/105175441-adddf980-5b02-11eb-9023-740705d28e54.png)

Do you have any idea when this functionality will be implemented?

Best Regards!

**Comment by zbroinx** [comment]
Hi @SevenOS ,
You can use the UpdateGateway action. It will work.

The problem is if you have multiple Datasources in a dataset.
