### ISSUE TITLE
Data source is not updated in in pbix after downloading a report from Power BI service.

### ISSUE THREAD

**Issue by debashish10** [maikvandergaag/msft-extensions#255]
Issue: Data source is not updated in in pbix file after downloading a report from Power BI service.

Investigation details:

->User is publishing the Power BI report to a UAT workspace using CI/CD process with Azure DevOps. 

One of the tasks is to update the data source to UAT server from DEV while publishing to workspace.

when the user takes over the dataset they can see the expected the server: UAT in Power BI Service, this works well as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/55327056/105670107-7f975a00-5f06-11eb-8c4d-91a343e72275.png)

If the user downloads the pbix from Power BI service and open in Power BI Desktop, the data source still shows as DEV server.

![image](https://user-images.githubusercontent.com/55327056/105670140-8faf3980-5f06-11eb-9e70-484596c7328b.png)

I did raise a ticket to Microsoft as this seems to be a Power BI Service issue but thety responded back that they don't support this and the above updated data source credentials will never be in the PBIX file (and it's by design).

Just wanted to check if this has anything to do with the Power BI Actions extensions.

**Comment by maikvandergaag** [comment]
No this is default behaviour because the extension only alters things in powerbi.com not on the uploaded files
