### ISSUE TITLE
PBI Publish with Service Principle does not find existing workspace

### ISSUE THREAD

**Issue by BISQLC** [maikvandergaag/msft-extensions#256]
Hi,
Firstly, thanks for the plugin - it's great!

I've set up a service principle for PBI, allowed SPs publish rights in PBI Admin centre, and added the SP as an Admin on an existing workspace.

When the pipeline task to publish a report runs, it never finds the existing workspace which I created. Instead, it creates it itself and deploys the report.

If I delete the report it published and rerun the pipeline, it does find the workspace it created itself, and publishes the report.

Is there a reason for this? I.e. it can only publish to workspaces it creates itself?

Thanks

**Comment by maikvandergaag** [comment]
Hi @BISQLC,

I think this is because the SP creates a V2 kind of workspace. I think the workspace you create are the so called V1 and they are not support for service principals

**Comment by BISQLC** [comment]
Thanks for your prompt reply.
However, the workspace I created is definitely a 'new' workspace, and not a 'classic' workspace.
Any other ideas?

**Comment by maikvandergaag** [comment]
If that is not the case I would need to investigate it further. I have never seen this occur. Will check it
