### ISSUE TITLE
PBI reports are not overwriting the existing reports in workspace

### ISSUE THREAD

**Issue by SivakamiR** [maikvandergaag/msft-extensions#258]
Hi, 

I am deploying my reports using CICD pipelines. Am using Powerbi actions to Publish the report from SIT/UAT/Production. enabled the option"Overwrite Powerbi File" but still the report does not overwrite and creates a new copy in the UAT and Prod WS. attached the screenshot.
![Powerbi actions](https://user-images.githubusercontent.com/77982769/108239775-347b0a80-7185-11eb-9e98-ac038f98e0a8.jpg)

**Comment by maikvandergaag** [comment]
Could you send the log file as well with the debug setting enable.
