### ISSUE TITLE
Update DataSource: Credentials?

### ISSUE THREAD

**Issue by cedersup** [maikvandergaag/msft-extensions#259]
I'm building a CI/CD pipeline to deploy reports to different environments. The data source settings will be different for each environment so the release pipeline will update as it deploys the dataset. I see the action "Update DataSource connection" which will let me change the server and database, but I don't see a way to set credentials to access the data source. How is that supposed to be done?

**Comment by maikvandergaag** [comment]
I think you will then have to work with the parameters. This will give you an option to replace them during the deployment
