### ISSUE TITLE
Refresh dataset is refreshing all 

### ISSUE THREAD

**Issue by zbroinx** [maikvandergaag/msft-extensions#261]
Hi,
I configured the refresh dataset as bellow:
- task: PowerBIActions@5
  displayName: 'Refresh'
  inputs:
    PowerBIServiceEndpoint: 'Webmaster PowerBI'
    Action: 'DataRefresh'
    WorkspaceName: '$(Workspace)'
    DatasetName: '$(Datasetname)'

As you can see, I don't enabled the option to refresh all.
But I notice that refreshes all datasets.
Here's the log:

Starting Power BI Actions extension
### Trying to import the incorporated module for PowerBI
##[warning]The names of some imported commands from the module 'PowerBi' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Trying to refresh Dataset
Getting Power BI Workspace properties; Business
Processing dataset - AlXXXXX

Processing dataset - ChXXXXX

Processing dataset - CoXXXXX

Processing dataset - CuXXXXX

Processing dataset - DiXXXXX

Processing dataset - NoXXXXX

Processing dataset - ObXXXXX

Processing dataset - OrXXXXX

Processing dataset - PaXXXXX

Processing dataset - PaXXXXX

Done processing Power BI Actions
Done running Power BI Actions extension.
Finishing: Refresh

**Comment by maikvandergaag** [comment]
That strange, cloud you re run the extension and set the variable system.debug tot true and send the log?

**Comment by zbroinx** [comment]
Log attached.

Obrigado(a).
Saudações calorosas,
PEDRO RIBEIRO
Tlm.: 912 101 019
Email: pedro_ribeiro@outlook.com

________________________________

**Comment by maikvandergaag** [comment]
Thanks there seems to be something wrong with a check in the extension. Hope to update as soon as possible

**Comment by okarabulut** [comment]
I'm having the same problem with the "Refresh a dataset" action. Even though I configure it to refresh a specific dataset (unchecked the option: Update all datasets in workspace the dataset name will be ignored), all datasets in the workspaces are refreshed. I hope this issue will be addressed soon. With dozens of datasets in a workspace, this bug has a significant impact on our data warehouse compute costs.

**Comment by zbroinx** [comment]
Hi @okarabulut 

In the mean time, I found a temporary solution.
Check if it helps.

`param(
[Parameter(Mandatory = $true)]
[ValidateNotNullOrEmpty()]
[string] $workspaceID,

[Parameter(Mandatory = $true)]
[ValidateNotNullOrEmpty()]
[string] $datasetID,

[Parameter(Mandatory = $true)]
[ValidateNotNullOrEmpty()]
[string] $BuildAgentLogin,

[Parameter(Mandatory = $true)]
[ValidateNotNullOrEmpty()]
[string] $BuildAgentPassword
)

###EXECUTION
Write-Host "### Script Started.";

try
{
### INSTALL MODULES AND LOGIN TO POWER ###
Install-module -Name "MicrosoftPowerBIMgmt.Profile" -AllowClobber -Verbose -SkipPublisherCheck -Force

#1. Authenticate to Power BI with Power BI Service Admin account
$secureBuildAgentPassword = ConvertTo-SecureString $BuildAgentPassword -AsPlainText -Force;
$creds = New-Object PSCredential($BuildAgentLogin,$secureBuildAgentPassword);

#2. Connect to PBI Serice
Connect-PowerBIServiceAccount -Credential $creds | Out-Null
Write-Host "### PBI succesfully Connected." -ForegroundColor Green;

#3. Refresh dataset
Write-Host "### Refresh Dataset." -ForegroundColor Green;
$RefreshDSURL = 'groups/' + $workspaceID + '/datasets/' + $datasetID + '/refreshes'
$Notify = @{"notifyOption"="NoNotification"}
Invoke-PowerBIRestMethod -Url $RefreshDSURL -Method Post -Body $Notify

Disconnect-PowerBIServiceAccount -Verbose

Write-Host "### Script Finished Succesfully." -ForegroundColor Green;
}
catch
{
    Write-Host "### Script Failed." -ForegroundColor Red;
    throw;
}`
