### ISSUE TITLE
BindGateway to dataset with multiple datasources

### ISSUE THREAD

**Issue by zbroinx** [maikvandergaag/msft-extensions#262]
Hi,
I have an dataset that have two datasources. Log bellow.
![image](https://user-images.githubusercontent.com/11558823/109041512-020e6780-76c7-11eb-9758-e1eed14ef310.png)

How can I bind the gateway to the datasource?
If my report has only one datasource in the dataset, the UpdateGateway actions works.

Starting: Update Gateway
==============================================================================
Task         : Power BI Actions
Description  : Release Task Power BI Actions
Version      : 5.3.16
Author       : Maik van der Gaag
Help         : 
==============================================================================
Starting Power BI Actions extension
### Trying to import the incorporated module for PowerBI
##[warning]The names of some imported commands from the module 'PowerBi' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Trying to change the Gateway
Getting Power BI Workspace properties; Business
##[warning]No action taken! Gateway DataSource- '' for Dataset- 'Customers' could not be matched; ensure the gateway and datasource already exists
Done processing Power BI Actions
Done running Power BI Actions extension.
Finishing: Update Gateway

**Comment by zbroinx** [comment]
@maikvandergaag 
Any ideia how I can solve this?

**Comment by dimabutenko** [comment]
Hi @maikvandergaag, @zbroinx. I also have this problem. After my investigations as I understood need only change '-eq' to 'in' in this line: https://github.com/maikvandergaag/msft-extensions/blob/54a807df183fe11ea5133b809db998d26524b560/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1#L76

**Comment by maikvandergaag** [comment]
@dimabutenko you should be able to fork and the do a pull request. If that isn't possible please let me know

**Comment by dimabutenko** [comment]
I created pool request #284 but it has 2 of 5 checks passed.

**Comment by maikvandergaag** [comment]
@dimabutenko: Change looks good checks that fail are other pipelines that seem to have been triggered. Will fix that this week. For now the pull request is committed.
