### ISSUE TITLE
Power BI Premium Workspace does not exist

### ISSUE THREAD

**Issue by radekrezac** [maikvandergaag/msft-extensions#263]
Power Bi Action Publish has issue when publishing to Power BI Premium Workspace. I got error message: Power BI Workspace: xxxx does not exist, even if realy exists.

**Comment by maikvandergaag** [comment]
Check the version of the workspace and the access of the spn.

**Comment by radekrezac** [comment]
Thanks for your answer. Version of the workspace is V2 and as a service connection I use my username/password authentication type.

**Comment by maikvandergaag** [comment]
Ok, does the user has permission on the workspace? Could you besides that set the variable "System.debug" to true and rerun the pipeline and send the logs
