### ISSUE TITLE
Problems with release pipeline to PowerBI

### ISSUE THREAD

**Issue by DavidJFC** [maikvandergaag/msft-extensions#265]
Hi Maik, hope you are doing well.

I´m having problem to deploy the release pipeline into PowerBI workspace.

I have linked a new service connection to an Azure Acitve Directory (Tenant ID, Client ID and Client Client Secret).
However, when I try to run the task "PowerBI Action" I get the below error.

![image](https://user-images.githubusercontent.com/79982318/109809954-d5a39f80-7c20-11eb-88d1-494d4ad9865b.png)

This is a access problem, or there is something I should fix?

**Comment by maikvandergaag** [comment]
I think this is a access problem or a misconfiguration.

Could you share the logs with the system.debug variable set to true

**Comment by DavidJFC** [comment]
Hi Maik,

Attached I send you the logs. Let me know if this is what you want (because this is from the build pipeline)

[logs_4.zip](https://github.com/maikvandergaag/msft-extensions/files/6076741/logs_4.zip)

**Comment by maikvandergaag** [comment]
Hi, it should be the logs from the release pipeline.

**Comment by DavidJFC** [comment]
Hi, 

[ReleaseLogs_8.zip](https://github.com/maikvandergaag/msft-extensions/files/6076950/ReleaseLogs_8.zip)

Here it is the logs. Thanks!

**Comment by maikvandergaag** [comment]
@DavidJFC: Is this a log file with the variable system.debug added? If yes please reconfigure your service connections and make sure the service principal you are using has the correct permissions.

**Comment by DavidJFC** [comment]
Hi Maik,

Yes we have the variable system.debug = true added. We also had reconfigure our service connections but we had the error below

[3_Power BI Action Dataset.pbix.log](https://github.com/maikvandergaag/msft-extensions/files/6083828/3_Power.BI.Action.Dataset.pbix.log)

Please let me know if you need any further information.

**Comment by DavidJFC** [comment]
Note: With this approach we need to have a Premium/Pro PowerBI account?

**Comment by maikvandergaag** [comment]
That depends on how you configure the service connection. A SPN does not need to have a pro license a user did you also try to create a workspace

**Comment by MamoonAshraf** [comment]
i am facing the same issue detailed Release log is attached, system.debug=true
[tasklog_6.log](https://github.com/maikvandergaag/msft-extensions/files/6155790/tasklog_6.log)

**Comment by maikvandergaag** [comment]
@MamoonAshraf your authentication seems incorrect. Please check your configuration.

**Comment by MamoonAshraf** [comment]
> @MamoonAshraf your authentication seems incorrect. Please check your configuration.

@maikvandergaag Thanks for your prompt reply, i have re-checked configurations and found that i provided client certificate id instead of its value, now i have provided value it worked for me Thanks
