### ISSUE TITLE
Support PowerBI Service Connection through Service Principal

### ISSUE THREAD

**Issue by SherinMirza** [maikvandergaag/msft-extensions#268]
@maikvandergaag PowerBI Service Connection is currently below parameters for ServicePrincipal Authentication

TenantID
ClientID
Client Secret

Is it possible to support "Certificate" instead of "Client Secret"?

**Comment by maikvandergaag** [comment]
Yes I think so will add it to the feature requests

**Comment by SherinMirza** [comment]
Thank you, looking forward for this feature

**Comment by maikvandergaag** [comment]
Added the new option to the service connection in a beta version of the extension. If you share your organization name I'm able to share the beta version with you.

**Comment by SherinMirza** [comment]
we will not be able to use beta version in our organization. But can sure test it in our sandbox org

**Comment by maikvandergaag** [comment]
Thanks for sharing your sandbox environment, you can test the extension by installing it via this link: https://marketplace.visualstudio.com/items?itemName=Development-vanderGaag.maikvandergaag-power-bi-actionsDev

**Comment by SherinMirza** [comment]
@maikvandergaag  I am getting  below error

```
 Done processing Power BI Actions
2021-05-05T13:31:17.4233720Z ##[debug]Caught exception from task script.
2021-05-05T13:31:17.4303571Z ##[debug]Error record:
2021-05-05T13:31:17.5981355Z ##[debug]New-PowerBIReport : Operation returned an invalid status code 'BadRequest'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-05-05T13:31:17.6088146Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ht    tpOperationException
2021-05-05T13:31:17.6124724Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'BadRequest',Microsoft.PowerBI.Commands.Report    s.NewPowerBIReport
```

**Comment by joaovictormelo42** [comment]
Hi! The ID of dataset or workspace changed someway? Because i had trouble with this same return some time, and i could fix that verifiyng the DatasetId and WorkspaceId parameter on the PowerBI Service.

**Comment by joaovictormelo42** [comment]
> @maikvandergaag I am getting below error
> This is happening when a **new** PowerBI report is published to the workspace through the PowerBI Actions task.
> If i publish a new version of already existing PowerBI file in the workspace, the task is successful.
> Any idea how to fix this issue?
> 
> ```
>  Done processing Power BI Actions
> 2021-05-05T13:31:17.4233720Z ##[debug]Caught exception from task script.
> 2021-05-05T13:31:17.4303571Z ##[debug]Error record:
> 2021-05-05T13:31:17.5981355Z ##[debug]New-PowerBIReport : Operation returned an invalid status code 'BadRequest'
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2021-05-05T13:31:17.6088146Z ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...ewPowerBIReport:NewPowerBIReport) [New-PowerBIReport], Ht    tpOperationException
> 2021-05-05T13:31:17.6124724Z ##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'BadRequest',Microsoft.PowerBI.Commands.Report    s.NewPowerBIReport
> ```

Hi! The ID of dataset or workspace changed someway? Because i had trouble with this same return some time, and i could fix that verifiyng the DatasetId and WorkspaceId parameter on the PowerBI Service.

**Comment by maikvandergaag** [comment]
is supported in the newest version. If there are problems please create a new issue and attach the full logs.
