### ISSUE TITLE
MS Office Multi-Factor Authentication

### ISSUE THREAD

**Issue by zuzka188** [maikvandergaag/msft-extensions#27]
Hi, 
1) I really like this extension!
2) we have MFA set up for whole company, so I've had to create special user in AD without MFA, which is obviously not the best solution.. Could there be an option for running this task with MFA?

**Comment by zuzka188** [comment]
:-D sorry, of course I meant Power BI Actions

**Comment by denvro** [comment]
I'm also trying to use your extension in an enterprise environment with MFA. They don't allow us to create accounts without MFA. So currently the extension is not working for us. I think creating the possibility to publish with a service principal name is the way forward

**Comment by maikvandergaag** [comment]
Hi Denvro, thank you for your suggestion. As far as I know at the time I was developing the extension it wasn't possible to use a service principal. Mid Oktober I will have more time and will try to update the extension.

**Comment by maikvandergaag** [comment]
Hi Denvro, 

Thanks you for your feature request. At this moment it is not possible to only use a Service Principal to perform actions on PowerBI. 

The only option there is is creating a Service Principal and use delegated permissions for the account. Will close the issue for know. When Service Principals are possible I will try to update the extension.
