### ISSUE TITLE
Rebind Report

### ISSUE THREAD

**Issue by DuckoDeath** [maikvandergaag/msft-extensions#274]
Would be nice to have the ability to change the report dataset at deployment time.

Looks like possible via:
https://docs.microsoft.com/en-us/rest/api/power-bi/reports/rebindreport

**Comment by maikvandergaag** [comment]
@DuckoDeath: I will check this option when I have some time available thanks for pointing out the existing documentation

**Comment by maikvandergaag** [comment]
Added the functionality in a beta release. If you could share your organization I can give you an option to test

**Comment by maikvandergaag** [comment]
is in version 5.4.9
