### ISSUE TITLE
publish dataset from model.bim/xmla script instead of pbix file

### ISSUE THREAD

**Issue by datadu-de** [maikvandergaag/msft-extensions#275]
it would be very nice if we could use model.bim or a xmla script to create/modify a dataset, instead of publishing from pbix file.
we many times build models independently from reports/dashboards in tabular editor and would like to deploy these.

something that can be done with cmdlet invoke-ascmd if i'm not mistaken.

are we missing something? is this already possible?
thanks!

**Comment by maikvandergaag** [comment]
Never seen this option, could you maybe share more info as I'm not a data expert?

**Comment by datadu-de** [comment]
Cheers Maik,

if you want to dig deep into the CI/CD topic for tabular models, Daniel the creator of TabularEditor has some excellent [Blog Posts on this](https://tabulareditor.com/2020/06/20/DevOps5.html)

The short version is: Inside the pbix-file lives a Model.bim - which is the data model that is created in the report (all the tables, measures, data sources, hierarchies, etc - but without the data itself).
In more advanced scenarios (bigger amounts of data, more than one developer, etc) models are developed separately from the reports that are built on top - and then deployed separately.
(Reports are built separately as well in PBI Desktop and have a Liveconnection to such a dataset/model).

Now, you have such a Model.bim (which is JSON) and/or a TSML/XMLA Script (which is also JSON) that can be executed against the XMLA endpoint of the PBI Premium workspace using the Invoke-AsCmd Cmdlet in order to create and/or modify such a dataset - no pbix-file is involved anymore if, say, there's a sprint with only changes to the model and none to the dashboards.

Now, it would be very cool to have a proper "pbi action" for this deployment in the pipeline instead of "handmade" powershell with what feels like clumsy handling of service principal vars, xmla endpoints and errors.

Does this help a bit? Can I clarify any further?

**Comment by maikvandergaag** [comment]
@datadu-de: I'm trying to understand the usecase a little more. But can not really find a usefull and clean way to git this up and running. Do you maybe have more information on this?

**Comment by mattias-de-coninck** [comment]
@datadu-de I added this functionality to the beta build. Would you care to test this out, as I have no access to a premium capacity workspace to do it myself?

An example task can be seen below.

![image](https://user-images.githubusercontent.com/59693063/141832463-bf6d9ff0-c6a9-4cf9-9761-1fe78ca09968.png)
