### ISSUE TITLE
Take over dataset --> no credentials

### ISSUE THREAD

**Issue by Stefkus** [maikvandergaag/msft-extensions#276]
Hi,

When I publish a dataset/report with service principal and take over ownership the credentials of the datasoure are gone. I can still update the datasource but the refresh of the report fails.

I get error:
It looks like scheduled refresh failed because at least one data source is missing credentials. To start the refresh again, go to this dataset's settings page and enter credentials for all data sources.

I use from the Power BI Actions extension the following Actions:
1) Publish
2) Take Ownership
3) UpdateDataSource
4) DataRefresh

Hope you can help me.

Regards Stefan

**Comment by maikvandergaag** [comment]
Hi @Stefkus some credential types need to be filled in in the portal

**Comment by Stefkus** [comment]
Hi Maik,

The problem is that you can't change the credentials in the portal when a service principal has ownership of a dataset. We use Azure SQL database.

regards Stefan




________________________________
Van: Maik van der Gaag ***@***.***>
Verzonden: woensdag 14 april 2021 14:56
Aan: maikvandergaag/msft-extensions ***@***.***>
CC: Stefkus ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [maikvandergaag/msft-extensions] Take over dataset --> no credentials (#276)


Hi @Stefkus<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStefkus&data=04%7C01%7C%7C4d9de38f29d245b2073308d8ff44b8b3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637540017913891791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UaZ664j%2F0aE9ZtlD8W3WUwX5sXHJwDqorKrfRvxMEzs%3D&reserved=0> some credential types need to be filled in in the portal

**Comment by maikvandergaag** [comment]
When that is the problem you should configure the connection in another way or change the step of taking ownership.

Met vriendelijke groet,

Maik van der Gaag

**Comment by Stefkus** [comment]
Thanks!

**Comment by zuheirashraf17** [comment]
hi @Stefkus do you have a solution for this? I'm having the same issue with yours.

Step that we do is:
1 - Publish Report
2 - Take Ownership
3 - Update Datasource Connection -> Change from Dev to Prod, this require ownership of the dataset
4 - Update Parameters -> Change top 1000 rows from Dev to Prod, again I believe this require ownership
5 - Refresh Dataset -> to refresh after parameters updated. Which then doesn't work because its already lose the credentials.

Any suggestion / idea or input is greatly appreciated.

**Comment by maikvandergaag** [comment]
Hi @zuheirashraf17, I don't think there is another option at this moment. If there is please let me know and I will see if I can add it to the extension.

**Comment by BartWysocki** [comment]
A little late to the conversation in here, did you managed to get any solution here? I am having the same problem
