### ISSUE TITLE
Delete Report feature isn't actually deleting from the Power BI Workspace.

### ISSUE THREAD

**Issue by IagoFranco** [maikvandergaag/msft-extensions#277]
Hi, first of all thank you so much for build and provide the source code for this amazing product!

My experience using "Delete Report" feature is that I'm getting a success message from the Power BI Action component execution, but when I'm looking into the Workspace, the report still there.

My SPN has Admin access on the workspace and also all the permissions needed.

Any ideas on why this is occuring?
Thank you very much!

**Comment by maikvandergaag** [comment]
Did you try running the extension with the system.debug variable set to true?

**Comment by IagoFranco** [comment]
Hi Maik,
Yes I did.
Looking into logs there's nothing showing up that might be the reason for that.

But, I am confusin about one log line: The 'Delete-PowerBIReport' command in the PowerBi' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Remove".

I don't know if this is related, any ideas?

**Comment by maikvandergaag** [comment]
Could you share the logs? Is the report maybe used by another dashboard

**Comment by IagoFranco** [comment]
Hi @maikvandergaag, here it is :D

[DeleteReport-logs.txt](https://github.com/maikvandergaag/msft-extensions/files/6335387/DeleteReport-logs.txt)

**Comment by maikvandergaag** [comment]
@IagoFranco : Thanks, from the log I can see that there is a small bug in the code. I fixed that part of the code and this is build and deployed as we speak. in about 30 min a new version should be available for you to test

**Comment by IagoFranco** [comment]
Hi @maikvandergaag thank you very much!
Now I am facing a different error message:
2021-04-19T17:42:47.5965184Z ##[error]Cannot process argument transformation on parameter 'Create'. Cannot convert value "" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.

**Comment by maikvandergaag** [comment]
Strange that bug has seem to be snucked in during some big changes. It is building a new version as we speak

**Comment by IagoFranco** [comment]
Hi @maikvandergaag, it worked in the new version 5.3.21
Thank you very much for your quick support, I really appreciate that!
