### ISSUE TITLE
PAT expiration issue

### ISSUE THREAD

**Issue by manish-jain-alept** [maikvandergaag/msft-extensions#278]
Currently it uses Azure Service Connection(Azure DevOps API) which requires PAT. But we don't have never expiring PAT option in Azure DevOps till now, so the person who created that PAT leave organization before PAT expiration, we won't get notified via email and in such a way many of things will stop working without any intimation.
Though this extension doesn't use Azure Service Connection(Azure Resource Manager) we don't have option to use Service Principal.
Can we have any alternative here?

**Comment by maikvandergaag** [comment]
You can always generate a pat yourself and update the service connection

**Comment by manish-jain-alept** [comment]
> You can always generate a pat yourself and update the service connection

Thanks for your quick response, but actually the limitation of PAT(expired some time in future) is stopping us to use that. We need to build a process where, it is completely non-dependent and nobody required to take a look into that process anytime further in future.
Do we have something where we can use Service Principal(or any alternate) instead of PAT, so we can overcome from regenerate PAT issue?
