### ISSUE TITLE
Create a New Workspace feature only creates on shared capacity

### ISSUE THREAD

**Issue by IagoFranco** [maikvandergaag/msft-extensions#281]
Hi @maikvandergaag,

We are using Power BI Action's "Create a new Workspace" feature, and actually are creating it, but only on Shared Capacity.
Does this feature supports also creation on Dedicated Capacities (Premium)?

Thank you very much!

**Comment by maikvandergaag** [comment]
No sure, what could you explain me more about this requirement? I'm not a PowerBI specialist

**Comment by IagoFranco** [comment]
Sure, @maikvandergaag 
In Power BI has two types of capacities, that is related to the resources usage, basically.
Shared Capacity: All Microsoft clients have concurrency for the same resources (memory, storage, processing)
Dedicated Capacity, also know as Premium: Only my company will use this resources, the resources are dedicated to that specific company.

I can create a new Workspace in a Shared Capacity or in a Dedicated Capacity.
If I create a workspace in Dedicated Capacity, and publish reports on it, I will have some advantages, one of them is for the users that will only consume the reports as readers, they doesn't need to have a PRO License. On the other hand, if we use a Shared Capacity, the users that will only see, as reader, they will need a PRO license.

Today, if I use Power BI Action feature "create a new workspace", it will create a workspace in a Shared Capacity.

I don't know if this is the information that you are looking for, I hope this helps :)

**Comment by maikvandergaag** [comment]
Oké this helps already a little. Do you connect to the same uri?

**Comment by IagoFranco** [comment]
Yes, through the same URI.
Those workspaces that has a diamond symbol are placed in a Premium capacity.
![image](https://user-images.githubusercontent.com/68740646/116449985-26a2cf00-a831-11eb-8cc8-0114eb6af397.png)

**Comment by maikvandergaag** [comment]
Ok did not know that was possible seems pretty cool. Will investigate if I can get that done via the api

**Comment by IagoFranco** [comment]
@maikvandergaag This is awesome!

I think it isn't possible to create a new workspace direct in a Premium Capacity,
But what it is possible, is to run this feature as is, create a workspace, and than move this workspace to some Premium capacity.

Please, see:
https://docs.microsoft.com/en-us/rest/api/power-bi/capacities/groups_assigntocapacity

![image](https://user-images.githubusercontent.com/68740646/116452542-37087900-a834-11eb-89a8-4dd80e8d7319.png)

Through API, all we can do is passing the workspace id, that was created before, and also passing the capacity id.

I really appreciate if you take some time to evaluate this possibility, I think this can contribute so much, many companies could have more than one Premium Capacity, and this may helps :D

**Comment by maikvandergaag** [comment]
Ahh great I could add that as a new action into the extension. Will send you a message when I have it in beta

**Comment by maikvandergaag** [comment]
Created a beta for this functionalty. If you are able to share your devops organization I can give you access to it.

**Comment by IagoFranco** [comment]
Hey @maikvandergaag, I really appreciate that, but here in my company we are not allowed to share the DevOps organization due security team recomendations, I'm very sorry! :(
Does have another way that we can test, maybe realese a new version or something like that?

 Thank you very much!

**Comment by IagoFranco** [comment]
Hi @maikvandergaag 
You were able to evaluate another option for us to test, maybe realese a new version or something like that?

Thank you very much!

**Comment by maikvandergaag** [comment]
@IagoFranco Sorry for the late response. You do not have to share the organization with me I only require the name of the organization so that I can allow the beta installation to be installed there.

Sorry I do not have another option to test.

**Comment by jkeeley583** [comment]
@maikvandergaag - I'm also interested in this capability, would be happy to test out the beta - organization = jkeeley0105

**Comment by maikvandergaag** [comment]
functionality is finished and published
