### ISSUE TITLE
Requirements for self hosted agents?

### ISSUE THREAD

**Issue by Carsten3000** [maikvandergaag/msft-extensions#282]
I can deploy a Power BI Report via Power BI Actions with a Microsoft hosted agent. Using a self hosted agent i get this error (debug is on )

##[debug]Remove report           : 
Getting Power BI Workspace properties; Datasets TMS
##[debug]10:08:52 - Get-PowerBIWorkspace begin processing with ParameterSet Name.
##[debug]10:08:52 - Cmdlet version: 1.0.896.0
##[debug]Error record:
##[debug]Get-PowerBIWorkspace : An error occurred while sending the request.
##[debug]At C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1:658 char:22
##[debug]+ ...       $workspace = Get-PowerBIWorkspace -Name $WorkspaceName -Verbose
##[debug]+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpRequestException
##[debug]    + FullyQualifiedErrorId : An error occurred while sending the request.,Microsoft.PowerBI.Commands.Workspaces.GetPo    werBIWorkspace
##[debug] 
##[debug]Script stack trace:
##[debug]at Get-PowerBIGroupPath, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1: line 658
##[debug]at Publish-PowerBIFile, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1: line 748
##[debug]at <ScriptBlock><Process>, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\run.ps1: line 79
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
##[debug]   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
##[debug]   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
##[debug]   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
##[debug]   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
##[debug]   at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
##[error]An error occurred while sending the request.
##[debug]Processed: ##vso[task.logissue type=error]An error occurred while sending the request.
##[debug]10:08:53 - Get-PowerBIWorkspace end processing.
##[debug]10:08:53 - Get-PowerBIWorkspace begin processing with ParameterSet Name.
##[debug]10:08:53 - Cmdlet version: 1.0.896.0
Done processing Power BI Actions
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Get-PowerBIWorkspace : An error occurred while sending the request.
##[debug]At C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1:586 char:18
##[debug]+     $workspace = Get-PowerBIWorkspace -Name $WorkspaceName
##[debug]+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpRequestException
##[debug]    + FullyQualifiedErrorId : An error occurred while sending the request.,Microsoft.PowerBI.Commands.Workspaces.GetPo    werBIWorkspace
##[debug] 
##[debug]Script stack trace:
##[debug]at New-PowerBIWorkSpace, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1: line 586
##[debug]at Get-PowerBIGroupPath, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1: line 661
##[debug]at Publish-PowerBIFile, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\ps_modules\PowerBi\PowerBi.psm1: line 748
##[debug]at <ScriptBlock><Process>, C:\agent\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.21\run.ps1: line 79
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
##[debug]   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
##[debug]   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
##[debug]   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
##[debug]   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Api.V2.Groups.<GetGroupsWithHttpMessagesAsync>d__5.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.<GetGroupsAsync>d__1.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroups(IGroups operations, String filter, Nullable`1 top, Nullable`1 skip)
##[debug]   at Microsoft.PowerBI.Common.Api.Workspaces.WorkspacesClient.GetWorkspaces(String filter, Nullable`1 top, Nullable`1 skip)
##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.GetWorkspaces()
##[debug]   at Microsoft.PowerBI.Commands.Workspaces.GetPowerBIWorkspace.ExecuteCmdlet()
##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
##[error]An error occurred while sending the request.
##[debug]Processed: ##vso[task.logissue type=error]An error occurred while sending the request.
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: Power BI Action: Publish

Are there any requirements to the agent server i am missing? I could not find any differences between the logs of Microsoft hosted and the self hosted agent.

**Comment by Carsten3000** [comment]
Our self hosted agent is running Windows Server 2016

**Comment by maikvandergaag** [comment]
Hi @Carsten3000,

How is the agent managed. It looks like a connectivity issue from the agent to Power BI

**Comment by maikvandergaag** [comment]
Were you able to resolve this issue?

**Comment by Carsten3000** [comment]
I was. MS disabled TLS 1.0 and neither TLS 1.1 nor 1.2 were enabled in Powershell on the Server. Took my by suprise.


This did the trick in Powershell:
`[Net.ServicePointManager]::SecurityProtocol` = [Net.SecurityProtocolType]::Tls12
