### ISSUE TITLE
Update Azure Resource Group Tagging to use Az module

### ISSUE THREAD

**Issue by robe070** [maikvandergaag/msft-extensions#286]
The Azure Resource Group Tagging script is using the old Azure RM module. It is now generating 4 warnings about the use of Azure RM module. This is muddying the Azure DevOps pipeline reports.

Please update it ASAP to use the Az module

**Comment by maikvandergaag** [comment]
Will schedule an update.

**Comment by robe070** [comment]
Surely this Issue should not be closed until the issue is resolved? Then I can confirm that it is resolved. With it closed I'll never know that you've addressed it.
