### ISSUE TITLE
Unable to update DataSource connection, using Dynamics 365 / Dataverse

### ISSUE THREAD

**Issue by pma04snb** [maikvandergaag/msft-extensions#288]
Hi,

We are trying to develop a standard set of Power BI Reports, created in our development Dynamics 365 environments, so we can release these to all of our customers and the data source of each report then represents the data in the customers environment so that the data is correct.

We have managed to publish the reports to another environment, but of course the data still represents the data from the development environment that the report was created against.

We have tried using the "Update DataSource connection" action, but with no success and unsure what the parameters should exactly be. The error message we receive currently is "Dataset doesn't contain a datasource that matches selector #1"

Is updating a Dataverse connection with Power Bi Actions even possible? Should we create our own Powershell to achieve this? If so, any idea on what the parameters should exactly be?

Assistance with this would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/85345404/120791786-88d7a980-c52c-11eb-8ae9-b3b05fbc1419.png)

![image](https://user-images.githubusercontent.com/85345404/120791568-46ae6800-c52c-11eb-8594-b06a93668f86.png)

**Comment by bilal684** [comment]
I have the same issue 👍 Looking forward an answer so I can resolve this as well.

**Comment by maikvandergaag** [comment]
Best option to investigate this option is to find the correct selector, because the selection is done based on the old information supplied. Youi could use the API's to retrieve it. 

I will try to add a functionality to display it in the logs.
