### ISSUE TITLE
Issue when updating parameters

### ISSUE THREAD

**Issue by pjserlet** [maikvandergaag/msft-extensions#289]
Hi Maik!

My issue when updating the parameters of my dataset:

**Below JSON does not update the desired parameter.** 
 [     {       "name": "XXX",      "newValue": "\\\\XXX\\XXX\\XXX\\XXX.xlsx"     }   ] 
The message I received: Bad request

**Comment by pjserlet** [comment]
Resolved --> [ { 'name': 'XXX', 'newValue': '\\\\\\\\XXX\\\\XXX\\\\XXX\\\\XXX.xlsx' } ]

**Comment by maikvandergaag** [comment]
@pjserlet. Thanks for letting this know.
