### ISSUE TITLE
PowerBI action - update the workspace, doesn't update the app.

### ISSUE THREAD

**Issue by Farzad-Jalali** [maikvandergaag/msft-extensions#29]
Dear Sir/Madam,

I love your extension, 
I can successfully upload the report into the workspace, but I noticed that in order to publish it for users, I need to do the following steps:

1. login into website
2. go to the workspace 
3. click on the "update app" button ( the yellow button in the top right of the below screenshot)

**Question/Issue:**
` I wonder if I'm doing something wrong such as an extra permission that I need to grant, or it's a bug in your extension?`

![image](https://user-images.githubusercontent.com/3695669/43892813-e8ea2486-9bc4-11e8-8f65-79e131547a6c.png)

**Comment by maikvandergaag** [comment]
Could you retest it?
