### ISSUE TITLE
What does "Update Gateway" is for?

### ISSUE THREAD

**Issue by IagoFranco** [maikvandergaag/msft-extensions#290]
Hi @maikvandergaag how are you?
There's is some documentation for us to see what this feature is about? I'm testing every feature, but the "Update Gateway" functionality is not clear for me, what I expect from it?

Thank you very much!

**Comment by maikvandergaag** [comment]
Hi @IagoFranco: It updates the dataset connection with new gateway details.

**Comment by IagoFranco** [comment]
Ohh, got it! Thank you very much!
