### ISSUE TITLE
Failed to populate environments in settings

### ISSUE THREAD

**Issue by Ragunath452** [maikvandergaag/msft-extensions#291]
We are trying to use this Power BI Action to perform Power BI CI/CD from Azure DevOps Server ( TFS) 2019. we created service principal and trying to create, delete and add the users to workspace. But we are getting the below error 
**Failed to populate environments in settings**

we verified the connection and all are looking good.

**Comment by maikvandergaag** [comment]
Could you do a rerun with the variable system.debug set to true

**Comment by Ragunath452** [comment]
may i know where can i set System.debug set to true? Sorry

**Comment by Ragunath452** [comment]
I tried to set System.Debug  as true and re-run. Still we are getting the error.

**Comment by Ragunath452** [comment]
Could you please help me on this ?

**Comment by maikvandergaag** [comment]
Could you share how you have setup the service connection?

**Comment by Ragunath452** [comment]
We used Service Principal. Provided Tenant Id,  Client ID and Client Sec ( Azure AD Registered App ).
![Capture](https://user-images.githubusercontent.com/86080785/122566803-93567080-d00d-11eb-86d8-97ab0e9efe8f.PNG)

**Comment by Ragunath452** [comment]
We used Service Principal. Provided Tenant Id, Client ID and Client Sec ( Azure AD Registered App ).
![Capture](https://user-images.githubusercontent.com/86080785/122567146-fb0cbb80-d00d-11eb-9e33-2feab1cbeaa1.PNG)

**Comment by maikvandergaag** [comment]
That configuration seems to be oke, could you maybe also share the task config.

And do all tasks have the same error?

**Comment by Ragunath452** [comment]
Yes, Same error for all tasks

**Comment by Ragunath452** [comment]
@maikvandergaag  - Could you please look into this and assist me?

**Comment by maikvandergaag** [comment]
Are you able to perform the scripts from the sever it self as you are using a private hosted environment

**Comment by Ragunath452** [comment]
Let me try that. You mean run the poweshell to see if we are able to connect power bi workspace or not right ?

**Comment by maikvandergaag** [comment]
Yes you could extract some code out of this repo to test.

**Comment by Ragunath452** [comment]
Do you think below code is fine to run this ?

[CmdletBinding()]param()Trace-VstsEnteringInvocation $MyInvocation
#import powerbi moduleImport-Module $PSScriptRoot\ps_modules\PowerBi#import ADAL moduleImport-Module $PSScriptRoot\ps_modules\ADAL.PS
try {    # Get VSTS input values		$authenticationType = Get-VstsInput -Name "AuthenticationType" -Require

	if($authenticationType -eq "User"){		$connectedServiceName = Get-VstsInput -Name ConnectedServiceName	}else{		$connectedServiceName = Get-VstsInput -Name connectedServiceNameSP	}
		$serviceEndpoint = Get-VstsEndpoint -Name $connectedServiceName -Require
	#connected service	$userName =  $serviceEndpoint.Auth.Parameters.username	$passWord = $serviceEndpoint.Auth.Parameters.password	$clientId = $serviceEndpoint.Data.clientId
	if(!$clientId){		$clientId = $serviceEndpoint.Auth.Parameters.servicePrincipalId	}
	$clientSecret = $serviceEndpoint.Auth.Parameters.servicePrincipalKey	$tenantId = $serviceEndpoint.Auth.Parameters.tenantId
	Write-Host "******************************"	Write-Host "** Service Connection: $($connectedServiceName)"	Write-Host "** TenantId: $($tenantId)"	Write-Host "** ClientId: $($clientId)"	Write-Host "******************************"
	if($password){		$passWord = ConvertTo-SecureString $passWord -AsPlainText -Force	}
	if($clientSecret){		$secret = ConvertTo-SecureString $clientSecret -AsPlainText -Force	}
	#parameters	$filePattern = Get-VstsInput -Name PowerBIPath	$workspaceName = Get-VstsInput -Name WorkspaceName	$overwrite = Get-VstsInput -Name OverWrite -AsBool	$create = Get-VstsInput -Name Create -AsBool	$action= Get-VstsInput -Name Action -Require	$dataset = Get-VstsInput -Name DatasetName	$oldUrl = Get-VstsInput -Name OldUrl	$newUrl = Get-VstsInput -Name NewUrl	$oldServer = Get-VstsInput -Name OldServer	$newServer = Get-VstsInput -Name NewServer	$oldDatabase = Get-VstsInput -Name OldDatabase	$groupObjectIds = Get-VstsInput -Name GroupObjectIds	$newDatabase = Get-VstsInput -Name NewDatabase	$accesRight = Get-VstsInput -Name Permission	$users = Get-VstsInput -Name Users	$datasourceType = Get-VstsInput -Name DatasourceType	$updateAll = Get-VstsInput -Name UpdateAll -AsBool	$ServicePrincipalsString = Get-VstsInput -Name ServicePrincipals 	$ConnectionString = Get-VstsInput -Name ConnectionString
	.\run-task.ps1 -Username $userName -OldUrl $oldUrl -NewUrl $newUrl -OldServer $oldServer -DatasourceType $datasourceType -NewServer $newServer -OldDatabase $oldDatabase -NewDatabase $newDatabase -AccessRight $accesRight -Users $users -FilePattern $filePattern -Password $passWord -ClientId $clientId -WorkspaceName $workspaceName -Overwrite $overwrite -Create $create -Dataset $dataset -Action $action -UpdateAll $UpdateAll -ClientSecret $secret -TenantId $tenantId -ServicePrincipalString $ServicePrincipalsString -ConnectionString $ConnectionString -GroupObjectIds $groupObjectIds}finally {    Trace-VstsLeavingInvocation $MyInvocation}

**Comment by maikvandergaag** [comment]
What kind of version are you running of the extension? 

Besides that the script shown is I think of the old version. Besides that there are functions in there that will not work in a regular powershell session.

**Comment by Ragunath452** [comment]
Version 5.*

**Comment by Ragunath452** [comment]
we come to know that private server can not connect to Power BI Services.

**Comment by Ragunath452** [comment]
Do we need to provide Client Secret and Client Certificate both ?

**Comment by RGunasekaran21249030** [comment]
we provided the client secret and it worked. Thank you everyone!
