### ISSUE TITLE
Power BI Actions: Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by NiteshMarshom** [maikvandergaag/msft-extensions#293]
Hi,

I am using Power BI Actions in my Azure DevOps Release pipeline and getting the below error:
![image](https://user-images.githubusercontent.com/60717285/123340193-bc15c300-d543-11eb-967a-9ae3de5e6d9e.png)

I am using a Service Principal to create the Power BI service connection and Service Principal has been granted admin level access to the target workspace. Please see below how it is configured:
![image](https://user-images.githubusercontent.com/60717285/123340495-3a726500-d544-11eb-82ea-08e0092eb37b.png)

I am not sure what else is required in terms of getting this working and would really appreciate any pointers regarding this issue. My target workspace is in PBI Premium Per User capacity.

Regards,
Nitesh

**Comment by maikvandergaag** [comment]
Please add the variable system.debug with the value true to the pipeline.

And who created the workspace the extension or was it already there?

**Comment by NiteshMarshom** [comment]
Thanks for your response. I am not sure where to enable/add the system.debug variable in my release pipeline. I know how to do that in the build pipeline but not sure about the release pipeline.

I created the PBI workspace and added the extension to my organization from the market place.

Regards

**Comment by maikvandergaag** [comment]
That should work did you also trigger a new release?

**Comment by NiteshMarshom** [comment]
Yes, I did create a new release but still the same error message i.e Invalid Status Code "Unauthorized"

**Comment by maikvandergaag** [comment]
That's correct but the log should show more info

**Comment by NiteshMarshom** [comment]
Correct. There is something more I can see now in the log. I can see the exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'

![image](https://user-images.githubusercontent.com/60717285/123536284-4e26f280-d721-11eb-81df-fc64448dd2f3.png)

**Comment by maikvandergaag** [comment]
Oké, does the action to create a workspace work?

**Comment by NiteshMarshom** [comment]
When I changed the action to create workspace, it does work. I can see the workspace created using the Power BI Service connection that uses my credentials on Power BI Service. However, I can't see the workspace created using Service Principal on the Power BI Service.

**Comment by NiteshMarshom** [comment]
Okay.
**Case1**: I am working on my own subscription on my personal machine.
1. Created SPN (noted down app/client id, tenant id and secret value) and granted Power BI Service Tenant.ReadAll and Tenant.ReadWriteAll API permissions 
2. Created an Azure AD security group and added the SPN created in Step 1
3. Installed Power BI Actions to my Azure DevOps organization from market place
4. Enabled **Allow Service Principals to use Power BI APIs** and specified Azure AD security group created in Step 2 using Power BI admin portal.
5. Added the security group created in Step 2 as an admin to a workspace which is the target for Step 6. **Please note that this workspace is created by me and not by SPN using Power BI Action component**
6. Created an Azure DevOps  release pipeline using Power BI Action to publish a report using Power BI Service connection created using the SPN created in Step 1.

**_Pipeline fails with "Unauthorized Status code". Error log attached earlier._**

**Case2**: Step 1 - Step 4 Same as Case 1 
5. Created an Azure DevOps  release pipeline using Power BI Action to create a workspace using using Power BI Service connection created using the SPN created in Step 1.
6. Added another step to release pipeline using Power BI Action to add a user (myself) to the workspace created in previous step.
7. Added another step to release pipeline using Power BI Action to publish a report to the workspace created in Step 5.

Power BI Action is using Power BI Service connection created using the SPN created in Step 1.

_**Pipeline runs successfully. Created workspace, added me as admin and published the report.**_

**Case3**: I am working on my client's subscription on their machine where I have limited access where I neither have permissions to install Power BI Action from market place nor permission to create SPN/Azure Security Group/Access the Power BI admin portal to tweak tenant level settings. 
1. Someone from the IT created SPN (noted down app/client id, tenant id and secret value) and granted Power BI Service Tenant.ReadAll and Tenant.ReadWriteAll API permissions 
2. Someone from IT created an Azure AD security group and added the SPN created in Step 1
3. Someone from IT installed Power BI Actions to Azure DevOps organization from market place
4. Someone from IT enabled **Allow Service Principals to use Power BI APIs** and specified Azure AD security group created in Step 2 using Power BI admin portal.
5. I added the security group created in Step 2 as an admin to a workspace (to which I am an admin) which is the target for Step 6. **Please note that this workspace is created by IT**
6. I created an Azure DevOps  release pipeline using Power BI Action to publish a report using Power BI Service connection created using the SPN created in Step 1.

_**Pipeline fails with "Unauthorized Status code". Error log attached earlier.**_

Any help? I think I have got all bases covered but seems still something is missing somewhere.

**Comment by supunthri** [comment]
I'm getting the same error for my Premium Per User workspace. Case 2 from @NiteshMarshom worked for me as well and what I noticed was it creates a "Pro" workspace. But when I switch it back to "PPU" I start getting the the same error.

Is there an additional setting that should be set for PPU workspaces?

PS: This works for Premium Capacity workspaces so looks like the issue is specific to PPU.

Thanks!

**Comment by maikvandergaag** [comment]
@NiteshMarshom: could you check with direct assignments?

**Comment by maikvandergaag** [comment]
Could you do a retest and share the logs with version 5.4.9

**Comment by tushmesh** [comment]
I am getting the same error while trying to either create a workspace or publish via SPN.

**Comment by maikvandergaag** [comment]
@tushmesh: that is the status regarding your issue.
