### ISSUE TITLE
Update SQL Direct Query String return (400) Bad Request.

### ISSUE THREAD

**Issue by IagoFranco** [maikvandergaag/msft-extensions#295]
Hi @maikvandergaag how are you?

Can you try to help me on this?
I'm trying to use the Update SQL Direct Query String feature with Power BI Actions, but when I run, I got a Bad Request response, see:

 
![image](https://user-images.githubusercontent.com/68740646/124659120-fbfd7400-de7a-11eb-9012-392bfb64c2da.png)

[SQLDirect Log.txt](https://github.com/maikvandergaag/msft-extensions/files/6772541/SQLDirect.Log.txt)

**Comment by maikvandergaag** [comment]
@IagoFranco:

Could you maybe share more info:
- What type of connection are you using SPN / User
- What kind of agent?
- Task configuration

**Comment by IagoFranco** [comment]
Hey @maikvandergaag 
I'm using SPN connection.

This is the agent:
![image](https://user-images.githubusercontent.com/68740646/124758160-ae2d4e00-df04-11eb-81fa-7b741bf94d3b.png)

This is the task configuration:
![image](https://user-images.githubusercontent.com/68740646/124758325-d5841b00-df04-11eb-8fab-29549a32dd1b.png)

**Comment by maikvandergaag** [comment]
Ok, will try to find some time to check what is going wrong.

**Comment by IagoFranco** [comment]
Hi @maikvandergaag 
Did you get a chance to look at this?

Thank you very much!

**Comment by maikvandergaag** [comment]
A new version is being deployed to production could you please check that version if the problem still exists?

**Comment by IagoFranco** [comment]
Hey @maikvandergaag 
I just ran again my release pipeline, but the same error ocurred: The remote server returned an error: (400) Bad Request.

**Comment by maikvandergaag** [comment]
Oké will further check the issue

**Comment by maikvandergaag** [comment]
Could you try it out with the new version?
