### ISSUE TITLE
(Fix) Testing Update SQL Credentials - 'Unauthorized'

### ISSUE THREAD

**Issue by joaovictormelo42** [maikvandergaag/msft-extensions#298]
In the Action: Update SQL Credentials, i had the return: Operation returned an invalid status code 'Unauthorized'.

How i have to declare the parameters? I mean, i want to know if i have to use " " in the password or name parameters. 
My password has special caracteres, i dont know if has some trouble with it. 

Password example: Jk/cc45[z12A

I'm doing like the example below
![image](https://user-images.githubusercontent.com/20947225/126724351-cbb7f788-878e-4d56-9d6e-9004d53ea62e.png)

PS: I test my connection in the Power BI desktop, and it works. 

Edit: I'm using this Action after Publish, Takeover and update data source connection.

**Comment by maikvandergaag** [comment]
You should not have robust " in the names. Unauthorized sounds like an authentication issue or rights issue are you sure the service connection has the right permissions to do this?

**Comment by joaovictormelo42** [comment]
Hi Maik, tnks for answer. Yes, i'm sure, because i try before with my own script, but in my script i use a decode in password to base64 because of the special caracters. Still works with the script, but i wanna try this to maintain all the actions without depending on the 'rest api' who my script call.

**Comment by maikvandergaag** [comment]
Ok, 

Could you share a sample of your script so that i can check to incorporate

**Comment by keithd99** [comment]
Hi both! 

Getting the exact same issue - did you find a resolution by any chance? 

We are trying to update all tenant DataSets in a multi-tenanted environment with the following steps .. 
![image](https://user-images.githubusercontent.com/7514964/129566677-bcba5ec8-0d05-4fd0-84df-f51f21e4f1c3.png)

and getting same unauthorised error
![image](https://user-images.githubusercontent.com/7514964/129566438-3a1d5338-0ec6-47e4-9b5d-0ceb7afe5228.png)

(The service principal the pipeline is running as has admin access to the Workspaces)

**Comment by joaovictormelo42** [comment]
Hi, Mike! I didn't upload my function before because it has some personal info in there, so i'm focusing in not using more the function on pipeline, doing the upload and updating sql credentials only with power bi actions. 

I put the system.debug on pipeline variables and get this return:

![image](https://user-images.githubusercontent.com/20947225/133319072-92a08dc4-2b37-4a6a-b821-7c8ee2396ec9.png)

I validate the credentials for database manually, they are correct. I dont now if the problem is with it, but i try to give the admin access for my user on power bi service, but nothing changed.

![image](https://user-images.githubusercontent.com/20947225/133319402-b67df110-5337-45f3-8a0c-f95541868f24.png)

**Comment by joaovictormelo42** [comment]
I will open a new issue with new information i have for the same problem to update the post.
