### ISSUE TITLE
Update Datasource Connection is not working in Power BI Action tasks in DevOps

### ISSUE THREAD

**Issue by Annadhaksc** [maikvandergaag/msft-extensions#300]
Hi ,

I've two power bi action task. First one configured for Publish Action. it is working fine.

The second power bi action task, I've configured the action as Update Data Source Connection. My source is Analysis service. 

The task getting completed successfully. But, data source value not changed.  What I have to change. I've provided all the mandatory values of the task. Please help me on the same.

#98 #

**Comment by maikvandergaag** [comment]
@Annadhaksc could you share the logs with system.debug false set to false?

**Comment by maikvandergaag** [comment]
No more comments
