### ISSUE TITLE
Multiple Errors Occurred 

### ISSUE THREAD

**Issue by Ragunath452** [maikvandergaag/msft-extensions#301]
We are trying to use this Power BI Action to perform Power BI CI/CD from Azure DevOps Server ( TFS) 2019. we created service principal and trying to create, delete and add the users to workspace. But we are getting the below error
Failed to populate environments in settings

Do we need to provide both Client Secret and Certificate ?

**Comment by maikvandergaag** [comment]
You can use Client Secret or Certificate
