### ISSUE TITLE
##[error]Cannot bind argument to parameter 'String' because it is an empty string.

### ISSUE THREAD

**Issue by shyammayhs** [maikvandergaag/msft-extensions#302]
Hi, I am trying to setup a pipeline using the Power BI Action: Publish job. But I am running into the error -  ##[error]Cannot bind argument to parameter 'String' because it is an empty string. 

What am I doing wrong?

I would also like to Update a parameter but I will add that in once I have fixed the issue with Publishing the report.

Thanks.

**Comment by maikvandergaag** [comment]
Could you share the logs with the system.debug variable set to true, and share some screen shots?

**Comment by shyammayhs** [comment]
Hi Maik, 
![image](https://user-images.githubusercontent.com/36566182/129730908-a1211c42-4bd1-4cdd-9353-39b9653b8323.png)

I may need a walkthrough to how to set the system.debug variable up. (I have added it to the Variable page)

**Comment by maikvandergaag** [comment]
Ok, I think it is something in the service connection. Could you share a screenshot of that configuration and send the log.txt file that can be downloaded?

**Comment by shyammayhs** [comment]
I may have realised something. 
![image](https://user-images.githubusercontent.com/36566182/129735587-fa0d89fe-9187-4b82-9193-31647bbc7a85.png)
These fields are optional in the job so I have left them blank. However I have a feeling these blanks are causing the problem?

**Comment by maikvandergaag** [comment]
Yes you have to fill in one of them

**Comment by shyammayhs** [comment]
thanks, I have added the client secret.
but now I get this error
![image](https://user-images.githubusercontent.com/36566182/129737334-e443b120-5b5b-464f-94eb-fdf166d97386.png)

**Comment by maikvandergaag** [comment]
Can you share a screenshot of your service connection configuration

**Comment by shyammayhs** [comment]
sure here you go.
![image](https://user-images.githubusercontent.com/36566182/129742862-a7345a1a-5bcb-4760-b49e-12ace89f3ce8.png)

**Comment by maikvandergaag** [comment]
Ok could you share the log.txt

**Comment by shyammayhs** [comment]
do I achieve this by clicking this?
![image](https://user-images.githubusercontent.com/36566182/129744061-5bb7c8ef-ca1a-47dd-bfb4-54bc77f53ddb.png)

**Comment by maikvandergaag** [comment]
yes

**Comment by shyammayhs** [comment]
here you go :)
[3_Power BI Action Publish.log](https://github.com/maikvandergaag/msft-extensions/files/7000783/3_Power.BI.Action.Publish.log)

**Comment by maikvandergaag** [comment]
please recreate the service connection for some reason the tasks sees a certificate value. That should not be there

**Comment by shyammayhs** [comment]
okay thanks.  I will recreate it now. in the Certificate secret, which value are you meant to use?
![image](https://user-images.githubusercontent.com/36566182/129746353-913a5ef9-c691-4730-97f6-c9d5393bb472.png)

**Comment by maikvandergaag** [comment]
That is somewhere else on the application. For a SPN you can use Client Secret of Client Certificate authentication

**Comment by shyammayhs** [comment]
I have created a Client Secret on Azure. But do I use the 'value' or the 'secret ID'?

**Comment by maikvandergaag** [comment]
You should use the value

**Comment by shyammayhs** [comment]
I think it has been fixed now thanks. Although later on in the process, it is saying my workspace doesn't exist. I have added my Group (with SPN in there) to the Tenant and also the workspace!!

**Comment by maikvandergaag** [comment]
Otherwise you can let the task create the workspace

**Comment by shyammayhs** [comment]
That would only be suitable for the first deployment. After I have an update, I would need to find existing workspaces!

**Comment by shyammayhs** [comment]
Update - the Pipeline actually worked now! wahoo!
thanks for your speedy support. have a great day :)

**Comment by arnabdasgupta04** [comment]
@maikvandergaag I am getting the below error while using powerBI action 
![image](https://user-images.githubusercontent.com/63199431/141101130-bfa6e585-5497-416c-b6ce-e669fd47604b.png)

It is asking for client secret even after providing client secret as shown in the below snapshot.

![image](https://user-images.githubusercontent.com/63199431/141101559-7806a23c-8af2-4e7f-a1b4-524c3d51e392.png)

The power Bi action is taking the power BI service connection instead of the v4 one as shown below 

![image](https://user-images.githubusercontent.com/63199431/141101841-baa6628d-4fd4-4b3f-a04d-2ba0f990dd44.png)

Kindly please assist me in this issue .

**Comment by manthonyh** [comment]
It needs CLIENT SECRET
from your client secret, get the **VALUE** not the ID and use it

**Comment by Pass1406** [comment]
> I think it has been fixed now thanks. Although later on in the process, it is saying my workspace doesn't exist. I have added my Group (with SPN in there) to the Tenant and also the workspace!!
