### ISSUE TITLE
capacity could not be found! error on Workspace set capacity task, Power BI Action

### ISSUE THREAD

**Issue by mwbong** [maikvandergaag/msft-extensions#303]
Per subject, I am trying to add a task to assign a capacity to a Power BI workspace.

However I ran into a "capacity could not be found!" error. With the same service principal I was able to see the capacity on Powershell/Invoke-RestMethod

Poking at powerbi.psm1, I wonder whether in the following block of code for Get-PowerBICapacity function, **name** should be **displayName** instead?

if (-not [string]::IsNullOrEmpty($CapacityName)) {

        Write-Verbose "Trying to find capacity: $CapacityName"		
        $items = @($capacities | Where-Object name -eq $CapacityName)
    
        if ($items.Count -ne 0) {
            $capacity = $items[0]		
        }				
    }

**Comment by maikvandergaag** [comment]
@mwbong the functions looks correct could you share your configuration

**Comment by mwbong** [comment]
hi @maikvandergaag, thanks for responding

I have a Power BI embedded capacity (A1 Sku) and the Service Principal that performs DevOps tasks has been made a Capacity Administrator of this capacity.

The workspace was created by the same automation SP.

I have attached a few of screenshots for your reference.

Hopefully this is all the information you need but otherwise feel free to let me know what else is needed.

![image](https://user-images.githubusercontent.com/4377627/129846340-9ef3b9b5-fbba-437c-b422-3794f1b85270.png)
![Result](https://user-images.githubusercontent.com/4377627/129846626-35ec8d79-f705-40fb-8282-218d408b7866.jpg)
![PBI Actions](https://user-images.githubusercontent.com/4377627/129846883-98af768a-e5ee-48e6-9071-561a8f3d34c7.jpg)

**Comment by maikvandergaag** [comment]
At the moment I'm building a beta version with a change. If you share your organization name I can share the beta version with you

**Comment by mwbong** [comment]
Hi Maik,

My organization name is as below:

galactica-anz

Thanks very much!

**Comment by maikvandergaag** [comment]
Extension can be installed from here:

https://marketplace.visualstudio.com/items?itemName=Development-vanderGaag.maikvandergaag-power-bi-actionsDev

**Comment by mwbong** [comment]
hello @maikvandergaag, unfortunately i'm still having the same error with the beta version:
![image](https://user-images.githubusercontent.com/4377627/129975531-6a31b68f-9007-4b51-aa9b-f694968916f5.png)

**Comment by maikvandergaag** [comment]
Could you send the logs with the value system.debug set to true

**Comment by mwbong** [comment]
Hi @maikvandergaag 
As requested. The logs contain two actions - Create workspace 'TestDevops' and assign it to pbietest20210722 capacity.

Let me know if you need more information.

Thanks again
[devopslog.txt](https://github.com/maikvandergaag/msft-extensions/files/7013778/devopslog.txt)

**Comment by maikvandergaag** [comment]
Did you get around this issue. Checked the solution, the solution retrieves all the capacities via the API. It could be the case that the security used is not able to access the capacity.

**Comment by mwbong** [comment]
Hi Maik, we worked around the issue by calling Power BI API instead. Thanks!

**Comment by jreitz43** [comment]
I'm getting this exact same issue. It retrieves the capacity list just fine, but cannot find the capacity on this section:
`    Write-Verbose "Trying to find capacity: $CapacityName"		
    $items = @($capacities | Where-Object name -eq $CapacityName)`

because it uses 'name', rather than 'displayName' from the api response. When I replicate and pull out displayName from the response, it finds it just fine. Any reason not to use displayName in the Where-Object filter?

**Comment by maikvandergaag** [comment]
made an update by replacing it could you check if that works? Will be updated in about 10 min
