### ISSUE TITLE
Update Refresh Schedule

### ISSUE THREAD

**Issue by zuheirashraf17** [maikvandergaag/msft-extensions#304]
Hi @maikvandergaag,
Wish you were doing great!

I would like to know if there is any plan having a feature to set up a refresh schedule via Power BI Action
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/update-refresh-schedule-in-group

Thanks and very much appreciate it!

**Comment by maikvandergaag** [comment]
Not yet on the roadmap but looks like an amazing feature. Will be looking into it

**Comment by maikvandergaag** [comment]
Is published in version 5.4.9
