### ISSUE TITLE
[Fix] Operation returned status code "Unauthorized" - Possible Solution

### ISSUE THREAD

**Issue by joaovictormelo42** [maikvandergaag/msft-extensions#305]
Hi Maik!
I've been had some trouble with a new task on Power Bi Actions, and looking through the code i find what is interrupting the update credentials task.

On this file:
    msft-extensions/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1
In line 890:
    $workspace = (Get-PowerBIWorkspace **-Scope Organization** -Name $WorkspaceName)

Using the -scope parameter with Organization value, we got the unauthorized response because the user is not a fully admin on scope, because of the size of this project. I test using the default value **Individual** and got the positive return, you can see below:

![image](https://user-images.githubusercontent.com/20947225/133621564-bd3d6a6c-a38f-42e7-bd02-dca7e301d7ab.png)

This is my azure pipeline log:
![image](https://user-images.githubusercontent.com/20947225/133621593-5cbbb89b-ea7c-4e86-9574-bcc6f7840473.png)

Can you update the code, passing this "Organization" or "Individual" value by parameters on power bi actions task? I mean, if you can just remove the -scope is ok, but if not, maybe there is a way to edit this parameters on pipeline directly, for this type of case.

doc.: https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.workspaces/get-powerbiworkspace?view=powerbi-ps

**Comment by maikvandergaag** [comment]
Updated the code new version will be published shortly
