### ISSUE TITLE
Power BI extension doc missing from wiki

### ISSUE THREAD

**Issue by marcdebrouwer** [maikvandergaag/msft-extensions#306]
The readme for the power BI actions extension points to your wiki on github, but there seems to be nothing there anymore for this extension?

**Comment by maikvandergaag** [comment]
Strange will look into it. Thanks for pointing it out

**Comment by maikvandergaag** [comment]
thanks again fixed should be rolled out shortly. If you have any further questions please ask

**Comment by marcdebrouwer** [comment]
readme got updated - wiki still empty (this is where the "more information" link from the readme points to)
