### ISSUE TITLE
Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by giznaj** [maikvandergaag/msft-extensions#313]
Hi everyone!
First off, thanks for this extension.  It looks like once you have it working, it is pretty helpful.  For this issue, I have referenced previous issues #283 , #293 and #302 and they have helped get me to my current state

Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'

##[debug]Remove report           :
Getting Power BI Workspace properties; Aaron_POC [Test]
##[debug]10:24:49 AM - Get-PowerBIWorkspace begin processing with ParameterSet Name.
##[debug]10:24:49 AM - Cmdlet version: 1.0.896.0
##[debug]Error record:
##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'

##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.3.34\ps_modules\PowerBi\PowerBi.psm1:658 char:22

My setup is similar, if not exact as the other issues referenced above

1. That workspace exists
2. A Service Connection of type "Service Principal" has been created in advance
3. SP has the ability to access the pipelines
4. SP has the been added as an Admin to the PBI workspace (workspace exists manually and worspace created in PBI pipeline)
5. SP permissions (App registrations)

Azure Active Directory Graph (user read)
Power BI Service (Dataset read all)
Power BI Service (Dataset read.write all)

Pipeline is not able to refresh the datasets or publish a report in a manually created workspace, or a workspace created through PBI pipelines.  The error message is the same, so it is something about accessing this or any workspace.

The only thing that I can think of is an API permission that is missing, but I don't know.

**Comment by maikvandergaag** [comment]
The extension now has some reporting and error capabilities please retest with version 5.4.9. If the problem still is there please add another issue and post the log as well.

**Comment by giznaj** [comment]
I will do that now.  Thanks for getting back to me.  I'll ask the other questions there too.

**Comment by giznaj** [comment]
Sorry, this was run against 5.4.9
I will still open a new ticket with more details.

**Comment by giznaj** [comment]
This is due to the SP not being authorized (added to the list of users who can access the PBI API) and the error is exactly that. This has been resolved by adding the SP to the API.  All other permissions remained.
