### ISSUE TITLE
Space is a .pbix file name seem to have caused the publish fail.

### ISSUE THREAD

**Issue by JayaprasadChintada** [maikvandergaag/msft-extensions#314]
Hi,

The task 'Power BI Action: Publish' has thrown the below error and it's apparently because of the space in the .pbix file name. Please can you let me know if this is a know-issue/limitation or if there's a solution/work-around for this? 

**[error] The import was not successful for import ID '832XX-XXXXXXX-XXXX-XXXX-8ea77c7971bc', report name 'Value Dashboard'. The import state was 'Failed'.**

There were many releases which completed successfully from the same release definition when the filenames had no space. 

![image](https://user-images.githubusercontent.com/4254830/137523236-84bc653d-44cc-4331-89e9-76472afa465d.png)

**Comment by maikvandergaag** [comment]
That is strange. Is there anything specific for the report? Could you maybe share it for investigation

Groetjes,

Maik van der Gaag
________________________________
Van: Jayaprasad Chintada ***@***.***>
Verzonden: Saturday, October 16, 2021 2:37:44 PM
Aan: maikvandergaag/msft-extensions ***@***.***>
CC: Maik van der Gaag ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [maikvandergaag/msft-extensions] Space is a .pbix file name seem to have caused the publish fail. (#314)


Hi Maik,

It failed with the same error even after I renamed the report and removed the space. However, I could publish it manually i.e. from Power BI desktop both with and without space.

Regards,
Jayaprasad
