### ISSUE TITLE
Azure RBAC - Allow Multiple Roles  / Ability to select resource

### ISSUE THREAD

**Issue by patpicos** [maikvandergaag/msft-extensions#32]
Hi

It would be nice to allow the selection of multiple roles to assign to a group. For example, I would like to have the team receive reader to see all the resources, but also have specific roles assigned like Data Factory Contributor. 

On the flip side, it might make more sense to grant a generic permission at the RG and then Elevate on some resources (data factory, ADLA). The current plugin goes as far as RG.

**Comment by patpicos** [comment]
so far ill manage w/ perms at the RG. not a rush.its not a blocker for the pipelines i have on the go.

**Comment by maikvandergaag** [comment]
Sorry for the late response due to some personal stuff I haven't been able to proccess this hope to be able to do this in august

**Comment by maikvandergaag** [comment]
Investigated and will not be added to the extension
