### ISSUE TITLE
Operation returned an invalid status code 'Unauthorized' / $workspace = Get-PowerBIWorkspace -Name

### ISSUE THREAD

**Issue by giznaj** [maikvandergaag/msft-extensions#324]
This is related to issue #313 

etting Power BI Workspace properties; Aaron_Workspace [Test]
##[debug]8:33:23 PM - Get-PowerBIWorkspace begin processing with ParameterSet Name.
##[debug]8:33:23 PM - Cmdlet version: 1.0.896.0
##[debug]Error record:
##[debug]Get-PowerBIWorkspace : Operation returned an invalid status code 'Unauthorized'
##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.9\ps_modules\PowerBI\PowerBI.psm1:662 char:22
##[debug]+ ...       $workspace = Get-PowerBIWorkspace -Name $WorkspaceName -Verbose
##[debug]+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...owerBIWorkspace:GetPowerBIWorkspace) [Get-PowerBIWorkspac    e], HttpOperationException
##[debug]    + FullyQualifiedErrorId : Operation returned an invalid status code 'Unauthorized',Microsoft.PowerBI.Commands.Work    spaces.GetPowerBIWorkspace
##[debug]
##[debug]Script stack trace:

The SP has been added to the workspace(s) as admin - all in the pipeline (so both manually created an automated workspaces)
The App.Registration has the following API permissions Workspace(Read.Write.All), Dataset(Read.Write.All)
SP has been configued to use the pipeline

if I run with the option to 'overwrite' or 'create', the CI fails at same step with same reason.

**Comment by maikvandergaag** [comment]
Seems like the SPN is still missing some part of the configuration as it is saying unauthorized. Are there actions you can perform with the extension

**Comment by giznaj** [comment]
There are no actions that I can perform.  I was getting the error like the other users previously with "" values been passed for secret/certificate.  I have since then recreated 2 new service connections.  One using a cert and one usin a secret.  

I'm not sure what you could be leaving out, beause all the forms wouldn't save if they were not completed.  You can't save an incomplete service connection in azure.  In the pipeline you can't save empty values either.  

Let me ask.  What API permissions are needed to publish a pbix, or refresh a dataset?  Also, does the issue exist with workspaces that are created manually?

**Comment by giznaj** [comment]
I'm also wondering if it would be a good test to pass these value to a azure runbook or run them from powershell as a test?  I can look into that too.

**Comment by maikvandergaag** [comment]
Easiest thing to try is cloning the repo en testing the scripts locally.

I presume you are using a Microsoft Hosted Agent or are you using a Private one.

For the SPN what fields did you fill for the Service Connection

**Comment by giznaj** [comment]
Yes we are using a hosted agent apps.powerbi.com.  It is a public/commercial instance as well.  When I configure the SPN
Type
TenantID
ClientID
Secret
Name

I know about the App Registrations API permissions, but I also just realized that you need

"Allow App Registrations to use Power BI API" to be enabled, which I don't see as the Capacity Admin.

In the capacity, I do see the option of 

XMLA endpoint set to -> READ/WRITE

I am looking into this part.

**Comment by giznaj** [comment]
I believe I know what it is and this will be verified either Monday/Tuesday.

**Comment by giznaj** [comment]
I have resolved the issue.  The SP was not added to the list of approved users/security groups who have access to the Power BI API.  At the capacity level, you cannot see this setting.  You need tenant level permissions and this was the reason for the delay in finding out.  The extension is working great.
