### ISSUE TITLE
Error: A parameter cannot be found that matches parameter name 'Workspace'.

### ISSUE THREAD

**Issue by joaovictormelo42** [maikvandergaag/msft-extensions#326]
Hi, Maik!

After version 5.4.9 i try to update my sqlCredentials, but i got this error message:

![image](https://user-images.githubusercontent.com/20947225/140756870-9d950d70-7bd3-4446-807f-54fa0735bbce.png)

Where do i fill this in powerBi Actions fields?

![image](https://user-images.githubusercontent.com/20947225/140757153-fb931b7c-4fd3-48ef-82ac-2160f5118ae2.png)

I've see on code, where the function has been called, in line 997, the parameter $workspace.

https://github.com/maikvandergaag/msft-extensions/blob/bf16963cd45b7da63fc3b1681bed0344a403cb6d/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1#L986-L1000

**Comment by maikvandergaag** [comment]
@joaovictormelo42 thanks for pointing that out. I think I have a fix inplace do you have access to the beta

**Comment by joaovictormelo42** [comment]
> @joaovictormelo42 thanks for pointing that out. I think I have a fix inplace do you have access to the beta

I'm sorry, i dont know if i understand correctly, can i use this beta version?

**Comment by maikvandergaag** [comment]
Yea if you have access but let me push the version to production. Would you mind testing it

**Comment by joaovictormelo42** [comment]
Shure! I can test and reply here if something else happen. Thank you for the promptness to fix that!

**Comment by joaovictormelo42** [comment]
@maikvandergaag i had a "new-old" problem, the same issue we had with this guy, but few lines above:

https://github.com/maikvandergaag/msft-extensions/blob/bf16963cd45b7da63fc3b1681bed0344a403cb6d/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1#L1000

We discuss some days ago, to put them, like in this line over here:

https://github.com/maikvandergaag/msft-extensions/blob/bf16963cd45b7da63fc3b1681bed0344a403cb6d/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1#L994

Sorry for not seeing this before.

**Comment by maikvandergaag** [comment]
@joaovictormelo42 missed that one as well. Fix is in the pipeline and will be deployed within 30 min.
