### ISSUE TITLE
Using a variable for the DataSet name with TakeOwnership?

### ISSUE THREAD

**Issue by Richtpt** [maikvandergaag/msft-extensions#327]
How do I use a variable for the DataSet name with TakeOwnership?  Everything works fine if I hard-code the DataSet name.  I want to make this dynamic to work with any pbix file I publish.  My publish looks like this:

![image](https://user-images.githubusercontent.com/1249003/140836598-9e9eb462-99c5-4d61-b21a-a70b6c56f8e7.png)

It's working with whatever pbix file is in the $(packagePath), that pbix gets published to the Workspace.  After Publish I have a TakeOwnership so I can then do UpdateParameters and DataRefresh.  If I hard-code DataSet name for all of these to whatever the dataset is for the pbix I'm publishing it works fine, so I know it's working.

How can I do this without hard-coding the DataSet name?  If using a variable is the wrong approach I'm good with whatever is the correct way.  Thanks!

**Comment by maikvandergaag** [comment]
@Richtpt: Don't think there is a good solution for this in the extension at the moment. What you could do if possible to take the ownership of all items in the workspace.

**Comment by Richtpt** [comment]
To take ownership of all items, would the Source file be "*"?

**Comment by Richtpt** [comment]
Oh sorry, ignore that.  I didn't see the checkbox to take ownership on all datasets in the workspace.  That could work.  Maybe a variable could be a future enhancement?  Thanks!

**Comment by maikvandergaag** [comment]
Great will look for any options to get this is as a possible enhancement

**Comment by Richtpt** [comment]
At least in the Power BI reports I'm working with right now, the Dataset name is the same as the Report name.  If I could get the report name (less the extension) as output from the Publish task, I could set a DevOps variable with that then use that variable in these other tasks.  Just an example of how I would use this feature and could get rid of the Powershell I'm doing.  :)

**Comment by maikvandergaag** [comment]
I will check if we can add that. Maybe we can get it into an output variable of the task

**Comment by Richtpt** [comment]
Cool, thanks!

**Comment by mattias-de-coninck** [comment]
@Richtpt if I understand it correctly, u just want to reuse the variable because it references both the dataset and report name?

Maybe the following works for your use case:

Variable A = **File Name**
Variable B = **File Path**

1. Upload file, concatenate **Variable B**, **Variable A** and the suffix
2. Take ownership, use **Variable A**
3. Datarefresh, use **Variable A**

**Comment by Richtpt** [comment]
I'm still fairly new to Power BI.  So far all of the Power BI reports I've created have the dataset being the same name as the report.  For example, I created a report RichParamUpdateTest.pbix.  The dataset is named RichParamUpdateTest.  All of the reports I see are like that.  

If that's always the case (or normally the case), then I'm thinking if I could get the report name as an output variable from the publish task then I could use that as the dataset name for the other tasks.  Basically, have a way to use the report name as the dataset name in the other tasks, however that may work.

What I have working right now is in the build pipeline, there's a variable that has to be updated with the name of the pbix file - it is only building one file, it can't build several.  It zips that file and uploads it to a folder.  In the Release pipeline I have it unzipping the file and running your Publish task to publish that file.  I can't use your other tasks because the dataset has to be hard-coded.  So I have a Powershell task that connects to the Power BI Service account (Connect-PowerBIServiceAccount).  It gets the new parameter value from a pipeline variable.  It does a Get-ChildItem from the path the file was unzipped to so I can get the $_.BaseName and use that as the dataset name - there's only one file in that folder so this works.  Then using the MicrosoftPowerBIMgmt module I issue Invoke-PowerBIRestMethod to take ownership, update the parameter, BindToGateway then refresh the dataset.  All of this works - well, I'm getting a 429 TooManyRequests error on the refreshes at the moment that I'm trying to solve.  I would much rather use your tasks because they are a lot easier to understand and manage.  If I had a way to dynamically set the dataset name then I could use your tasks - everything worked perfect when I hard-coded the dataset name.

**Comment by mattias-de-coninck** [comment]
@Richtpt you are most likely hitting your refresh schedule limit.
For Power BI Pro, the max refreshes per day is **8**. Premium can go up to **48**, and yes, API calls count towards this limit.

Having the same name for dataset and report is fine to begin with, but I would suggest storing and uploading the dataset and report separately. This allows you to use the same dataset for multiple reports and is also a lot cleaner to work with. 

As an example see below:
![image](https://user-images.githubusercontent.com/59693063/142021071-aea93b73-3b8d-4ee8-9950-4f5dbb9a5d86.png)
![image](https://user-images.githubusercontent.com/59693063/142021420-284b112a-37a8-40e6-b40e-31eb3b0ac1fa.png)

**Comment by Richtpt** [comment]
@maikvandergaag Thanks about the limit, I couldn't find that anywhere.  It's weird that all the other Invoke's work fine, only the refresh fails with the 429 error.  And thanks about the datasets, that's a good idea and a process I'll work on following.  :)
