### ISSUE TITLE
##[error]The requested REST API version of 6.1 is out of range for this server. The latest REST API version this server supports is 6.0.

### ISSUE THREAD

**Issue by Yaseen17** [maikvandergaag/msft-extensions#329]
I am getting this error while using rigger Azure DevOps Pipeline extension

**Comment by maikvandergaag** [comment]
Could you share the complete log file? After a run with the system.debug variable set to true

**Comment by Yaseen17** [comment]
Hi @maikvandergaag 

I added this task in my release pipeline. Can you help me where to set system.debug in release pipeline

**Comment by maikvandergaag** [comment]
Just at it as a variable to the pipeline with the value true

**Comment by Yaseen17** [comment]
[extension_debug.txt](https://github.com/maikvandergaag/msft-extensions/files/7510702/extension_debug.txt)

**Comment by Yaseen17** [comment]
@maikvandergaag 

Any idea why it is throwing the error?

**Comment by maikvandergaag** [comment]
@Yaseen17: Yes you are using a internal hosted Azure DevOps instance. It looks like the api version 6.1 is not installed there.

**Comment by maikvandergaag** [comment]
is updated
