### ISSUE TITLE
Returns 'BadRequest' error while publishing a pbix which uses dataset from another dataset (which is already published)

### ISSUE THREAD

**Issue by rsdev-repo** [maikvandergaag/msft-extensions#330]
Hi Maik, 

Need your help here.

The .pbix i am trying to publish doesn't have it's own dataset, rather it's a report which uses another dataset. I used your plug-in to publish the .pbix which contains the actual dataset, which gets successfully deployed to the service. However when i try to publish the second .pbix which refers to the dataset, the task fails with 'BadRequest' error.

2021-11-09T22:28:31.8241975Z Done processing Power BI Actions
2021-11-09T22:28:31.9519979Z ##[error]Operation returned an invalid status code 'BadRequest'
2021-11-09T22:28:32.0050225Z ##[section]Finishing: Power BI Action: Publish

**Comment by maikvandergaag** [comment]
Could you share the complete log with the variable system.debug set to true?

**Comment by rsdev-repo** [comment]
HI Maik,

Thank you so much for your reply. I figured out that the problem was with the pbix which was looking for a dataset to which  the user did not have permission to. All good for now. Thank you. I really like your plugin. Great stuff

Rohith

**Comment by maikvandergaag** [comment]
Great
