### ISSUE TITLE
##[error]Missing an argument for parameter 'CertificateThumbprint'. Specify a parameter of type 'System.String' and try again.

### ISSUE THREAD

**Issue by arnabdasgupta04** [maikvandergaag/msft-extensions#332]
@maikvandergaag  I am getting the below error while using powerBI action
![image](https://user-images.githubusercontent.com/63199431/141119175-d51f59cf-cb2f-4008-a986-707de55a29fd.png)

It is asking for client secret even after providing client secret as shown in the below snapshot.

![image](https://user-images.githubusercontent.com/63199431/141119200-1b3333d8-19b5-4b95-9d16-ab6cd91d2fff.png)

The power Bi action is taking the power BI service connection instead of the v4 one as shown below

![image](https://user-images.githubusercontent.com/63199431/141119208-9ec36d42-96a9-4568-8680-ce56ef780fb3.png)

Kindly please assist me in this issue .

**Comment by maikvandergaag** [comment]
New version of the extension is being build at the moment, will take to about an hour before it is in production.

For the next time please include the log with the system.debug value set to true.

**Comment by arnabdasgupta04** [comment]
@maikvandergaag  Do I need to uninstall and then reinstall again the extension ? Please guide me

**Comment by maikvandergaag** [comment]
It should be updated automatically

**Comment by arnabdasgupta04** [comment]
@maikvandergaag   while using upload powerbi report , it is uploading only the report and dataset but not the dashboard , also I am not getting a separate option for uploading power bi dashboard in it , please assist me.
