### ISSUE TITLE
Power BI Action is showing issues for all the actions

### ISSUE THREAD

**Issue by PoojaKumar2015** [maikvandergaag/msft-extensions#339]
In PowerBI actions all the below actions fail with error "AgentPool\Agent-1\_work\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.16\ps_modules\PowerBI\PowerBI.psm1:1056 char:53"

Actions tried:
Take dataset ownership
Refresh a dataset
Upload Power bI report

**Comment by maikvandergaag** [comment]
Could you share the complete log when you running with the system.debug variable set to true?

**Comment by PoojaKumar2015** [comment]
In last function Function Set-RefreshSchedule there is extra "," in param list. Kindly help on this
[Issue339.zip](https://github.com/maikvandergaag/msft-extensions/files/7529623/Issue339.zip)

**Comment by maikvandergaag** [comment]
Fix is in the pipeline will be deployed in a few moments

**Comment by PoojaKumar2015** [comment]
sure , we are waiting as it is impacting production pipelines . Thanks for your support

**Comment by maikvandergaag** [comment]
Version should be there. Please check and let me know

**Comment by PoojaKumar2015** [comment]
Thanks the issue is resolved

**Comment by maikvandergaag** [comment]
Great, sorry for introducing the error
