### ISSUE TITLE
Error: Operation returned an invalid status code 'Forbidden' (Issue Reopened)

### ISSUE THREAD

**Issue by joaovictormelo42** [maikvandergaag/msft-extensions#342]
Hi @maikvandergaag , like you ask, i got new tests and got the same issue, so a reopen this issue here, the logs are the same of issue #331.
I've set Scope = Individual for UpdateSqlCreds action and still getting Forbidden.
From the logs I see that it is failing [on line 1014](https://github.com/maikvandergaag/msft-extensions/blob/54b21ba0e96417cc403e69bd4ef582386ac9ce2a/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1#L1014) - so I assume that Scope parameter was handled correctly.

If i use other actions, i dont get the error.

**Comment by sergeytrasko** [comment]
Should the Scope be set to Organization if you use service principal? Anyway I'm getting error with both Individual and Organization.

**Comment by maikvandergaag** [comment]
@sergeytrasko: I do not have a clear answer about that as well. That is something built into the PowerShell commands for PowerBI.

I have now rebuilt the component to just use the API's and this is being deployed into the beta environment. If you do not have beta access please share your Azure DevOps organization name

**Comment by sergeytrasko** [comment]
I think we don't have access to beta access.
I'm part of quite big organization and I'm not admin for Azure DevOps - any changes there (like installing new extensions) might take days and weeks due to required paper-work (unfortunately).

**Comment by maikvandergaag** [comment]
Ok, I will check if we can do the tests in another way

Groetjes,

Maik van der Gaag
________________________________
Van: Sergey Trasko ***@***.***>
Verzonden: Tuesday, November 16, 2021 10:32:09 AM
Aan: maikvandergaag/msft-extensions ***@***.***>
CC: Maik van der Gaag ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [maikvandergaag/msft-extensions] Error: Operation returned an invalid status code 'Forbidden' (Issue Reopened) (Issue #342)


I think we don't have access to beta access.
I'm part of quite big organization and I'm not admin for Azure DevOps - any changes there (like installing new extensions) might take days and weeks due to required paper-work (unfortunately).

**Comment by maikvandergaag** [comment]
The update is being published to production as we speak.

**Comment by joaovictormelo42** [comment]
Hi, @maikvandergaag!I think we are moving forward with this new update. In the log the data source credentials have been updated, but some errors occur as follows.

![image](https://user-images.githubusercontent.com/20947225/142618740-b93fd021-700c-4943-8e08-e16e1a7d7c28.png)


You think is better open a new issue to that?

**Comment by maikvandergaag** [comment]
Could you share some more information about the values you are supplying and maybe share the complete log

**Comment by joaovictormelo42** [comment]
Can i send the log directly to you? Because may had some sensitive info about the Workspace, and database.

**Comment by maikvandergaag** [comment]
tuurlijk maik at familie-vandergaag.nl

**Comment by sergeytrasko** [comment]
For me current versions works fine. Many thanks for the fix!

**Comment by joaovictormelo42** [comment]
hi @maikvandergaag , did you receive the e-mail? If i can help with something else.

**Comment by joaovictormelo42** [comment]
Hi @maikvandergaag , sorry to bothering you, if you had any news about the problem please let me note. Thank you so much again to help me on this.

**Comment by maikvandergaag** [comment]
I thought the issue was fixed what problem are you still having
