### ISSUE TITLE
Rebind report fails with error 'Cannot bind argument to parameter 'Name' because it is an empty string'

### ISSUE THREAD

**Issue by rsdev-repo** [maikvandergaag/msft-extensions#344]
Hi Maik,

The rebind report action is failing with above error message. I have attached detailed log for your reference. The reason I want to rebind is that the report is using a shared dataset which otherwise will refer to dataset from the workspace where it was built. Appreciate your help here.
[Rebinndreportdebuglog.txt](https://github.com/maikvandergaag/msft-extensions/files/7570813/Rebinndreportdebuglog.txt)

Regards
Rohith

**Comment by maikvandergaag** [comment]
Fix is beign deployed

**Comment by rsdev-repo** [comment]
Thanks Maik, When is the earliest we can use the fix?

**Comment by maikvandergaag** [comment]
It should be there already

**Comment by rsdev-repo** [comment]
That's really great, i will give a go and let you know. Quick question: Should the report name be with extn .pbix or without?

**Comment by rsdev-repo** [comment]
Thank you so much, it's working fine now. Really appreciate your quick response.
