### ISSUE TITLE
"System.OutOfMemoryException" when uploading large datasets

### ISSUE THREAD

**Issue by thoesk** [maikvandergaag/msft-extensions#346]
Hi,
I get the following a System.OutOfMemoryException when uploading a large dataset.

Dataset size: approx 1.2gb
Power BI premium. 
Azure windows agents used for upload. 

Publishing the same dataset directly from Power BI desktop works fine, confirmed size of 1.2gb in workspace after publishing. See output from "power bi actions" below. Note that the exception happens immediately, seems like the the memory isn't in fact full,  but that we are unable to assign a large enough memory block for the string or similar?

2021-11-25T08:18:02.3231227Z Checking for existing Reports with the name: *removed*
2021-11-25T08:18:02.4779318Z Importing PowerBI File
2021-11-25T08:18:03.6569299Z ##[error]Exception calling "GetString" with "1" argument(s): "Exception of type 'System.OutOfMemoryException' was thrown."

**Comment by maikvandergaag** [comment]
Will try to investigate with what we can do about this

**Comment by maikvandergaag** [comment]
This should work better with the new version
