### ISSUE TITLE
Trigger Pipeline -Passing variables

### ISSUE THREAD

**Issue by nitmatgeo** [maikvandergaag/msft-extensions#347]
Hello @maikvandergaag! 
Hope you are doing well and remember me! Am back requesting a new feature which allows passing of variables from master pipeline to child pipeline _(at the time of triggering)._ First question, is it technically possible? If so, please share your views, if things go well I can work and contribute on this :)

-Nitin

**Comment by maikvandergaag** [comment]
Hi Nitin,

Yes, that should be possible and has been something on my list to work on as well. If enabled this should be very easy to do with the api.

https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-6.0

You have a variables property for example.

Not sure about the build part

**Comment by nitmatgeo** [comment]
@maikvandergaag Let me analyze this, am taking your dish with my fork 😆 Hope to disturb you again.. when I need clarifications/help/guidance 😛

**Comment by maikvandergaag** [comment]
now in production
