### ISSUE TITLE
Power Bi Action : DataRefresh task is refreshing all datasets

### ISSUE THREAD

**Issue by adityaakel** [maikvandergaag/msft-extensions#348]
Power Bi Action : DataRefresh is refreshing all datasets. I am looking for refreshing only single dataset. I provided dataset name in this task but still refreshing all datasets. PFA the task configuration for data refresh. Will this task supports single dataset refresh? If yes, please let me know how to configure this task if the below configuration is wrong

![image](https://user-images.githubusercontent.com/95269211/143989808-878d5af1-64f1-4c20-beda-df8501e4439c.png)

**Comment by maikvandergaag** [comment]
Please update your version you are using version 4 at the moment we have version 5 running
