### ISSUE TITLE
Power BI Action: Publish error- One or more errors occured

### ISSUE THREAD

**Issue by aniruddhanikam** [maikvandergaag/msft-extensions#349]
Hi Sir,

From today only facing this error,before reports were getting deployed to destination workspace. Don't  know what is the issue.everything is same only.I am selecting single pbix file to deploy. Error is also not descriptive.Waiting for your reply as soon as possible
![IMG_20211130_154854](https://user-images.githubusercontent.com/15902576/144029466-0ae043d8-c982-4951-b451-f9e903c450d7.jpg)

**Comment by aniruddhanikam** [comment]
Closed

**Comment by dafzali** [comment]
Hello, may I know how did you fix this issue?

Thanks.
