### ISSUE TITLE
Not able to Select multiple files

### ISSUE THREAD

**Issue by aniruddhanikam** [maikvandergaag/msft-extensions#350]
Hi @maikvandergaag 

How to select multiple source files? I can either select single file or complete folder in Power bi Action extension.

**Comment by maikvandergaag** [comment]
Just perform wild card queries to select multiple files

**Comment by aniruddhanikam** [comment]
@maikvandergaag Sir,

Could you please let me know where and how to use wild card queries in power bi publish extension?
