### ISSUE TITLE
Option to Update App in target workspace on report publish

### ISSUE THREAD

**Issue by roe3p** [maikvandergaag/msft-extensions#353]
Is it possible to add an option in the Upload Power BI Report action that will refresh the Power BI App in the target workspace? According to the Rest API documentation the option is PipelineUpdateAppSettings: https://docs.microsoft.com/en-us/rest/api/power-bi/pipelines/selective-deploy#pipelineupdateappsettings

(Or alternatively a standalone action that will refresh the app independently, though I can't see if that's supported in the API)

**Comment by roe3p** [comment]
Ah, I think I may have made the same error as reported in issue #294 ...

**Comment by maikvandergaag** [comment]
Looks like a great functionality could you maybe support with your idea
