### ISSUE TITLE
Unable to use the variables declared in Variable Group

### ISSUE THREAD

**Issue by RaviChandraMadipadiga** [maikvandergaag/msft-extensions#354]
Hi ,
I have defined my version variable in Variable Group and i am getting the following error. Seems like the task is not taking the variable from the Variable group ?
![image](https://user-images.githubusercontent.com/34366217/145214328-e68cc294-70ff-498c-861e-52847bce99b0.png)

**Comment by maikvandergaag** [comment]
Which extension are you using and could you share a complete log in debug mode?
