### ISSUE TITLE
PBI Action: Update Parameters not working

### ISSUE THREAD

**Issue by c4g-wv** [maikvandergaag/msft-extensions#355]
Hi Maik, we're trying to deploy a pbi report using your tool. First, we publish the report and then we want to update a few parameters in the report. The publish works fine, but the update parameter step doesn't update the parameters. There is no error in the step either. Based on the code in the function "Update-PowerBIDatasetParameter", I'd expect a log entry for this line "`Write-Host "Updated parameters in Dataset- '$($Set.name)'"`", but it's not there, which would indicate it's not getting in the if-statement, which would indicate it can't find the parameter, even though it is there.  If there would be a permission issue, I'd expect an error would be thrown, which is also not the case, so a bit puzzled where the problem could be. Might it be a good idea to also log the output of this line: `$datasetParameters = Get-PowerBiParameters -GroupPath $GroupPath -SetId $setId` ? I don't mind sharing the log, but I'd prefer to do it in a private way, not just publicly in this post.

**Comment by maikvandergaag** [comment]
@c4g-wv: Could you add the system.debug variable and set it to true and then share the log. You can do this via mail: info at msftplayground.com

**Comment by c4g-wv** [comment]
@maikvandergaag : issue was with passing the update parameters json string from our side, wrong structure. Closing this item.
