### ISSUE TITLE
Update All - if null then continue on

### ISSUE THREAD

**Issue by Matte760** [maikvandergaag/msft-extensions#361]
I was wondering if your update all functionality can just iterate to all the reports that it would apply to in a workspace and not to ones that they dont apply to. 

For example, if I want to update a data source to our dev sql server from prod but only want to touch reports that have a specific prod server I want to apply the action to those and just skip the other datasets that it does not apply to. The only other option to do this is to create an action for each dataset and specify the change, but that would take too long as I have many reports in my workspace. 

Thanks!

**Comment by maikvandergaag** [comment]
@Matte760: thank you for your request I would have to look into it. On what specific action would you like this functionality?

**Comment by Matte760** [comment]
> t does not apply to. The only other option to do this is to create an action for each dataset and specify the change, but that would take too long as I have many repo

**Comment by Matte760** [comment]
@maikvandergaag  thanks for your reply mostly looking for this functionality on the "change data source" action 
![image](https://user-images.githubusercontent.com/97559780/149236103-2fcc04e1-0092-4a5c-abe5-96df1af2829b.png)

**Comment by Matte760** [comment]
If I choose the update all datasets options it just errors when one of the reports does not have the sql server connection i am trying to change
![image](https://user-images.githubusercontent.com/97559780/149236439-eca64f72-ee65-4484-86f3-2ccf047c8e96.png)

**Comment by maikvandergaag** [comment]
Could you add the log file when you add the variable system.debug: true to the pipeline
