### ISSUE TITLE
Power BI publish task failing

### ISSUE THREAD

**Issue by cbautistapina** [maikvandergaag/msft-extensions#362]
When i try to run a pipeline i'm getting the below error:

![image](https://user-images.githubusercontent.com/97840217/149665442-f466196e-9ee4-4381-a759-dbc975378792.png)

Actions tried;

-Create folder F:\tmp, the pipeline failed showing error "Access denied to folder F:\tmp"
-Grant full control access to the folder F:\tmp, the pipeline still showing error "Access denied to folder F:\tmp"

**Comment by maikvandergaag** [comment]
Please try f:\tmp\* if there are your files. Otherwise it is something with your agent.

**Comment by cbautistapina** [comment]
Thank you Maik for your quick respond
