### ISSUE TITLE
Getting error 400 when trying to push reports to power BI

### ISSUE THREAD

**Issue by saiudthawar** [maikvandergaag/msft-extensions#363]
I'm getting this error when trying to push report and datasets to PBI. 
2021-12-29T19:14:07.9462561Z ##[error]The remote server returned an error: (400) Bad Request.

**Comment by maikvandergaag** [comment]
Could you share more info

Groetjes,

Maik van der Gaag
________________________________
Van: saiudthawar ***@***.***>
Verzonden: Wednesday, January 19, 2022 4:58:51 PM
Aan: maikvandergaag/msft-extensions ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [maikvandergaag/msft-extensions] Getting error 400 when trying to push reports to power BI (Issue #363)


I'm getting this error when trying to push report and datasets to PBI.
2021-12-29T19:14:07.9462561Z ##[error]The remote server returned an error: (400) Bad Request.

**Comment by saiudthawar** [comment]
I have azure devops ci/cd for pushing report and datasets into powerbi. so when trying to push reports into workspace in powerBi I'm getting error 400.

![image](https://user-images.githubusercontent.com/37854151/150215212-7ee4166f-4df9-40a3-b6e0-1abb43f7054d.png)

**Comment by maikvandergaag** [comment]
What I can see from the logs is that you are trying to publish a file called readme.me. That is not supported
