### ISSUE TITLE
Error while updating SQL credentials : Response status code does not indicate success: 401 (Unauthorized).

### ISSUE THREAD

**Issue by nagu-git** [maikvandergaag/msft-extensions#366]
Hi @maikvandergaag ,

Amazed by your work, ADO tasks were really helpful.

Need your help on a step, while trying to update data source credentials. Facing error response like Unauthorized. 
Added debug log below. please guide to me to proceed further.

 ##[debug]Caught exception from task script.
 ##[debug]Error record:
 ##[debug]Invoke-PowerBIRestMethod : One or more errors occurred.
 ##[debug]At D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1:1060 char:13
 ##[debug]+             Invoke-PowerBIRestMethod -Url $ApiUrl -Method Patch -Body ...
 ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ##[debug]    + CategoryInfo          : WriteError: (Microsoft.Power...werBIRestMethod:InvokePowerBIRestMethod) [Invoke-PowerBIR    estMethod], AggregateException
 ##[debug]    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod
 ##[debug] 
 ##[debug]Script stack trace:
 ##[debug]at Update-BasicSQLDataSourceCredentials, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\ps_modules\PowerBI\PowerBI.psm1: line 1060
 ##[debug]at <ScriptBlock><Process>, D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.28\run.ps1: line 177
 ##[debug]at <ScriptBlock>, <No file>: line 1
 ##[debug]at <ScriptBlock>, <No file>: line 22
 ##[debug]at <ScriptBlock>, <No file>: line 18
 ##[debug]at <ScriptBlock>, <No file>: line 1
 ##[debug]Exception:
 ##[debug]System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
 ##[debug]   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 ##[debug]   at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.<InvokeRestMethod>d__35.MoveNext()
 ##[debug]   --- End of inner exception stack trace ---
 ##[debug]   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 ##[debug]   at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.ExecuteCmdlet()
 ##[debug]   at Microsoft.PowerBI.Commands.Common.PowerBICmdlet.ProcessRecord()
 ##[debug]---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
 ##[debug]   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 ##[debug]   at Microsoft.PowerBI.Commands.Profile.InvokePowerBIRestMethod.<InvokeRestMethod>d__35.MoveNext()<---
 ##[debug]
 ##[error]One or more errors occurred.
 ##[debug]Processed: ##vso[task.logissue type=error]One or more errors occurred.
 ##[debug]Processed: ##vso[task.complete result=Failed]
 ##[section]Finishing: Update SQL credentials

**Comment by mattias-de-coninck** [comment]
@nagu-git please make sure the service principal or service account used to update the credentials is owner of the dataset. This is often the root cause of 401 unauthorized errors.

**Comment by nagu-git** [comment]
Thanks @mattias-de-coninck 

I see Service principal has access to dataset. It fails only on gateway.
Not sure how to provide access to Gateway. Can you please few suggestions.
TIA.

**Comment by nagu-git** [comment]
Hi @mattias-de-coninck.

Finally able to resolve the 401 unauthorized error. 
Added take ownership and this issue solved.

**Comment by kru0207** [comment]
What do you mean by added take ownership?
Did you made any changes in gateway?

**Comment by maikvandergaag** [comment]
There is an action in the extension to take ownership of a report.

**Comment by Pass1406** [comment]
@maikvandergaag pls can you guide where in the extension can i find this ownership of report action..?

**Comment by maikvandergaag** [comment]
It is in the action drop down
