### ISSUE TITLE
Connection closed error

### ISSUE THREAD

**Issue by vaine25** [maikvandergaag/msft-extensions#367]
##[debug]System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
##[debug]   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
##[debug]   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
##[debug]   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[error]The underlying connection was closed: An unexpected error occurred on a send.

**Comment by arcticmonkey0** [comment]
Same thing happening in my pipelines. At first my token got expired, I renewed it and then this error started occurring.
![image](https://user-images.githubusercontent.com/47833491/153631438-8683e36a-2cb6-45c2-93da-dc66d1e347a3.png)

**Comment by arcticmonkey0** [comment]
Seems that new connection creation resolves the issue. At least for me it worked.
