### ISSUE TITLE
The variables can not be found on the definition: , ," when using secret variable

### ISSUE THREAD

**Issue by alexrang83** [maikvandergaag/msft-extensions#369]
I set a variable in the variables tab of the UI like so:
![image](https://user-images.githubusercontent.com/21359967/154485598-2ffb88d9-fff9-4b0a-9da1-df4eed4da3f1.png)

And then reference it in my YAML file here:
![image](https://user-images.githubusercontent.com/21359967/154485667-434ab9c8-9568-4ba9-8fa9-110e324d896b.png)

Yet I still get the "variables can not be found on the definition" error:
![image](https://user-images.githubusercontent.com/21359967/154486280-ec9e3a35-bd2c-45ce-b2d1-74cd40b92116.png)

**Comment by maikvandergaag** [comment]
Hi @alexrang83,

The property "VersionVariable" is referencing the version number. As far as I can see now you haven't specified it. Could you correct this?

**Comment by alexrang83** [comment]
I'm not entirely sure what you are asking, but I do have the VMM variable referenced as a variable at the beginning of my YAML file.

**Comment by maikvandergaag** [comment]
It cannot be an in file variable

**Comment by alexrang83** [comment]
Ok I have moved my variables to be created in the UI like so:
![image](https://user-images.githubusercontent.com/21359967/156253170-0e1004f3-42cd-4942-87ff-20407322dfba.png)

But when I attempt to use them, I still get the same error about "variables can not be found on the definition"

**Comment by maikvandergaag** [comment]
Would you mind trying version 2?

**Comment by alexrang83** [comment]
Same result with version 2
![image](https://user-images.githubusercontent.com/21359967/156360689-4b26a4e9-e19d-4c1e-8072-5260383366cb.png)

**Comment by maikvandergaag** [comment]
@alexrang83: Could you share the logs with system.debug set to true? And would you mind sharing / trying the following:

- What permissions does your PAT have?
- What happens when you use the OAuth autentication method, that is newly build into the extension?

**Comment by alexrang83** [comment]
![image](https://user-images.githubusercontent.com/21359967/156363392-640feef6-416d-4a47-a65b-d7a7a72ef30b.png)
![image](https://user-images.githubusercontent.com/21359967/156363664-3afd5f54-6fc9-4547-8dfc-93731243e6f7.png)
Here are the debugging logs. My PAT has read and manage build permissions. I don't see any documentation on the new OAuth authentication method. Where would I find that?

**Comment by alexrang83** [comment]
I did find the docs on the OAuth option and used it. The same error occurs.

**Comment by maikvandergaag** [comment]
Ok, from your debug log, I see that you do not get a good result from the builds API. This is because the response is HTML and no definition ID added to the next call. Could you try this:

Add the following permissions to your PAT: **Release**: Read, write, execute, & manage

Regarding the OAuth authentication try this: https://msftplayground.com/2022/02/version-number-counter-now-supports-the-build-identity/

**Comment by alexrang83** [comment]
Some extra logs 
![image](https://user-images.githubusercontent.com/21359967/156410561-f55b2eb0-c607-461c-aa97-f6f99fd0b1d5.png)

**Comment by alexrang83** [comment]
After updating to the 2nd version of this task and setting the right permissions in Azure DevOps, I was able to get it working. Thank you.
