### ISSUE TITLE
Release Task Power BI Actions: Update dataSource connection

### ISSUE THREAD

**Issue by developersheat** [maikvandergaag/msft-extensions#370]
Hi I'm trying to update the DataSource Connection (Azure Devops -Release Task Power BI Actions: Update dataSource connection

but I'm getting the same error all the time
Thanks
PD I tested trying to refresh the in a previous step  and I was able to complete the step successfully so I guess there is no an issue related to access to the Dataset 

Error
![Captdure](https://user-images.githubusercontent.com/89402346/154519749-145c846d-7263-4942-b807-35bdaf3b5b40.PNG)
![Cwwwapture](https://user-images.githubusercontent.com/89402346/154519752-e3a70e24-0aa6-4bfd-bab5-442e291573b7.PNG)

Success 

![Captdfdfdfure](https://user-images.githubusercontent.com/89402346/154519053-5a998511-c3b1-451f-b080-e3e17bbb61cc.PNG)
![Captwwwwure](https://user-images.githubusercontent.com/89402346/154519055-7cd99860-b9aa-4f09-801f-940687bcf19d.PNG)
 )

**Comment by maikvandergaag** [comment]
Could you share the logs after a run with the system.debug variable set to true?

**Comment by souvik221** [comment]
I am getting following error while trying to execute update source credentials. Sharing the configuration details and logs below.
![image](https://user-images.githubusercontent.com/33418807/160996785-024f0216-8aa0-468e-b57a-67e2746eb04b.png)
![image](https://user-images.githubusercontent.com/33418807/160997097-64e2f1da-ab4e-4d6c-ad2a-1e7699de661f.png)

**Comment by maikvandergaag** [comment]
Please share the logs with the added varaiable system.debug with the value true

**Comment by souvik221** [comment]
Please find below 
![image](https://user-images.githubusercontent.com/33418807/161002373-12d24777-23a1-413d-95c8-47ee1135f911.png)

**Comment by maikvandergaag** [comment]
Make sure you are suppling the correct info and that the datasource connection is setup correctly
