### ISSUE TITLE
Power BI Actions - Publish Dataset shows "success", but is not in the destination location

### ISSUE THREAD

**Issue by giznaj** [maikvandergaag/msft-extensions#372]
**Describe the issue**
We are running Azure CICD to deploy models (model.bim) to Power BI service.  We are using the plugin to deploy model/dataset and the UI shows successful.  When we navigate to the workspace, the dataset is not there.  So there is a bug in the wrong status coming back, but also, we need to see an example on how to add the "switches" properly.  

**Extension **
 - Power BI Actions 
 - Version: 5

**To Reproduce**
1. Setup the release
2. Trigger the release
3. No error, but a success message

**Expected behavior**
The Dataset (model.bim) file that was made available via the CI, is deployed via the CD.  The CD which holds the Power BI Actions plugin is attemping to deploy a model/dataset to power bi and is failing, but showing as successful.

**Situation (please complete the following information):**

 - Agent type: Azure Host
 - Autentication: Service Principal / App Registration
 - Extension Version: 5

**Log info**
![unnamed](https://user-images.githubusercontent.com/5216071/155378572-c2f33b81-2234-43ac-a1d8-77652a56ed81.png)

**Additional information**
PBI Service Connection : Service Principal account (it works, we can deploy reports and refresh datasets)
Action : upload tabular model
Workspace name: <<private>>
Source file : Path CI artifact (model.bim)
Tabular editor switches : -D provider (power BI) -C -O "MyDataset"

We really need help with the last textbox on your UI.  Can you please provide a meaningful example where you deploy to the Power BI Service?

**Comment by giznaj** [comment]
Here are the logs:

2022-02-24T14:41:01.2975632Z ##[section]Starting: Power BI Action: Publish dataset
2022-02-24T14:41:01.3540640Z ==============================================================================
2022-02-24T14:41:01.3541392Z Task         : Power BI Actions
2022-02-24T14:41:01.3541685Z Description  : Release Task Power BI Actions
2022-02-24T14:41:01.3541923Z Version      : 5.4.28
2022-02-24T14:41:01.3542159Z Author       : Maik van der Gaag
2022-02-24T14:41:01.3542374Z Help         : 
2022-02-24T14:41:01.3545208Z ==============================================================================
2022-02-24T14:41:04.5144963Z Starting Power BI Actions extension
2022-02-24T14:41:04.5640284Z ### Required Module is needed. Importing now...
2022-02-24T14:41:04.9608380Z ### Trying to import the incorporated module for PowerBI
2022-02-24T14:41:39.4713785Z Trying to publish file: D:<<path>>\Model.bim
2022-02-24T14:41:39.5783451Z 
2022-02-24T14:41:39.5835480Z Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                  
2022-02-24T14:41:39.5847829Z -------  ------    -----      -----     ------     --  -- -----------                                                  
2022-02-24T14:41:39.5853597Z      75       5      668       2848       0.05   5744   1 TabularEditor                                                
2022-02-24T14:41:40.5926326Z 
2022-02-24T14:41:40.6268576Z Tabular Editor 2.16.4 (build 2.16.7940.23396)
2022-02-24T14:41:40.6269277Z --------------------------------
2022-02-24T14:41:42.2203280Z Loading model...
2022-02-24T14:41:43.5933640Z Done processing Power BI Actions
2022-02-24T14:41:43.5940672Z Done running Power BI Actions extension.
2022-02-24T14:41:43.5955801Z 
2022-02-24T14:41:43.5956718Z 
2022-02-24T14:41:43.6921853Z ##[section]Finishing: Power BI Action: Publish dataset

**Comment by maikvandergaag** [comment]
Could you add the variable: system.debug and set it to true. Then run the pipeline again and send me the logs.

**Comment by giznaj** [comment]
Yes, I will do that and send them to you.

**Comment by giznaj** [comment]
@maikvandergaag - I will run the release with the same switches as before.  Can you also provide an example of the switches/arguments for publishing a new dataset to the PBI service?

**Comment by giznaj** [comment]
@maikvandergaag - How would you like to receive the logs?

**Comment by giznaj** [comment]
@maikvandergaag - I sent you an email with the logs attached.  Thanks!

**Comment by maikvandergaag** [comment]
@mattias-de-coninck: Could you help with this?

**Comment by mattias-de-coninck** [comment]
@giznaj try something like this
```
-D "Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/{Dataset};User ID=*****;Password=*****;" "{Dataset}" -O -C -P -V -E -W
```

Of course you have to replace the _{Dataset}_ with your own datasets and provide credentials as well.

**Comment by giznaj** [comment]
@mattias-de-coninck Thanks for getting back to me.  I just want to make sure about the credentials.  What credentials need to be passed?  This extension requires you connect to the PBI service either two ways.  We have done so using the App Reg/SP method.  

What other credentials are needed?

**Comment by giznaj** [comment]
If I leave the user/pass out of the connection string, I get the following error (I know you didn't say to do this, but the error helps)

(no user/pass in connection string)
2022-03-08T16:10:43.3685792Z ##[error]Deployment failed! Authentication failed: User ID and Password are required when user interface is not available.

(user/pass provided in connection string.  I tried my MS account and the SP/App reg.)
2022-03-08T16:04:22.6563798Z ##[error]Deployment failed! Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.

If I run a release that "refreshes a dataset" using the creds above, it works.  I'm not sure what else to do here.

**Comment by maikvandergaag** [comment]
@giznaj: Not completely sure but I think there is a problem regarding the authentication because the Tabular Editor is a separate tool. 

When using the username password authentication methods is used we could use those credentials but I'm not sure if the Tabular Editor support SPN @mattias-de-coninck: do you know that.

And could also specify how you have now run the extension?

**Comment by mattias-de-coninck** [comment]
@giznaj the authentication for Tabular Editor is indeed decoupled from the linked service established when first running Power BI Actions. In order to make use of a spn be sure to fill in the credentials in the connection string as follows:

```
User ID=app:<APPLICATION ID>@<TENANT ID>;Password=<APPLICATION KEY>;
```

**Comment by maikvandergaag** [comment]
@mattias-de-coninck: So, if I understand you correctly, this would be something we could build in as well. So that the users would not have to enter the creds again.

@giznaj: If possible, we will look at an option to build this in.

**Comment by mattias-de-coninck** [comment]
@maikvandergaag If we are able to fetch the credentials via the linked service I think we should be able to for sure. I will try to take a look at this in the future.

**Comment by giznaj** [comment]
You guys are great and have been very supportive and helpful!  I will try that syntax now and let you know.  I also believe you will be able to re-use or acquire the token from above.  We are able to do this in Azure automation scripts/Runbooks (power shell).

Thanks again so much and stay tuned!

**Comment by giznaj** [comment]
I will deploy via tabular editor and run filddler in the background.  Maybe I'll be able to see something meaningful and the exchange.  I'll keep you posted.

**Comment by maikvandergaag** [comment]
You will have to fill in the credentials offcourse. We will have to make a change to get the underlying creda for now you will have to supply them yourself

**Comment by giznaj** [comment]
Oh, you think the variable is causing the issue?  You are only seeing those because of the copy and paste.  During execution, those variables have the actual values "enjected" at runtime.

**Comment by giznaj** [comment]
> I will deploy via tabular editor and run filddler in the background. Maybe I'll be able to see something meaningful and the exchange. I'll keep you posted.

I deploy using the GUI tool often.  You authenticate in the tool and don't enter any of the creds in the app/publish wizard boxes/screens.  I still might be able to capture the proper syntax that is passed (when mimicing the cli)

**Comment by giznaj** [comment]
I can successfully deploy to the Power BI service usinng the desktop version of tabular editor (we've been doing this for 2 years now).  The authentication is Windows Based (Microsoft AD/Azure AD).  Once that MS prompt is satisfied, you can deploy the Power BI dataset to the power bi workspace.

If I use the extension again for testing, there is no combination of switches, params and options (as specified above) that I can enter to successfully deploy to the Power BI service.  I've tried all combinations above with the SP creds and my MS Windows creds (same as desktop gui tabular editor).

Are you both able to deploy with your extension?  Does anyone have a successful use-case example?

**Comment by giznaj** [comment]
Ok, thanks @maikvandergaag 
In the meantime, I have now got it working using another similar extension.  This extension piggy-backs the spn connection established during the start.  It has other options for authentication.  The extension is called "Azure Analysis Service" and is on VS Marketplace.  Thanks for your help in this.

When your extension is updated, I would be keen on testing it with you.  
Thanks again and have a great day!

**Comment by alexschindler** [comment]
I face exactly the same problem: the Azure DevOps pipeline continues before the TabularEditor has properly deployed the model.
To me it seems that the PBI action just does not wait until the Tabular model is properly deployed.
Can the issue be reopened if the problem persists?

I had the same problem when I use the command line to publish with TabularEditor in an Azure DevOps pipeline: the task continues before the TabularEditor is done deploying. I solved it by the hacky workaround of adding [1] after the TabularEditor command.

[1] Start-Sleep -Seconds 60
