### ISSUE TITLE
Version Number Counter - 404 Error on TFS URI

### ISSUE THREAD

**Issue by jmeaster30** [maikvandergaag/msft-extensions#374]
When I try to use the Version Number Counter task in my release pipeline, I get a 404 error when the task does its first GET request to the Azure DevOps REST API. 

The URI it uses is from the SYSTEM_TEAMFOUNDATIONSERVERURI which for me looks like `https://vsrm.dev.azure.com/<org name>/`

I tried to query the full endpoint using that URI `https://vsrm.dev.azure.com/<org name>/<project name>/_apis/build/builds/172?api-version=4.1` and like the error I got in the pipeline, I got a 404 error. I tried to see what happened with different URIs and there is the SYSTEM_TEAMFOUNDATIONCOLLECTIONURI which for me looks like `https://dev.azure.com/<org name>/`. So, I tried querying the endpoint from before but only removing the "vsrm." part and I actually got a proper response.

I made a fork and added an option so you can add a custom URI to use but I was also thinking about just making it a boolean flag to mark if you want to use the TFS URI versus the collections URI.  However, I wasn't sure if I was just doing something wrong, so I figured I would check here first before I make the pull request.

Here are screenshots of the error and the options I am using in the task:
![Screenshot 2022-02-25 141541](https://user-images.githubusercontent.com/14133582/155775693-95ab9e5e-79dd-4d68-a31b-b8b592c92d71.png)
![Screenshot 2022-02-25 142406_LI](https://user-images.githubusercontent.com/14133582/155783170-cd4bf76f-3924-465b-bde3-d394d9449969.jpg)

**Comment by maikvandergaag** [comment]
@jmeaster30 could you also share the logs for more insights?

Please send it when you did a run with the system.debug variable set to true

**Comment by jmeaster30** [comment]
@maikvandergaag Sorry yeah I forgot to cover all of the names that I don't think I can share.

I'll run it again with that system.debug variable set

**Comment by jmeaster30** [comment]
@maikvandergaag Here is the debug log

![Screenshot 2022-02-25 151950](https://user-images.githubusercontent.com/14133582/155795198-4aab0108-6285-441b-a452-b100c63c726c.png)

**Comment by maikvandergaag** [comment]
@jmeaster30 I just published a new version that should also include this fix.
