### ISSUE TITLE
Trigger Pipeline script throws error - when you Input "STAGE" parameter

### ISSUE THREAD

**Issue by ab1234567** [maikvandergaag/msft-extensions#376]
**Describe the issue**

Trigger Pipeline script throws an error - when you Input "STAGE" parameter.

**To Reproduce**

Goto - https://github.com/maikvandergaag/msft-extensions/blob/main/azuredevops/triggerpipeline-new/triggerpipeline/run-release.ps1

**Input -   [Parameter(Mandatory = $false)][String]$Stage = "DEV" ,**

And run the script, and it throws - **ConvertFrom-Json : Invalid JSON primitive: Page.**

**The Input -      [Parameter(Mandatory = $false)][String]$Stage, -- works with no issues by triggering to a default stage.** 

Thanks,

**Comment by maikvandergaag** [comment]
Could you share the logs?

**Comment by ab1234567** [comment]
Hey Maik, 

Its pretty simple - Just add a specific stage to "trigger release pipeline" script - like below 

[CmdletBinding()]
Param (
    [String]$OrganizationUrl ="https://dev.azure.com/xyz",
    [String]$ReleaseUrl = "https://vsrm.dev.azure.com/xyz",
    [String]$AzureDevOpsProjectName = "Agile-Test",
    [String]$DevOpsPAT = "Key",
    [Parameter(Mandatory = $false)][Bool]$UseSystemAccessToken,
    [String]$PipelineName = "CT",
    [Parameter(Mandatory = $false)][String]$BuildNumber,
    **[Parameter(Mandatory = $false)][String]$Stage = "DEV",**
    [Parameter(Mandatory = $false)][String]$Description = "Automatically triggered release"
)

**Errors out --** 
![image](https://user-images.githubusercontent.com/11134030/156442848-3a7c5712-10a0-468b-a9bb-05dfbfffcab7.png)

**With out stage - it works fine,** 

[CmdletBinding()]
Param (
    [String]$OrganizationUrl ="https://dev.azure.com/xyz",
    [String]$ReleaseUrl = "https://vsrm.dev.azure.com/xyz",
    [String]$AzureDevOpsProjectName = "Agile-Test",
    [String]$DevOpsPAT = "Key",
    [Parameter(Mandatory = $false)][Bool]$UseSystemAccessToken,
    [String]$PipelineName = "CT",
    [Parameter(Mandatory = $false)][String]$BuildNumber,
    **[Parameter(Mandatory = $false)][String]$Stage,**
    [Parameter(Mandatory = $false)][String]$Description = "Automatically triggered release"
)

Maybe, have to look if the stage is getting rightly filtered out. ??

**Comment by maikvandergaag** [comment]
@ab1234567 : I get your point. But to really see the issue you should be able to share the logs. I have looked into my demo environment and my test case still works.

The additional info would be helpful to check your case. Could you share the below info:
- Logs with the variable system.debug set to true.
- Image of your release
- Can you start that specific stage by using the UI?

**Comment by ab1234567** [comment]
@maikvandergaag  Sorry for not getting back to you on this. To replicate this issue in the UI.

Assume that your target stage has 2 Stages - DEV & QA with no pre-approvals 

And on the source pipeline - in the stages section input - "QA" (only) and trigger the source pipeline. And the problem is - 

IT QUEUES - BOTH DEV & QA STAGES. 

Is it working in your scenario?

**Comment by bigsem89** [comment]
doesn't work for me alse

**Comment by maikvandergaag** [comment]
Please share more info
