### ISSUE TITLE
Trigger an automated test cases after execute release pipeline

### ISSUE THREAD

**Issue by dadiaz18** [maikvandergaag/msft-extensions#377]
**For which extension would you like to add a feature request?**
Trigger Azure DevOps Pipeline

**Question**
I have two repositories (See the structure below)

> Organization A

     Project A 
          Repo A  (Front End Repository with React)
     Project B 
          Repo B  (Automated Test Cases)

After the creation of a new release in the QA environment using release-pipeline for Project A - Repo A, I need to trigger automated test cases (Project B - Repo B), both in the same organization within Azure DevOps.
Is it possible to use this extension for this purpose?

**Comment by maikvandergaag** [comment]
Yes that should work

**Comment by dadiaz18** [comment]
Can I use this extension without having an API created?

**Comment by maikvandergaag** [comment]
Yes

**Comment by dadiaz18** [comment]
When I try I receive these errors I can not use this extension.

![to upload](https://user-images.githubusercontent.com/43753695/157499528-e47b86c9-afb0-4093-b3c2-19379611ef21.png)
![2022-03-09 13_22_46-candidate-web qa - Release-187 - Pipelines](https://user-images.githubusercontent.com/43753695/157499614-eec45179-c6c4-436e-a0e1-68db16836872.png)

**Comment by maikvandergaag** [comment]
You receive this error because you are using a Linux based agent. If you use a windows one it should work

**Comment by dadiaz18** [comment]
Ok, I will try it. Thanks for the quick response!
