### ISSUE TITLE
Can we edit the REST API version?

### ISSUE THREAD

**Issue by Gautham13** [maikvandergaag/msft-extensions#378]
**For which extension would you like to add a feature request?**
Trigger Azure DevOps Pipeline

**Question**
I want to use this extension to trigger pipeline in my organization which is hosted in an server and supports REST API version only till 5.1

After installing this extension and tried to execute the agent job, I am facing below error:
##[error]The requested REST API version of 7.1 is out of range for this server. The latest REST API version this server supports is 5.1.

Does this mean the request from this extension is REST API version 7.1 ?
Is there a possibility that this version can be changed to lower version, ex: 5.1 
![Error](https://user-images.githubusercontent.com/94442983/156583509-b7466dc1-db85-4818-8de6-f56d39372165.JPG)
?

**Comment by maikvandergaag** [comment]
Good point we have just updated the version will check if we can add this option

**Comment by Gautham13** [comment]
> Good point we have just updated the version will check if we can add this option

Thanks for addressing my last query . Just wanted to check if any solution has been implemented for changing REST API version?

**Comment by maikvandergaag** [comment]
@Gautham13: Yes was working on the extension. It should be there in the next 15 min. Released a new version where you selectively can choose the API version. It defaults to 6.
