### ISSUE TITLE
Error Publishing Reports Power BI Actions

### ISSUE THREAD

**Issue by Keag1Jordan** [maikvandergaag/msft-extensions#379]
Please can you assist with me Power BI Actions

I have set up my release the way all guides do. I have selected a specific report and not a whole directory.
I get the following error when trying to deploy and I am not sure where to look to fix the issue:

##[error]Cannot bind argument to parameter 'CertificateThumbprint' because it is an empty string.
![image](https://user-images.githubusercontent.com/101187032/157235618-0865f5bc-a060-40cd-803c-1cc0686c8fac.png)

Your assistance would be most appreciated.

Kind Regards 

Keagan

**Comment by maikvandergaag** [comment]
I think the problem is with your service connection. Please check the configuration

**Comment by Keag1Jordan** [comment]
Thank you for your quick response I will have a look

**Comment by biswameet-007** [comment]
@Keag1Jordan  did you check out what's wrong? I am facing the same issue now.
