### ISSUE TITLE
Power BI Actions - Can the extension be working for Impala ODBC connections as another option for data source updation.

### ISSUE THREAD

**Issue by shivamshukla** [maikvandergaag/msft-extensions#381]
**For which extension would you like to add a feature request?** for Power BI Actions

**Is your feature request related to a problem? Please describe.** we have ODBC connection to our Power BI and we are not able to use this Extension to update the data source connections because available options are SQL, Analysis Service, SharePoint and Odata.

**Describe the solution you'd like**
If the ODBC connection becomes available, then our Power Bi CICD would be completely automated.

**Describe alternatives you've considered**
We have not found any other solution till now, which come close to this extension.

**Additional context**

**Comment by Ruchi-119** [comment]
Can we add azure synapse analytics dedicated SQL pool as a data source
