### ISSUE TITLE
Issue when selecting Project and Build definition fields in Trigger AzureDevOps Pipeline Task

### ISSUE THREAD

**Issue by leandrohinz** [maikvandergaag/msft-extensions#382]
Hi Maik, can you help me with this?, i added the task Trigger Pipeline because i need to trigger a build pipeline in a task of a release pipeline in one of my projects, i was able to create the service connection 
![image](https://user-images.githubusercontent.com/91966964/158284134-ad05a1c5-67cb-4098-9e4e-06077a1cdf99.png)
for the service connection i was able to create the PAT without problems,
But when i tried to select the Project and Build Definition fields it not show anything in the dropdown list:
![image](https://user-images.githubusercontent.com/91966964/158284658-1c37111d-4000-40fb-af14-c2a806e573cc.png)
![image](https://user-images.githubusercontent.com/91966964/158284748-892b80cc-626e-4780-9522-48f3ac77398b.png)
Can you please help me out with this?
Heres the service connection settings:
![image](https://user-images.githubusercontent.com/91966964/158284895-4d2ba8cc-5cbf-42cf-aba2-38890dbf60f9.png)

If i hardcode the project name, the build definition and the branch i got this error:  (##[error]The remote server returned an error: (401) Unauthorized)
![image](https://user-images.githubusercontent.com/91966964/158286940-e99ae7fb-325b-420e-b0b1-abc8d157ae43.png)

**Comment by maikvandergaag** [comment]
What permissions did you give the pat

**Comment by leandrohinz** [comment]
Exactly, i mean i got a "master pipeline" that triggers another build pipelines, one of them is called "claims party policy configurations" and that build got a variable called environmentArtifact, and that value is setteable at queue time, so if i want to build to QA i changed that value before the build and when the build ends it triggers the CD to the QA stage, so how can i ´pass´ this environmentArtifact value from my "master pipeline" in the task azure trigger to the build (like you do when you "pass" the branch 
![image](https://user-images.githubusercontent.com/91966964/159557948-542906bf-3e64-40f7-874b-7ae75b2f63f4.png)

**Comment by maikvandergaag** [comment]
I get your question variable setting isn't supported at the moment. Will try to look at that this week.

**Comment by leandrohinz** [comment]
Great Maik, i'll stay tuned.

**Comment by maikvandergaag** [comment]
Yes, I almost have a beta version ready. Would you like to beta test ? If yes could you send your organization name?

**Comment by leandrohinz** [comment]
Of course maik, its https://oms-fort.visualstudio.com/ thank you in advance!

**Comment by maikvandergaag** [comment]
new extension version is beign published at the moment.
