### ISSUE TITLE
The import was not successful for import ID 'e0990860-2f\958-47e4-9aee-1cc1307e40d2', report name 'Broker Communications Report Confidential'. The import state was 'Failed'

### ISSUE THREAD

**Issue by omptech** [maikvandergaag/msft-extensions#383]

**Comment by omptech** [comment]
![image](https://user-images.githubusercontent.com/55268151/158604336-a66b4fa0-2eba-49d1-94c1-ea5bb8de6191.png)

**Comment by maikvandergaag** [comment]
Could you supply more information as requested in the template? We really need the system.debug logs to check what is going wrong.
