### ISSUE TITLE
BUG - Update SQL Credentials 

### ISSUE THREAD

**Issue by gabrissk** [maikvandergaag/msft-extensions#385]
**Describe the issue**
There's a bug in the "Update-BasicSQLDataSourceCredentials" function. When it checks if the data source is of SQL type, it's actually assigning the SQL type to the datasource.

**Extension**
 - Extension: Power BI Actions
 - Version: 5

**Additional information**
As you can see below, instead of a comparison, it's doing an assignment:

![image](https://user-images.githubusercontent.com/28660199/158667766-31d91d33-d462-472e-ab0f-b4535467a243.png)

I believe the right code should be 

if ($dataSource.DatasourceType -eq "Sql").

**Comment by maikvandergaag** [comment]
thanks for pointing that out. Will be deployed in a couple of hours

**Comment by gabrissk** [comment]
Thanks!!
