### ISSUE TITLE
Triggering Automated Test Cases Release within Release Pipeline (Website)

### ISSUE THREAD

**Issue by lambat** [maikvandergaag/msft-extensions#386]
Hi,

I am trying to trigger my automated test cases (Selenium) pipeline within our release pipeline for our website. This is so that once the website has been released, we can then trigger our test cases to run. The only reason I am doing it this way is because our release pipeline for the website uses a different build agent to the automated test cases pipeline otherwise it would have been straight forward.

So far, using the guide here: https://msftplayground.com/2019/02/trigger-a-pipeline-from-an-azure-devops-pipeline/?unapproved=326415&moderation-hash=4704ea70b8cfb6270760c57a38340e3a#comment-326415 .....  I can only see my build artifacts and nothing from my release ones:

Build:

![image](https://user-images.githubusercontent.com/16940182/159452784-603e3aa2-ce36-40b6-8b2c-daa3a85cf246.png)

Release:

![image](https://user-images.githubusercontent.com/16940182/159452893-ebb94105-d415-4935-9e84-6d1f88872c8a.png)

It says no results found.

Your help is greatly appreciated.

Thanks in advance.

**Comment by maikvandergaag** [comment]
What is the pat configuration

**Comment by lambat** [comment]
> What is the pat configuration

![image](https://user-images.githubusercontent.com/16940182/159454008-301dda47-cb90-49b5-ac19-16c97c3c830c.png)

Had to scribble out my company name but its the organization name

**Comment by maikvandergaag** [comment]
And what are the permissions of the pat

**Comment by lambat** [comment]
> And what are the permissions of the pat

![image](https://user-images.githubusercontent.com/16940182/159454958-3f147065-4f25-4ed5-999f-249a79151879.png)

**Comment by maikvandergaag** [comment]
Release API should be:  https://vsrm.dev.azure.com/[organization name]

**Comment by lambat** [comment]
> Release API should be: [https://vsrm.dev.azure.com/[organization](https://vsrm.dev.azure.com/%5Borganization) name]

I have tried this according to your guide and if i use that, then i can't see any of the build or release definitions

**Comment by maikvandergaag** [comment]
but could you configure it that way, and look with the edge developer tool or the chrome version. This should show a UI error if there is one

**Comment by lambat** [comment]
> but could you configure it that way, and look with the edge developer tool or the chrome version. This should show a UI error if there is one

Getting a 404 error. I think it's because we currently use the Legacy format like so:

![image](https://user-images.githubusercontent.com/16940182/159461376-a3ac1492-98c4-4311-b89d-1165456c544c.png)

**Comment by lambat** [comment]
> Release API should be: [https://vsrm.dev.azure.com/[organization](https://vsrm.dev.azure.com/%5Borganization) name]

I just tried this again and its now working! no idea how but I can suddenly see my release pipelines!! thank you so much
