### ISSUE TITLE
The action task "Update SqlCreds" runs successfully but does not update the credential after deployment

### ISSUE THREAD

**Issue by mig-sre** [maikvandergaag/msft-extensions#389]
**For which extension would you like to add a feature request?**

Power BI Action: UpdateSqlCreds
Action : Update SQL credentials

**Question**

Hello Maik, 

I am trying to update the user for one of my datasets that connects to Snowflake, I am using the action to update SQL credentials but is not reflecting any change even though the deployment task does not show any error during deployment on my CD process.

Is this action compatible with the connections to Snowflake?

Is there any way to pass this connection string and update the dataset?

thank you,

**Comment by maikvandergaag** [comment]
No sorry that action is not compatible with connections to snowflake
