### ISSUE TITLE
Power BI Actions-Create Workspace Step Fails in Azure DevOps 

### ISSUE THREAD

**Issue by NV2601** [maikvandergaag/msft-extensions#390]
I keep getting this error I try creating a Build Pipeline using Service Connection details where i provide - 

##Error - ResponseBody: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '***' was not found in the directory 'Org_Name'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

![Service Connection](https://user-images.githubusercontent.com/103122809/161990755-808528b4-f093-4db8-9c61-0f1284b75014.PNG)

**Comment by NV2601** [comment]
I have been able to resolve the issue- But my next issue is that as this has succeeded and i can see Workspace is created in logs. But when i go to Power BI App, i dont see this auto created Workspace in the list of workspaces. 

Can you let me know where we are going wrong ?

**Comment by maikvandergaag** [comment]
If you do not see the workspace you do not have permissions you will also have to add your self as a user.
