### ISSUE TITLE
Incorrect TLS algorithm causes a publish failure

### ISSUE THREAD

**Issue by amaslar11** [maikvandergaag/msft-extensions#397]
I am unable to publish a report to the cloud with PowerBIActions without making an edit to the powershell script. When I change the powershell to hardcode it to TLS 1.2 everything works. 

I place the following line in run.ps1 and it works:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

The problem returns if there is an extension update because this change will be blown away. Is there a way of disabling updates, or perhaps this can become a setting, or perhaps we can default it to a higher TLS?

**Extension **
 - Extension: PowerBIActions
 - Version: 5.4.31

**To Reproduce**
Try to publish a report with PowerBIActions from behind a firewall where only TLS1.2 is allowed

**Expected behavior**
Success

**Log info**
Attached two log files. Failure is what i see without making the TLS change to 1.2 and the other is Success with the change to TLS 1.2
[Success.zip](https://github.com/maikvandergaag/msft-extensions/files/8556102/Success.zip)
[Failure.zip](https://github.com/maikvandergaag/msft-extensions/files/8556103/Failure.zip)

**Comment by maikvandergaag** [comment]
updated the extension will be published in 30 min
