### ISSUE TITLE
How to use "Pipeline" - Build  Pipelines / Releases

### ISSUE THREAD

**Issue by DerekLedbetter** [maikvandergaag/msft-extensions#398]
**Describe the issue**
Have had several errors when trying to use the same technique as "Pipeline" for CI.  CD is not working.

**Extension **
Power BI Action: Publish
Publisher - Maik van der Gaag
Installed version - 5.4.31 (Latest)
Last updated - Mar 28, 2022 at 3:05 AM EDT

**To Reproduce**
Building a new pipeline (Release) section.
Create Release
Deploy - and the "TEST/PROD" versions are not loading into the workspace(s).

Pipelines works!  
Releases does not.

**Expected behavior**
Expected this to push to TEST/PROD as the stages are layed out.

**Situation (please complete the following information):**

 - Agent type:   Release
 - Authentication:  "Service Connection"
 - Extension Version: 

**Log info**
Attached.

[2022-04-27_Log.txt](https://github.com/maikvandergaag/msft-extensions/files/8571621/2022-04-27_Log.txt)

**Additional information**
![2022-04-27_2](https://user-images.githubusercontent.com/40179723/165508293-33ba2358-9f83-459d-9572-cee1a5ce8984.png)
![2022-04-27_3](https://user-images.githubusercontent.com/40179723/165508322-6d9f5596-1708-4ee6-b874-755b73e56ed2.png)
![2022-04-27_1](https://user-images.githubusercontent.com/40179723/165508408-9674e539-4da3-41c2-bc76-d742733f5b83.png)

**Comment by maikvandergaag** [comment]
Hi @DerekLedbetter,

As the Source file isn't correct the extension is not finding any files. This property should point to the powerbi file / files you can use wild card inclusing for example *.pbix

**Comment by DerekLedbetter** [comment]
Hi @maikvandergaag ,

thanks for replying.  I tried changing it and it worked.  However, nothing updated.

THE CI is working great.  We built 3 pipelines.  However, according to Microsoft, one is supposed to be build for "DEV", the CD (Release) is built for TEST/ PROD.

Attached are the logs as I saw no change in the RELEASE version.

in TEST - Source - $(System.DefaultWorkingDirectory)/*.pbix - However, nothing moved.

[ReleaseLogs_14 (1).zip](https://github.com/maikvandergaag/msft-extensions/files/8583558/ReleaseLogs_14.1.zip)

**Comment by maikvandergaag** [comment]
The stage is still not finding reports. Please make sure that you set it up correctly. The output should show the reports it is working on. If you share a log file please also make sure you send one when the system.debug variable is set to true

**Comment by maikvandergaag** [comment]
Any update on your issue

**Comment by DerekLedbetter** [comment]
I can’t figure out how to get the “extension” to work with the “Release pipeline”.  It is working GREAT with the Pipelines!

Please send a sample if possible so I can resolve this quickly.

***@***.***

***@***.***

Should the source be the “source artifact”?



From: Maik van der Gaag ***@***.***>
Sent: Monday, May 9, 2022 7:45 AM
To: maikvandergaag/msft-extensions ***@***.***>
Cc: Ledbetter, Derek ***@***.***>; Mention ***@***.***>
Subject: [External Email]Re: [maikvandergaag/msft-extensions] How to use "Pipeline" - Build Pipelines / Releases (Issue #398)


Any update on your issue

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1-voSvMHYHhR0bdTzzZNK4xlpWeEPucuCz49D-ji1upQ8oyzuNpC7BCD7hUHzkOSlxBoFoovgoQxJKrruRO8NOW2d4wdECJW_0mfbpbm8oOeQu-xBS68nnTnFlC32GIGtYoantzsRyJOWqFt3cZP9dQbJ1iUj86mA7fHYSSWmxMnsTsB6t-VIzei_lS4pU7PGClYJh638Fbzj9zYYV5sHOwrr7K9-30zoSMDvscTvHkC1x63PmSBFih2y57G7yLOuPvBJ1jVYGO0Lxyr_EG3pPL74AQC6gu8tGz2lF5D3tf06j3wFz7LJSxi6OgwrMdn342laGzz-Om9iAJ8Lf2OxZQu3qEr6mWwHcnxDXHUAOlNjLD5pIkWSuqi_YMd_Q2cTt7c_mY_nfncAEzXrn2QbcA/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398%23issuecomment-1120993523>, or unsubscribe<https://secure-web.cisco.com/1VFRfhiiZbKMNuqVuMF_arWUoZ9j-e3p4dFUbk2gEQd_OW0akODZXkvNWGV1Eja0J4FCOa0Dfq8z_FT24DxTEtYSIibdZU2lW3e_FnMMV-r2YuvWVZjnHOAsX_u3JxwE0xCvJOIqDsUfmi8_LnbamIuaDw7k7MYOQKJmDhOFEs9gFOAPQbtgYxAaXVrDSgA68Fg_OPAo6YXor13rKDanovxZhNpzSbwx8wpkJxe8tTVRsIVfOi00V5jyTj-jPR4cyh4rH8aHiRuKMRWmDLfEb86fv8FelHL7hQ_wbZi_2PdCLCfp-qD2LnLrTdlxJiFYpHNZYsccsTRJofDn0gV6wU0vwMvUo_oia5W5W18xmSeImKm8ioymVs3oiU1lDMqzdlwpZnzsv_y98GA_klyw5yA/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJSRQC6S4CIUC6TCW77NEGTVJD3D5ANCNFSM5UO22L2A>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


NOTICE: This message may contain confidential information intended only for the recipient.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer.

**Comment by DerekLedbetter** [comment]
doesn’t matter what I put, same error.

***@***.***



From: Maik van der Gaag ***@***.***>
Sent: Monday, May 9, 2022 7:45 AM
To: maikvandergaag/msft-extensions ***@***.***>
Cc: Ledbetter, Derek ***@***.***>; Mention ***@***.***>
Subject: [External Email]Re: [maikvandergaag/msft-extensions] How to use "Pipeline" - Build Pipelines / Releases (Issue #398)


Any update on your issue

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1-voSvMHYHhR0bdTzzZNK4xlpWeEPucuCz49D-ji1upQ8oyzuNpC7BCD7hUHzkOSlxBoFoovgoQxJKrruRO8NOW2d4wdECJW_0mfbpbm8oOeQu-xBS68nnTnFlC32GIGtYoantzsRyJOWqFt3cZP9dQbJ1iUj86mA7fHYSSWmxMnsTsB6t-VIzei_lS4pU7PGClYJh638Fbzj9zYYV5sHOwrr7K9-30zoSMDvscTvHkC1x63PmSBFih2y57G7yLOuPvBJ1jVYGO0Lxyr_EG3pPL74AQC6gu8tGz2lF5D3tf06j3wFz7LJSxi6OgwrMdn342laGzz-Om9iAJ8Lf2OxZQu3qEr6mWwHcnxDXHUAOlNjLD5pIkWSuqi_YMd_Q2cTt7c_mY_nfncAEzXrn2QbcA/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398%23issuecomment-1120993523>, or unsubscribe<https://secure-web.cisco.com/1VFRfhiiZbKMNuqVuMF_arWUoZ9j-e3p4dFUbk2gEQd_OW0akODZXkvNWGV1Eja0J4FCOa0Dfq8z_FT24DxTEtYSIibdZU2lW3e_FnMMV-r2YuvWVZjnHOAsX_u3JxwE0xCvJOIqDsUfmi8_LnbamIuaDw7k7MYOQKJmDhOFEs9gFOAPQbtgYxAaXVrDSgA68Fg_OPAo6YXor13rKDanovxZhNpzSbwx8wpkJxe8tTVRsIVfOi00V5jyTj-jPR4cyh4rH8aHiRuKMRWmDLfEb86fv8FelHL7hQ_wbZi_2PdCLCfp-qD2LnLrTdlxJiFYpHNZYsccsTRJofDn0gV6wU0vwMvUo_oia5W5W18xmSeImKm8ioymVs3oiU1lDMqzdlwpZnzsv_y98GA_klyw5yA/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJSRQC6S4CIUC6TCW77NEGTVJD3D5ANCNFSM5UO22L2A>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


NOTICE: This message may contain confidential information intended only for the recipient.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer.

**Comment by maikvandergaag** [comment]
Source path should be linked to a file. I'm not aware what your file structure is within your pipeline

**Comment by maikvandergaag** [comment]
$(System.DefaultWorkingDirectory) refers to the file system of your repo. The source file it self should point to one or more pbix files.

**Comment by DerekLedbetter** [comment]
I've tried this many times and getting the same error.

Please assist.





From: Maik van der Gaag ***@***.***>
Sent: Monday, May 16, 2022 4:22 AM
To: maikvandergaag/msft-extensions ***@***.***>
Cc: Ledbetter, Derek ***@***.***>; Mention ***@***.***>
Subject: [External Email]Re: [maikvandergaag/msft-extensions] How to use "Pipeline" - Build Pipelines / Releases (Issue #398)


$(System.DefaultWorkingDirectory) refers to the file system of your repo. The source file it self should point to one or more pbix files.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1T4AoJkuXa_ey9qhyyQt4_e1hkQ8R1Ehx4B4K8nMmNuOHZS_Cr2hhVh408poy17ZXNFHeAl-ZWbqK9nUOH0bJInAK32EkYV8TR60Pxu7bFYoxDQLzqqrs6b0GYwpoeM_k6L7A5ygt9EpAFE62AhTJhsm_HAjazQDCbK1RRwHI2h6V4TG9Cwfy8xCfoYdFq013laNTmUdAZVtJHrFooQALKZon_3Lfx3kitAIbZTvBTGyPJzYrVrjRFTnM9V-v9nlQd9tLhP30bMjv9ocSgWOzlzL12wIQ9VxfHBiqm8RGXPGtb1_kPVekAW135yfy9ngRPk74vJBdtD5u8_jnqu7AX92uWozj3ClkdPdH5HitIOVBiyZPirRwZAg75LoktrvB5x4o8Qo3_A5YpeyayuMZbA/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398%23issuecomment-1127375104>, or unsubscribe<https://secure-web.cisco.com/1H1xd4xu_Vu98CArblo_CxvLaXkp3TVUvS7hKA00p6PZuHHcWlJ-J2IeeWMTh1b1dqeb4FMUYJi-mFe8fbZ8kh5SRJ0pfTtxhBnVvVxdDNyZ-z1BA3gKnEp94TXDyuCG1A-eOtJsK8RyPZrDb6YqPVJeR4MAWzZwNFZ9JWv9rIuMIF_4D0mbsmd9_Vmq_KUFXmCc4i4wKeY_7AnreiUZsIfU9PCQf7aRgzRIuppw4Ijlrl9fd1p3veleHBLK6R5ZZGLpeF-H09s4Up1zmG9UVjAjQnaKMY2UDg25efUGW968uN5i1YMVGXFdXkDG-8NeOJDMl2GiwUrvP7Bs_srFkzMH_P9YEjMzPjdIcDTvB9r13T_NXNnBZGh9Hmq2uCkLmxoBuC0pBsHgzf6FOBTRM2Q/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJSRQCZNMUUPESYXKCYNXUTVKIAULANCNFSM5UO22L2A>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


NOTICE: This message may contain confidential information intended only for the recipient.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer.

**Comment by maikvandergaag** [comment]
@DerekLedbetter Technically there is not much different from a CI / CD pipeline. The main difference are the tasks and the references to the filepaths. If it works for CI it should also work for your CD. What are the differences between those two?

**Comment by DerekLedbetter** [comment]
Please don’t close.

Let’s setup a meeting so I can get the CD portion working.

I am still requesting assistance.



From: Maik van der Gaag ***@***.***>
Sent: Thursday, June 16, 2022 3:13 PM
To: maikvandergaag/msft-extensions ***@***.***>
Cc: Ledbetter, Derek ***@***.***>; Mention ***@***.***>
Subject: [External Email]Re: [maikvandergaag/msft-extensions] How to use "Pipeline" - Build Pipelines / Releases (Issue #398)


Closed #398<https://secure-web.cisco.com/1FppiaMeB_yf7TEmx6U5fYFXmjTOqRgjmjho86HHIEHGIwKFwpnqbxrnRVy57bN4Bzg67fIuZHyZUQRDdkKHINljejEzjSbRgM1NqFsgl6FGFeL1KLyR9BRXz-X0C6OEn4KXFmfpmVwStfa_CU9YTT1ajS5rneHnL1PipcGJJpzMbWChrm7LcB8XfaeFpBGyXMonbNzxpbL6SG4Cd_9Kuw3fS5q_JtmYuzVRHM_8Qfdgs2WBzoN2lTlEW9i4eapnNlAiA0zF88T2JRwXL0FALoFxhI_f4tkgvpcB7JejBQBPQmwNj_dQZUBWDbXnSPjavsooUde4fx-pNtSXaZH9SStwySFlL9cce7xEzkBIrnG_NZqFj7oTjCwxAe8FsBau2rWrcqnJfN1eSJYYdnCbvFA/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398> as completed.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1hG3E8IGb1bl_rLGQoFc9-Ndv3aSeaKh9nR9jAc1PjXR3g810y5BX114zv2g2FEluoO5AS_h2pTJSR3VHRdI-JUHEMKJRiSI7c3wbJuE3sQ7369TFJ3NoeD-XFA5iNl8mUT3hG3lcN7dOPUpUeq9cc3vqaD9Agh9OUlYX3r-6JyX2bwnSqMeNCNH7SJ8zcUjRXJYWvUBslUD1ZfEZ8zzFcdcWI1zXVeRBlZj8IBZcOJQQHse_sHu1d4NV9qH1hm3pgH43nooH_xhElTqEG9IcmB3TeS-sqW1ECM_tM3o36WW3DSrib0ZVJibJH-aTmcIYsK1nnqfhdldoN0T_K0Br4VLXEG1B8RRJBsycw-zovwtktRBSRDXSksxoZ8OYUAtV8CA389y6myKF0Lnb2rfNhg/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398%23event-6823447862>, or unsubscribe<https://secure-web.cisco.com/1wijIj1_VGgtjJRQfqbBb4TaVHfCglSJdA1cq6KLrnkubDmtGbruw_PdtJyN01GWED_KY_Tz6cN_yLiWPeDetCSGW1nZfHVD4bcnz9T7GwbwgaeynuKXvTENDCQ-ypfs8t9OAmTAuZEYmEIdTzCtxknAtXZzhjixbUhKCObr9SIRObv7TO11PG7JnnrpTZv4fMMyi69CI0F5DyJdmzDWoh6cP0UwVuhDeKKJZAOLBbTyM1vRqM3qsTrLKI8cdck4qlEnAZWJlZTl1q5GCmzwIJgeXConAltuB0DkjDWVv8NTgZD9Rb7e1AjPya2GP7YbaR6dOppRJFD04DCzhUZdS-rj1wk7Q6t2MDQ1lBoE417fY0PBpPr-oz8KdRb4tu7ztmRPMT38e4RlFZ04B9jaqvQ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJSRQC7E6KIGSY7VSHPYDO3VPN4CLANCNFSM5UO22L2A>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


NOTICE: This message may contain confidential information intended only for the recipient.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer.

**Comment by maikvandergaag** [comment]
Ok, @DerekLedbetter will reopen as there was no response for 20 days. I closed it. it should work on both portions. so we need to look at your setup.

**Comment by DerekLedbetter** [comment]
Please give me some dates times for a meeting (I'm on the East Coast USA).  Currently the time is 16:00.

**Comment by maikvandergaag** [comment]
sorry very busy, just send a invite I will see if it works

**Comment by maikvandergaag** [comment]
Info @ msftplayground . com

Groet,

Maik van der Gaag

**Comment by maikvandergaag** [comment]
Closing this issue as everything was discussed

**Comment by DerekLedbetter** [comment]
I’d like to setup a meeting for us to get together and work through the “Release” pipeline with the extension.



From: Maik van der Gaag ***@***.***>
Sent: Thursday, June 16, 2022 3:55 PM
To: maikvandergaag/msft-extensions ***@***.***>
Cc: Ledbetter, Derek ***@***.***>; Mention ***@***.***>
Subject: [External Email]Re: [maikvandergaag/msft-extensions] How to use "Pipeline" - Build Pipelines / Releases (Issue #398)


Reopened #398<https://secure-web.cisco.com/1teNroWovC7VWtaaU5DQyqI2sf1yzp87KL6r-LTMvhYgMsC6WoMTkJOgaueQKXIGsQ-K9CUD2mD1Wmub1mjDk7-ETkgv982Bq1IeLq6g1nRuotb-xPM2A7wfOzm4L8ArFVcphlhWKaX6yq4Vov9e0c1K-9Y3BV5TYpKlAZQUVNZaIukDCNi247EgHqCZaN5AEsi5O7STo3YhP1naSHunM9yTeQPAW9NBglxYint9MacApbh2YFnx1h8S7wyXCb4cdi5-ATuc9v_cipXoV5Qf-cw0KBZM25wo83CUc-4-ThbrOanRr8N9YOETtad3UU7714skcZIz3sqKnzpZ1r6rY8EowtvMSx14-jqLAC3edSmhvAy5P_hHYfL3Y8Aj2-lzA8l8Hwsjs9CG6Kr3dcNdSNg/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398>.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1OH3l9coyl3p_4OZBte-caeNI8j0-hOMsrGDBWFDNJAsMiT1LrZjQ0uOMPOGKzOfXSX8ac1HPyCg1K2ahXTcNFyWjjMUfubHa6y9uQs84w3gaEhBmMNW_LeMKyyKJCfo43N_PFqn-xtcd7rKzQfeKtJlFTi9qbiJOYeJ6EDnKiJ7ZQCZNGe-DIgCSyLgHtcGY4iYpeJc_pm-FxC6Frv7-1slg532cnW1ncu0sheWj3SJNP78eZvqvD1ZvS7Cxwm4jKtC3bfYDbmfOj7gY20Pb8YAEsUtGoJNotWLPLz4CQwcXTLJKyc2BtuYh4H-Pv4a_75hrLH4VWS-dFOn7rDzOV9BX92eSalVuQVFbCULWFqTC4ECLxsTryi1qSe-guPzOLZhk9V2ec0pKYjOb0FMNZg/https%3A%2F%2Fgithub.com%2Fmaikvandergaag%2Fmsft-extensions%2Fissues%2F398%23event-6823665847>, or unsubscribe<https://secure-web.cisco.com/1-AYREcUmToDr6xKwNCDORSoMrbxd8E5EjgLERDtCv8GMLD_VSS0vQqiYmT9Ed1Bfv6WKoKmrQhL2DFgPQzDgxjpbJXwLLJSa51jPmp2x4izpQtuCoEYM65hzVfzs8K74uTFACGZDfYlNlK61Lb8To7uAwFyTVayqaPa7hFCUHhIauLp0SW455uGLvS7ptxGnAgFC7aGFc-VdORYSqkobySfOE7Hn6n8f-6Mz1k4jPxwFXqeJFwgCSAOYwM5FqKzJDGcLij_Lat-ddtVJSaIA5BmXk7-WmcSGNVyXcrkGkRXvR2KiR_wKcB6NGX3z7j6Tmz0a8NxyUtgvxOYxBrd631EMxkeVgHznCuYRg92TYnk-poYho-jBHMX4hOZQWEDM6PwV09LD4DGYs3STdSjsFw/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJSRQC3PKUTBJFRKSRTIYEDVPOBCHANCNFSM5UO22L2A>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


NOTICE: This message may contain confidential information intended only for the recipient.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer.
