### ISSUE TITLE
##[error]Unable to find a build definition for Project Parker System Base with the build id: 791.

### ISSUE THREAD

**Issue by chrisparkeronline** [maikvandergaag/msft-extensions#404]
**Describe the issue**
Today, after using this extension for well over a year, I get "##[error]Unable to find a build definition for Project Parker System Base with the build id: 791.". Maybe with the new version I'm doing something wrong.

**Extension **
 - Extension: Version number counter
 - Version: 6 or 7.1-preview.7.

**To Reproduce**
1. Run pipeline errors on Version number counter step.

**Expected behavior**
Expect it to update the version number like previous.

**Situation (please complete the following information):**

 - Agent type:  On prem agent.
 - Authentication: Either new OAuth or Personal token.
 - Extension Version: Version: 6 or 7.1-preview.7.

**Log info**
Starting: Version number counter
==============================================================================
Task         : Version number counter
Description  : Build and release task for a version number counter
Version      : 2.0.10
Author       : Maik van der Gaag
Help         : 
==============================================================================
VersionVariable      : version
UpdateMinorVersion   : true
MaxValuePatchVersion : 0
UpdateMajorVersion   : true
MaxValueMinorVersion : 0
DevOpsPAT            : <not present>
DevOps Uri           : https://dev.azure.com/lcacorp/
Project Name         : Parker System Base
Project Id           : 2fcf31ac-824f-4961-855a-61ac309f8f95
Only Update Minor    : False
API Version          : 7.1-preview.7
BuildId              : 791
Invoking rest method 'Get' for the url: https://dev.azure.com/lcacorp/Parker System Base/_apis/build/builds/791?api-version=7.1-preview.7.

**Comment by maikvandergaag** [comment]
Could you share a debug log?

**Comment by chrisparkeronline** [comment]
I have attached the log.
[log.txt](https://github.com/maikvandergaag/msft-extensions/files/8665878/log.txt)

**Comment by maikvandergaag** [comment]
Sorry the log file does not contain anything regarding the extension you mentioned

**Comment by chrisparkeronline** [comment]
Look on line 920. It's not much information provided for the extension. This is all that is provided in the log. The error I see says this 

Cannot read property 'variables' of null

`
2022-05-09T15:35:54.2706919Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2022-05-09T15:35:54.2803421Z ##[section]Finishing: Restore
2022-05-09T15:35:54.2824978Z ##[section]Starting: Bumping version number
2022-05-09T15:35:54.2992712Z ==============================================================================
2022-05-09T15:35:54.2993026Z Task         : Version Increment Task
2022-05-09T15:35:54.2993561Z Description  : This package helps automatic versioning of packages
2022-05-09T15:35:54.2993801Z Version      : 0.0.6
2022-05-09T15:35:54.2993939Z Author       : Oscar van Tol
2022-05-09T15:35:54.2994113Z Help         : 
2022-05-09T15:35:54.2994299Z ==============================================================================
2022-05-09T15:35:54.7995938Z ##[error]Cannot read property 'variables' of null
2022-05-09T15:35:54.8044421Z ##[section]Finishing: Bumping version number
2022-05-09T15:35:54.8111574Z ##[section]Starting: Checkout Common Library@main to s
`

**Comment by maikvandergaag** [comment]
I don't think that is coming from my extension. Because at first it should show some information about the extension and I do not see and info

**Comment by klucyszy** [comment]
Hi, I got sth similar. No matter which API Version I select I'm getting error: `Unable to find a build definition for Project XXX with the build id: 123123.`

As I see the in the GET for the build, the api-version is incorrectly set with the dot at the very end.

```Starting: Version number counter
==============================================================================
Task         : Version number counter
Description  : Build and release task for a version number counter
Version      : 2.0.10
Author       : Maik van der Gaag
Help         : 
==============================================================================
VersionVariable      : package.version
UpdateMinorVersion   : true
MaxValuePatchVersion : 100
UpdateMajorVersion   : false
MaxValueMinorVersion : 0
DevOpsPAT            : <not present>
DevOps Uri           : https://dev.azure.com/XXX/
Project Name         : XXX
Project Id           : XXX
Only Update Minor    : False
API Version          : 7.1-preview.7
BuildId              : 62755
Invoking rest method 'Get' for the url: https://dev.azure.com/XXX/XXX/_apis/build/builds/XXX?api-version=7.1-preview.7.

##[error]Unable to find a build definition for Project tedee with the build id: 62755.
Finishing: Version number counter
```

If you try to run any api-version with dot at the end, the Azure Dev Ops service returns bad request with error as below:
```
{"$id":"1","innerException":null,"message":"Invalid api version string: \"7.1-preview.7.\". Api version string must be in the format: {Major}.{Minor}[-preview[.{ResourceVersion}]].","typeName":"Microsoft.VisualStudio.Services.WebApi.VssInvalidApiResourceVersionException, Microsoft.VisualStudio.Services.WebApi","typeKey":"VssInvalidApiResourceVersionException","errorCode":0,"eventId":3000}
```

**Comment by maikvandergaag** [comment]
Then your buildid isn't correct

**Comment by klucyszy** [comment]
Ok, got it. The pipeline permissions were not enough when using OAuth. Fixed when used PAT. I created PR with a minor error message change that can suggest the permissions are not satisfied.

https://github.com/maikvandergaag/msft-extensions/pull/437
