### ISSUE TITLE
ISO27001 certified

### ISSUE THREAD

**Issue by PaulKar9** [maikvandergaag/msft-extensions#406]
I am wondering, is this extension ISO27001 certified?
Is there any penetration test summary report or security attestation for this extension?

**Comment by maikvandergaag** [comment]
Hi Paul,

The extension is not certified testing reports are not available. If you would like more info or have specific info please contact me via email info at msftplayground dot nl

**Comment by PaulKar9** [comment]
The dot gets evaluated into an actual dot or the three letter dot?
A bit confused what email to send this to.
Mine is paul.kardash@aimco.ca
The email I tried from what you wrote above bounced back for me.
