### ISSUE TITLE
Set refresh schedule not working in power bi actions extension in ADO.

### ISSUE THREAD

**Issue by souvik221** [maikvandergaag/msft-extensions#407]
Hi @maikvandergaag 

Hope you are doing great !

set refresh schedule job failing in power bi actions extension in ADO. Detail debug log below 

Rest all jobs as mentioned in below snapshot are working fine with no errors !

![image](https://user-images.githubusercontent.com/33418807/169514607-7f128221-cb75-4bad-b05c-eeda87a2bee5.png)
![image](https://user-images.githubusercontent.com/33418807/169514937-2cacdece-7f09-4d6a-9606-78a9fe5102d9.png)

**Comment by maikvandergaag** [comment]
Could you please share the complete debug log?

**Comment by souvik221** [comment]
[ReleaseLogs_342.zip](https://github.com/maikvandergaag/msft-extensions/files/8751578/ReleaseLogs_342.zip)

**Comment by maikvandergaag** [comment]
I will have a few days off at the moment

**Comment by souvik221** [comment]
Hi @maikvandergaag,

Can I expect an update on this issue now ?

-Souvik

**Comment by maikvandergaag** [comment]
Publishing a new version at the moment could you try with that version?

**Comment by souvik221** [comment]
Hi @maikvandergaag ,

I still don't see the new version at the moment in my ADO org.

![image](https://user-images.githubusercontent.com/33418807/171158301-34b8ac1e-5a49-4372-83a5-62be42751c0b.png)

**Comment by maikvandergaag** [comment]
Deployment will be done automatically because it is still version 5

**Comment by souvik221** [comment]
The statement "Publishing a new version at the moment could you try with that version?" is not clear at all . What do you exactly mean ??

**Comment by maikvandergaag** [comment]
I published a new version of the extension with a small adjustment please try again

**Comment by maikvandergaag** [comment]
Coudl you please share the complete logs again?

**Comment by souvik221** [comment]
[ReleaseLogs_365.zip](https://github.com/maikvandergaag/msft-extensions/files/8805069/ReleaseLogs_365.zip)

**Comment by souvik221** [comment]
Hi @maikvandergaag ,

Any findings on the above detailed logs ? Please suggest.

-Souvik

**Comment by maikvandergaag** [comment]
I will need more time. Please check on your end if you are able to deploy the report with the PowerShell module from Microsoft

**Comment by souvik221** [comment]
Any update on the fix @maikvandergaag ?

**Comment by souvik221** [comment]
refresh schedule is working using PBI powershell cmdlets.

**Comment by robspaansinspark** [comment]
> refresh schedule is working using PBI powershell cmdlets.

@souvik221 can you please share your powershell code where you set the schedule? 

I'm running into the exact same problem, but the strange thing is that for 1 dataset it works perfectly and within the same workspace, with the same authorisations another dataset gives the same error. The only difference is the name of the datamodel.

**Comment by maikvandergaag** [comment]
@souvik221: Would be great if you can share your code you used.

**Comment by robspaansinspark** [comment]
And I'm still very curious about the powershell code :) because obviously you want a notification when the refresh fails.

**Comment by maikvandergaag** [comment]
@souvik221 are you able to share the code you used?
