### ISSUE TITLE
Unable to publish a dataset due to error 'The import was not successful for import ID 'xxxxxxxx', report name 'xxxxxxxx'. The import state was 'Failed'.'

### ISSUE THREAD

**Issue by rsdev-repo** [maikvandergaag/msft-extensions#408]
The publish is task is failing due to below error

![image](https://user-images.githubusercontent.com/63914614/170075611-42deaf83-6110-41b7-8a90-8b025e6691e8.png)

I have enclosed the complete debug log:
[tasklog_14.log](https://github.com/maikvandergaag/msft-extensions/files/8764292/tasklog_14.log)

**Comment by maikvandergaag** [comment]
Does it work manually

**Comment by rsdev-repo** [comment]
Hi Mike,,

Yes, I can publish manually after a refresh

**Comment by rsdev-repo** [comment]
Hi Maik,

We figured out that there was an issue with pbix, the import worked fine after correcting that. 

Thank you for your time.
