### ISSUE TITLE
Adding new type of Data Source for the UpdateDatasource action

### ISSUE THREAD

**Issue by ericAbaka** [maikvandergaag/msft-extensions#410]
**For which extension would you like to add a feature request?**
PowerBi Actions - Update Datasource

**Is your feature request related to a problem? Please describe.**
We have a data source of type Web in one of our report and we can't modify it yet through the extension...
![image](https://user-images.githubusercontent.com/106656645/171358958-cb234154-8819-4b7a-9b82-076b92fe722a.png)

**Describe the solution you'd like**
Being able to replace the source URL as we do for other sources

**Describe alternatives you've considered**
For now we are pushing the one report manually

**Additional context**

**Comment by maikvandergaag** [comment]
Could you share a report for testing purposes?
