### ISSUE TITLE
Operation returned an invalid status code 'BadRequest' while publishing any xlsx file

### ISSUE THREAD

**Issue by rubenGan** [maikvandergaag/msft-extensions#411]
**Describe the issue**
We are getting ##[error]Operation returned an invalid status code 'BadRequest' when we are trying to publish a xlsx file via Azure DevOps. I have had no problems publishing pbix or rdl.

**Extension**
 -Extension: Power BI Actions
 -Version: 5.4.33

**To Reproduce**
1. Go to Release pipeline
2. Click on create release and deploy
3. Scroll down to logs after Publish Power BI file

**Expected behavior**
It was expected to publish the xlsx file successfully to the workspace without any error

**Situation (please complete the following information):**

 - Agent type: Hosted | Azure Pipelines (windows-latest)
 - Authentication: Service Principal
 - Extension Version: 5.4.33

**Comment by maikvandergaag** [comment]
Please share the logs as well. Make sure to set the variable system.debug to true to get all the information.

Are you able to publish the same manually, and are the rights correctly configured?
