### ISSUE TITLE
Getting VS402964: Transitioning of stage from state 'Queued' to state 'InProgress' is not allowed.

### ISSUE THREAD

**Issue by glenndorr-ntracts** [maikvandergaag/msft-extensions#420]
I'm using Version 2.0.6 of the  Trigger Azure DevOps Pipeline task. The release is started and finished without error, but the calling release errors out with 
##[error]VS402964: Transitioning of stage from state 'Queued' to state 'InProgress' is not allowed.
Can you suggest a change for me?

**Comment by maikvandergaag** [comment]
Could you please share more info on what you are doing and also add the logs as requested in the template for the issue

**Comment by maikvandergaag** [comment]
Closed for now as there was no response. Please reopen if you have the information

**Comment by LuitWagemaker** [comment]
Hi,

Also running into 'VS402964: Transitioning of stage from state 'InProgress' to state 'InProgress' is not allowed.'
The targeted release-pipeline does get triggered though.

I hope you can advise, looking forward to your reply,

Br. Luit

[trigger.error.txt](https://github.com/maikvandergaag/msft-extensions/files/12793943/trigger.error.txt)
