### ISSUE TITLE
replace ADAL by MSAL

### ISSUE THREAD

**Issue by robspaansinspark** [maikvandergaag/msft-extensions#421]
**For which extension would you like to add a feature request?**
PowerBI Actions

**Is your feature request related to a problem? Please describe.**
In https://github.com/maikvandergaag/msft-extensions/blob/main/azuredevops/powerbiactions/powerbiactions/run.ps1 you use the ADAL module, but this year it will be depricated:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration

**Describe the solution you'd like**
It would be great if you can update the code so it uses MSAL if possible

**Comment by maikvandergaag** [comment]
@robspaansinspark there is a new version of the extension

**Comment by maikvandergaag** [comment]
If the new version: https://github.com/maikvandergaag/msft-extensions/blob/main/azuredevops/powerbiactions-new/powerbiactionsnew/run.ps1. Isn't fine please let me know will close the issue for now.
