### ISSUE TITLE
400 (BadRequest) when executing Power BI Action - Set refresh schedule

### ISSUE THREAD

**Issue by MichiPL** [maikvandergaag/msft-extensions#422]
**Describe the issue**
When executing the Power BI Action 'Set Refresh Schedule' it returns a 400 (Bad Request) error. Other actions are a success with the same Service Connection, workspace name & dataset name. The JSON that I am sending with the request is the example provided ({'value': {'days': ['Sunday'],'times': ['07:00'],'localTimeZoneId': 'UTC'}}). 

**Extension **
 - Extension: Power BI Actions
 - Version: 5.*

**To Reproduce**
1. Add Power BI Action to the release pipeline
2. Add the Service connection, workspace & dataset, the JSON file
3. Run the release pipeline

**Expected behavior**
The targeted Power BI dataset has a refresh schedule set using the parameters provided in the JSON file.

**Situation (please complete the following information):**

 - Agent type: Hosted Agent on Azure Pipelines, windows 2019
 - Autentication: Service connection using a Service Principal
 - Extension Version: 5.*

**Log info**
[tasklog_12.log](https://github.com/maikvandergaag/msft-extensions/files/9121160/tasklog_12.log)

**Additional information**
YAML of the PBI Action:

#Your build pipeline references an undefined variable named ‘workspacename’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
  displayName: 'Power BI Action: SetRefreshSchedule'
  inputs:
    PowerBIServiceEndpoint: 'Power BI Service'
    Action: SetRefreshSchedule
    WorkspaceName: '$(workspacename)'
    DatasetName: Bayard
    RefreshScheduleInput: '{''value'': {''days'': [''Sunday''],''times'': [''07:00''],''localTimeZoneId'': ''UTC''}}'

**Comment by maikvandergaag** [comment]
@MichiPL: After the PowerBI report is deployed are you able to change the refresh schedule manually or do you have to perform a specific action first?

**Comment by MichiPL** [comment]
I have to take over the dataset as it is configured by the Service Connection, but after that i can add & adjust a refresh schedule. I've also tried it directly via powershell, but i'm experiencing the same errors (on different datasets).
![image](https://user-images.githubusercontent.com/109357576/183015618-efdf21fd-4828-4b26-9560-ea858ed5eb8d.png)
![image](https://user-images.githubusercontent.com/109357576/183015689-9db5b5bc-53de-4e70-98ee-7f65ad36357f.png)

**Comment by maikvandergaag** [comment]
What steps are you using when doing it via PowerShell?

Could you try a take over dataset action in your pipeline first and than setting the schedule?

**Comment by MichiPL** [comment]
I'm currently already doing a dataset takeover action in my pipeline, the actions i perform are the following (in order): Publish, take over, SQL credentials update, Refresh schedule, delete report (so only dataset remains). 
The steps in the Powershell are the following: connect to the PBI service, find & list the workspace & report/dataset, send the request to update the refresh schedule (using the Invoke PowerBI rest method, patch method)

**Comment by maikvandergaag** [comment]
that is strange i will check what I can find out.

**Comment by maikvandergaag** [comment]
I have found the solution. By default when setting a refresh schedule through the API of the interface the dataset owner will receive a notification.

When using a service principal for example this will not work as the spn is unable to receive notifications. So you need to disable this in the config.

Sample message will then be:

`{'value': {'notifyOption':'NoNotification', 'enabled': true, 'days': ['Monday'],'times': ['07:00'],'localTimeZoneId': 'UTC'}}`

**Comment by MichiPL** [comment]
I have just tested & validated your solution, this seems to work perfectly! 
Thank you for the feedback, I was breaking my head on the error messages and couldn't figure it out myself. 
![image](https://user-images.githubusercontent.com/109357576/183056116-5ead8d2d-2661-4538-98e5-2f842890d855.png)
