### ISSUE TITLE
Power BI Action: Update Parameters for Multiple datasets

### ISSUE THREAD

**Issue by dileeprajam** [maikvandergaag/msft-extensions#424]
**For which extension would you like to add a feature request?**
Power BI Actions 2
**Question**
I am using Power BI Action to deploy my PBIX files via Azure DevOps. I want to set same server and database connection parameters for different reports. 

I am getting "Cannot bind argument to parameter 'DataSet' because it is null." at Power Bi Action: Take Ownership

i have passed "Dataset1; Dataset2" as value for the datasets variable defined for the task

Can you please help me with this issue

**Comment by ctimoftey** [comment]
Hi Dileepraja,

I think inside the Take Ownership action you cannot pass "Dataset1; Dataset2"
but only one "Datasetsomething"
Look at the example

![TakeOwneship](https://user-images.githubusercontent.com/80866261/182676632-ba9cba81-3a7b-4387-92fe-270b808a0e94.JPG)

But you have the option to takeover all the datasets within the workspace

**Comment by dileeprajam** [comment]
So either One or all datasets can be updated. Is there a plan on adding a feature to update multiple datasets?

**Comment by maikvandergaag** [comment]
related to feature request #427 closing this issue for now
