### ISSUE TITLE
Power BI Visuals got changed to old version of the report after deploying through DevOps pipeline using Powerbi action extension

### ISSUE THREAD

**Issue by nitinbiradar14** [maikvandergaag/msft-extensions#426]
Hi, 
Our Organization follows Automatic Deployment process for deploying Power BI reports. We create Power BI reports in Power BI desktop and upload pbix files into Azure Repo. This will automatically trigger the deployment pipeline. This is the standard procedure we follow on a regular basis, recently after a pipeline deployment to Production, we noticed a report deployed through the pipeline is not reflecting the changes we made to the report, Instead it was with the old version of the report which we initially deployed. But the credentials were with the respective environment and the data is also with the same environment but the report is with old instance of the repo and when the Dataset is refreshed it changed to the new layout and new changes we made were reflecting too. What could be the reason for this strange behavior?

Thanks & Regards,
Nitin Biradar

**Comment by maikvandergaag** [comment]
Hi @nitinbiradar14, I think this is related due to your process. In the extension nothing in particular is done with the reports

**Comment by ctimoftey** [comment]
Hi 
Maybe this is related when you use the extract action, you need to have these true
cleanDestinationFolder: true
overwriteExistingFiles: true

TY
G
