### ISSUE TITLE
Trigger build pipeline from the release pipeline - How to actually pass a variable from release to build pipeline?

### ISSUE THREAD

**Issue by nkatunov** [maikvandergaag/msft-extensions#429]
**For which extension would you like to add a feature request?**
Trigger Azure DevOps Pipeline
**Question**
I am triggering the build pipeline from the release pipeline and I need to pass a build number variable to the build pipeline. I was trying to use the "Release variable json" field for that with no luck. What I put in here is not set to env variables or to the params passed to the build pipeline. Is there a way to pass a variable?

**Comment by maikvandergaag** [comment]
@nkatunov: you should be able to put in parameters for the builds. The naming of the field is a bit off but this should work: Release variable json

**Comment by nkatunov** [comment]
Can you give a bit more specific example pls: Like if I set Release variable json value to {'name': 'test'} I should be able to get this value from my build pipeline by addressing it using parameters? If I specify parameter: name in build yaml file I get an error: "name param is not available". So it seems that the build pipeline cannot see the "name" param set in the Release variable  json field in the plugin

**Comment by maikvandergaag** [comment]
You also have to configure parameters in your build pipeline.

**Comment by nkatunov** [comment]
Yes, that is what I did, did not help

**Comment by maikvandergaag** [comment]
Then please share more info like logs and screenshots like mentioned in the template

**Comment by maikvandergaag** [comment]
As there was no response will close the ticket for now. If you still have the question please reopen and share the log files
