### ISSUE TITLE
Trigger release pipeline from build - Variabile Input

### ISSUE THREAD

**Issue by garcia117** [maikvandergaag/msft-extensions#430]
Try to trigger a Release pipeline from yaml build pipeline I have to pass parameter through VariableImput json param but I Don't understand how to pass json, es. { 'version' : 'x.y.z' }
 - Extension: Trigger Azure DevOps Pipeline
 - Version: 2.0.6

passing **VariableInput: '{''version'' : ''x.y.z''}'**
It's returns: 
**The release name ***-$$REV1$$ [refs/heads/*********] contains invalid character(s). Characters which are not allowed include '"', '/', ':', '', '\', '|', '?', '@', and '*'.**

Trying with different pattern it returns:
**##[error]Supplied json for the variables is not in the correct format!**

How can I resolve the issue?

**Comment by maikvandergaag** [comment]
The release variable should be in the format: {'name' : 'test', 'newValue' : 'test'}

**Comment by adityagu0910** [comment]
@garcia117 Could you please share your example of pipeline how you are using this passed variable in parameter of pipeline that is being triggered ?

I have same requirement as I need to pass  'isRelease' parameter to my main build pipeline and values could be 'PRERELEASE, PATCH, MINOR or MAJOR'
