### ISSUE TITLE
Issue while using PowerBI Actions extension 

### ISSUE THREAD

**Issue by Chetan8595** [maikvandergaag/msft-extensions#433]
Hi Team,

We're facing an issue while using an extension (PowerBI Actions) for the CI/CD in which, for two specific Workspaces ("Unifi Station Analytics - UAT" and "Unifi Station Analytics"), the pipeline doesn't recognise the workspace names as it seems to be encrypting half of the string (the workspace name "Unifi Station Analytics -UAT" will  transform into "***-UAT").
Could you please provide a possible solution to this usecase?

Best regards,
Chetan

**Comment by maikvandergaag** [comment]
Hi @Chetan8595, Would love to help you but please stick to the template for the issues. That way I have options to investigate I now miss a lot of valuable information.

Please recreate your issue with the template. I will then assists you so will close this one for now.
