### ISSUE TITLE
String encryption issue - PowerBI Actions 

### ISSUE THREAD

**Issue by Chetan8595** [maikvandergaag/msft-extensions#434]
Description:

We're facing an issue while using an extension (PowerBI Actions) for the CI/CD in which, for two specific Workspaces ("Unifi Station Analytics - UAT" and "Unifi Station Analytics"), the pipeline doesn't recognise the workspace names as it seems to be encrypting half of the string (the workspace name "Unifi Station Analytics -UAT" will transform into "***-UAT").
Could you please provide a possible solution?

**PowerBI Extension**
 - Extension: powerbiactions@5
 - Version: 5.*

**Comment by maikvandergaag** [comment]
Do you have logs

**Comment by Chetan8595** [comment]
Hello,

Could you please provide an update on this if any?

Best Regards,
Chetan

**Comment by maikvandergaag** [comment]
Could you share logs of the run?

**Comment by Chetan8595** [comment]
PFA the logs
![IMG_20220905_131047__02](https://user-images.githubusercontent.com/23029080/188396637-b1c06cb6-49f7-43b7-be9b-cdec88951be2.jpg)
![IMG_20220905_131047__01](https://user-images.githubusercontent.com/23029080/188396666-79deb452-3ea7-4bb7-991c-5f57061b83e1.jpg)
 for the Power BI Action: Publish task which is failed for the powerbi workspace (Unifi Station Analytics - UAT) .

Please let me know if you need any further information on this issue.

**Comment by Chetan8595** [comment]
Hi maik,

Any update on this issue?

Best regards,
Chetan

**Comment by Chetan8595** [comment]
Hello @maikvandergaag ,
I have already shared the run logs for the PowerBI Actions task.
Could you please look into the issue, we can quickly connect on call for a review of required.

Best regards,
Chetan

**Comment by maikvandergaag** [comment]
@Chetan8595 If the workspace can not be found this could be caused by two things:
- encoding problem within the extension.
- permissions

For the first one we made a fix a year ago, so the best guess is that it is option two please check all the permissions.

**Comment by maikvandergaag** [comment]
Oke,

Could you:
- Supply the logs in a txt file reference
- Tell me how you tested the API
- Tell me the security method used
- Version of the extension

That way I'm able to check the process. Next time please use the template of the issue because we are lacking info for a good investigation.

**Comment by Chetan8595** [comment]
> Oke,
> 
> Could you:
> 
> * Supply the logs in a txt file reference
> * Tell me how you tested the API
> * Tell me the security method used
> * Version of the extension
> 
> That way I'm able to check the process. Next time please use the template of the issue because we are lacking info for a good investigation.

@maikvandergaag ,
> * Supply the logs in a txt file reference:
[PowerBI_Actions_Error_log.txt](https://github.com/maikvandergaag/msft-extensions/files/9548082/PowerBI_Actions_Error_log.txt)
> * Tell me how you tested the API:
Here's a quick way for us to double-check how Power BI is reading the Workspace names directly, so we know if the issue is related with the Extension or with the PBI Service as a whole.
Could you go to this page (Groups - Get Groups - REST API (Power BI Power BI REST APIs) | Microsoft Docs) and click on the Try-It button?
This is an API that will list all the Workspaces that you have access to. When signing-in, let us use the same PBI account that you use on PBI Service. Afterwards, click directly on Run.
You should get a 200 result on the Response and see the Workspaces listed there on the Body. We see the Unifi Station Analytics and Unifi Station Analytics - UAT workspaces listed there.
[RESTAPI_Test_logs.txt](https://github.com/maikvandergaag/msft-extensions/files/9548181/RESTAPI_Test_logs.txt)
> * Tell me the security method used:
We have used the Service Principal authentication to PowerBI service 
> * Version of the extension:
PowerBi Actions: 5.4.39

Let me know if any more info required.

**Comment by maikvandergaag** [comment]
Oke thanks,

One point if you are using Service Principal Authentication. It can be due to the access rights of the SPN.

It is great that you have tested it our via docs but that is done by a user. The authorization can be very different for a spn.

**Comment by maikvandergaag** [comment]
Will check naming looks fine on the side of the extension.


Could you share screenshots of the configuration and the access rights on the workspace

**Comment by Chetan8595** [comment]
> Will check naming looks fine on the side of the extension.
> 
> Could you share screenshots of the configuration and the access rights on the workspace

@maikvandergaag ,
Attached are the screenshots for the ADO configuration and Access grant in PowerBi.
![PowerBI_Actions_Config](https://user-images.githubusercontent.com/23029080/189721310-7c447c78-ef98-4104-8584-d269014dcb89.JPG)
![PowerBI_Workspace_Access](https://user-images.githubusercontent.com/23029080/189721311-496e3cae-ce5e-434d-8410-c7e35d1b9520.JPG)

We could surely connect for a few minutes call if required as per your convinience.

Best regards,
Chetan

**Comment by maikvandergaag** [comment]
Thanks is that the only user in de access grant?

And could you maybe share the export from the api.

You can also share things via email if you do not want to place them here

**Comment by Chetan8595** [comment]
> Thanks is that the only user in de access grant?
> 
> And could you maybe share the export from the api.
> 
> You can also share things via email if you do not want to place them here

@maikvandergaag ,
There are many other users too as part of the workspace.
I will share via email to you on export details.

**Comment by Chetan8595** [comment]
> Thanks is that the only user in de access grant?
> 
> And could you maybe share the export from the api.
> 
> You can also share things via email if you do not want to place them here

@maikvandergaag ,
If I get you right, "export from api"  - https://api.powerbi.com/v1.0/myorg/groups 
When we run this RESTAPI , we sign in with the respective service account login to the powerbi and able to see the workspace details in the json.

**Comment by maikvandergaag** [comment]
Yes

**Comment by Chetan8595** [comment]
> Yes

@maikvandergaag , 
We have validated even that and it seems to be the access is absolutely fine.

**Comment by Chetan8595** [comment]
> > > Yes
> > 
> > 
> > @maikvandergaag , We have validated even that and it seems to be the access is absolutely fine.
> 
> @maikvandergaag , I have already shared you those details as part of the RESTAPI_test_logs.txt . It shows the details

@maikvandergaag ,
Any update on this??

**Comment by maikvandergaag** [comment]
Yes but would like to see a validated log with the Service Principal that you are using with the extension.

**Comment by Chetan8595** [comment]
> Yes but would like to see a validated log with the Service Principal that you are using with the extension.

@maikvandergaag ,
Am not sure what you meant by "validated log with the Service Principal".
However, in the attached success case and the failure case logs we have the service principal authentication successful.
We could surely schedule a quick call and close on this if possible.
Let me know your best time, so as to send you an invite for the same.

Best Regards,
Chetan

**Comment by maikvandergaag** [comment]
My availability is terrible could you just send me a time slot when you have time?

**Comment by Chetan8595** [comment]
> My availability is terrible could you just send me a time slot when you have time?

@maikvandergaag ,
I have sent a teams meeting to your email, could you please accept the invite, else please suggest a suitable timeline.

Best Regards,
Chetan

**Comment by Chetan8595** [comment]
> > My availability is terrible could you just send me a time slot when you have time?
> 
> @maikvandergaag , I have sent a teams meeting to your email, could you please accept the invite, else please suggest a suitable timeline.
> 
> Best Regards, Chetan

@maikvandergaag ,
Could you please join the call on the teams invite which i sent you?

**Comment by maikvandergaag** [comment]
@Chetan8595 Sorry was away with my family. We can schedule something for Wednesday. What timezone are you in?

Just tested the extension with the same naming and it works correctly so the encoding will not be the issue. I think you are missing some configurations arround the SPN that why I asked to call the API with the SPN.

**Comment by Chetan8595** [comment]
> @Chetan8595 Sorry was away with my family. We can schedule something for Wednesday. What timezone are you in?
> 
> Just tested the extension with the same naming and it works correctly so the encoding will not be the issue. I think you are missing some configurations arround the SPN that why I asked to call the API with the SPN.

@maikvandergaag ,
Sure, i will setup a call around 2pm IST On Wednesday.
Thanks for the test result, could you please share me the logs if possible for PowerBI actions task if possible, may be I could compare with my error logs and try to fix the configuration issues if any.

Best regards,
Chetan

**Comment by maikvandergaag** [comment]
off course:
[3_Power BI Action Publish.log](https://github.com/maikvandergaag/msft-extensions/files/9591137/3_Power.BI.Action.Publish.log)

**Comment by Chetan8595** [comment]
> off course: [3_Power BI Action Publish.log](https://github.com/maikvandergaag/msft-extensions/files/9591137/3_Power.BI.Action.Publish.log)

@maikvandergaag ,
Thanks for the log, but as per my observation the string name is different in the logs as "Unify Station Analytics - UAT", But this string is supposed to be " Unifi Station Analytics - UAT" right?

Best regards,
Chetan

**Comment by maikvandergaag** [comment]
Is it correct that you have a space in front of your name?

**Comment by Chetan8595** [comment]
> Is it correct that you have a space in front of your name?

@maikvandergaag ,
This is the exact string we could try on : 'Unifi Station Analytics - UAT'.
Best regards,
Chetan

**Comment by Chetan8595** [comment]
> > Is it correct that you have a space in front of your name?
> 
> @maikvandergaag , This is the exact string we could try on : 'Unifi Station Analytics - UAT'. Best regards, Chetan

@maikvandergaag ,
This part of the log I was referring to:
2022-09-17T06:30:31.9719158Z ##[debug]INPUT_WORKSPACENAME: 'Unify Station Analytics - UAT'

**Comment by Chetan8595** [comment]
> > > Is it correct that you have a space in front of your name?
> > 
> > 
> > @maikvandergaag , This is the exact string we could try on : 'Unifi Station Analytics - UAT'. Best regards, Chetan
> 
> @maikvandergaag , This part of the log I was referring to: 2022-09-17T06:30:31.9719158Z ##[debug]INPUT_WORKSPACENAME: 'Unify Station Analytics - UAT'

@maikvandergaag ,
Did you get a chance to try with the right string name?

**Comment by maikvandergaag** [comment]
Yes that also worked

**Comment by Chetan8595** [comment]
> Yes that also worked

@maikvandergaag ,
Could you please share the logs for the same,
We could discuss more on this in Wednesday (2pm IST) Call.

Best regards,
Chetan

**Comment by Chetan8595** [comment]
> > Yes that also worked
> 
> @maikvandergaag , Could you please share the logs for the same, We could discuss more on this in Wednesday (2pm IST) Call.
> 
> Best regards, Chetan

@maikvandergaag ,
Hope this timeline is ok for you.

**Comment by maikvandergaag** [comment]
Not able to share logs at this moment time is fine

**Comment by Chetan8595** [comment]
> Not able to share logs at this moment time is fine

@maikvandergaag ,
Sure, let me send you the updated invite.

**Comment by Chetan8595** [comment]
> > Not able to share logs at this moment time is fine
> 
> @maikvandergaag , Sure, let me send you the updated invite.

@maikvandergaag ,

Could you please join the teams call?

**Comment by Chetan8595** [comment]
> > > Not able to share logs at this moment time is fine
> > 
> > 
> > @maikvandergaag , Sure, let me send you the updated invite.
> 
> @maikvandergaag ,
> 
> Could you please join the teams call?

@maikvandergaag ,

**Comment by maikvandergaag** [comment]
Solution was to add the SPN to the users of the workspace

**Comment by Chetan8595** [comment]
Hello,

Due to organizational restrictions, i will not be able to share the logs
with you but I have provided the workspaces names.
However, the error says: "workspace ***-UAT doesn't exist".
We could surely connect over a quick call if required.

Best Regards,
Chetan
