### ISSUE TITLE
While publishing the report, all files are getting refreshed instead of only file with changes.

### ISSUE THREAD

**Issue by Kruu27** [maikvandergaag/msft-extensions#447]
"Power BI Actions"
Hi @maikvandergaag 
I'm publishing Power BI reports using this extension, It works good with single PBIX.
when two files are available into repository, and developer trigger a release by committing changes into one file, 
instead of only file with changes, all the files available into repository will go through pipeline and get refreshed into power BI service.
anyone got any idea, if I could add any variables or something else in release pipeline, so that only file with changes will get refresh in power BI service.

**Comment by maikvandergaag** [comment]
I understand your question. You will need to make additions to your pipelines to check what file is updated and save that in a variable and use that variable in the extension. This is not something buildin into the extension.

**Comment by Kruu27** [comment]
Can you suggest where could I add the variable?
