### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by Rachasmita** [maikvandergaag/msft-extensions#450]
After applying the incremental policy setup in the Power BI code base we are not able to deploy it from one environment to other using Power BI actions plugin in Azure Devops
![Incremental Deployment error Screenshot ](https://user-images.githubusercontent.com/114867478/193459326-18d083d0-911b-4c7c-92b6-eea963c32952.png)
[Incremental Deployment error Log.txt](https://github.com/maikvandergaag/msft-extensions/files/9692784/Incremental.Deployment.error.Log.txt)

**Extension **
 - Power BI Actions
 - Version: [Version of the extension]

**To Reproduce**

**Expected behavior**

**Situation (please complete the following information):**

 - Agent type: 
 - Autentication:
 - Extension Version: 

**Log info**
Please add the log file of the agent in debug mode [Add the variable system.debug with the value 'true ' to your pipeline]

**Additional information**

**Comment by maikvandergaag** [comment]
From the log it seems that the report you are trying to update cannot be found or the creds used do not have access to the report.

**Comment by Rachasmita** [comment]
> 

Hi Maik , We checked everything from our side looks Ok .Can you suggest if we can connect to discuss further on this plz

**Comment by Rachasmita** [comment]
Hi,

Need to connect and discuss this issue please.
I checked with Microsoft but they said its not their extension .Hence need your help to resolve this .
Regds
Rachasmita
________________________________

**Comment by maikvandergaag** [comment]
Hi Rachasmita,

I understand but this week will be hard at the end of next I have some time left. What you could try in the meantime is test with the script that are in the github repo from your local machine to see were it exactly breaks.

**Comment by maikvandergaag** [comment]
Could you also share a screenshot of your configuration by the way

**Comment by Rachasmita** [comment]
Hi Maik,

Please find the attached screenshots of the configurations .
Also please let me know if we can connect over call .

Regds
Rachasmita
________________________________

**Comment by Rachasmita** [comment]
+Pallavi
________________________________
From: Rachasmita Samal ***@***.***>
Sent: Friday, October 7, 2022 11:39 AM
To: maikvandergaag/msft-extensions ***@***.***>; maikvandergaag/msft-extensions ***@***.***>; Sonu Chandra (Ext - Consultant) ***@***.***>
Cc: Author ***@***.***>
Subject: [maikvandergaag/msft-extensions] Deployment Error (Issue #450)

Hi Maik,

Please find the attached screenshots of the configurations .
Also please let me know if we can connect over call .

Regds
Rachasmita
________________________________

**Comment by maikvandergaag** [comment]
@Rachasmita: I can not see the screenshots.

**Comment by Rachasmita** [comment]
Hi Maik,
Enclosing the screenshots again.
![Incremental Deployment error Screenshot ](https://user-images.githubusercontent.com/114867478/195832734-6c760286-83ef-40d7-8243-07a7ff35da10.png)
![Incremental Deployment error Screenshot 1 ](https://user-images.githubusercontent.com/114867478/195832740-24eab597-fa0b-498b-9666-02309ecdead4.png)
![Screenshot 2022-10-07 105412  2](https://user-images.githubusercontent.com/114867478/195832742-ed86e587-ddc9-4caf-85a7-77c47d7da3fd.png)
![Screenshot 2022-10-07 110410  3](https://user-images.githubusercontent.com/114867478/195832744-721b037f-ef76-40af-b262-60c9249bb47c.png)


Regds
Rachasmita

**Comment by Rachasmita** [comment]
Hi Maik,
As you can see ,we are struck with the above issue since long .Need you to try to connect over a call as soon as possible .
Please confirm .

Regds
Rachasmita
________________________________

**Comment by Rachasmita** [comment]
Hi Maik,
As you can see ,we are struck with the above issue since long .Need you to try to connect over a call as soon as possible .
Please confirm .

Regds
Rachasmita

**Comment by maikvandergaag** [comment]
Hi @Rachasmita, yes we can have a call, at the moment I'm sick but we can schedule one for next week.

What you could try is the powershell execution locally. To find out why it is not finding the DatasetId. My guess still is that this is because of misconfiguration.

**Comment by Rachasmita** [comment]
________________________________

**Comment by Rachasmita** [comment]
Hi Maik,
As you can see ,we are struck with the above issue since long .Need you to try to connect over a call as soon as possible .
Please confirm .

Regds
Rachasmita

**Comment by Rachasmita** [comment]
Hi Maik,

Here is the screenshot of latest error that we are getting ,
I have scheduled a call @ 4pm IST ,please join to discuss.

Regds
Rachasmita

![MicrosoftTeams-image](https://user-images.githubusercontent.com/114867478/197174513-66366642-695e-4b48-a569-097721672ffb.png)

**Comment by Rachasmita** [comment]
Hi Maik,

We waited for you in the call .Not sure if you have got the invite or not .
Need your help to close this issue at the earliest .
Please confirm your earliest possible convenient time to connect .

Regds
Rachasmita

________________________________
From: Rachasmita Samal ***@***.***>
Sent: Wednesday, October 19, 2022 5:04 PM
To: maikvandergaag/msft-extensions ***@***.***>; maikvandergaag/msft-extensions ***@***.***>
Cc: Mention ***@***.***>; Pallavi Routray (Ext - Consultant) ***@***.***>
Subject: RE: [maikvandergaag/msft-extensions] Deployment Error (Issue #450)
When: Friday, October 21, 2022 4:00 PM-4:30 PM.
Where:


________________________________

**Comment by maikvandergaag** [comment]
Hi,

I did not receive any call. Please send one for next week

**Comment by maikvandergaag** [comment]
Also send complete log file from the images I cannot extract all the info

**Comment by Rachasmita** [comment]
Hi , Herewith enclosing the complete log file .
Also, please confirm your email id to send meeting invite to scheduled call coming 
[tasklog_9.log](https://github.com/maikvandergaag/msft-extensions/files/9843857/tasklog_9.log)
week

**Comment by maikvandergaag** [comment]
Info at msftplayground dot com

**Comment by Rachasmita** [comment]
Hi Maik,
Have shared the meeting invite to  Info@msftplayground.com  .Please confirm receipt and join .

Regds
Rachasmita

**Comment by maikvandergaag** [comment]
Haven't received an invite

**Comment by Rachasmita** [comment]
Its for tomorrow 27th oct @ 2pm .

here is the link ,
https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_NzY1Njk1MjUtNjVjMi00NDg4LWJhZDQtYWEzODM3NGU1ODM5%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522fe9c4641-3b53-43d0-af72-8f3e64d3aa05%2522%252c%2522Oid%2522%253a%252242d1b715-f89d-4080-94d5-faa190eb46b2%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=032cb6a8-5a05-47f4-8b0d-d3ffba2e064b&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

**Comment by Rachasmita** [comment]
Hi Maik,
Can you please join .We are waiting for you in the meeting.

**Comment by maikvandergaag** [comment]
Please check your email!

**Comment by maikvandergaag** [comment]
Let's do further communication via e-mail. You are encountering an issue I'm glad to help you with. but this issue should not be pilled up with unnecessary information.
