### ISSUE TITLE
Proxy Admin option

### ISSUE THREAD

**Issue by RickyDiazTech** [maikvandergaag/msft-extensions#451]
**For which extension would you like to add a feature request?**
Power BI Build Tools

**Is your feature request related to a problem? Please describe.**
I am trying to implement an Azure DevOps solution for Power BI within a large company that has very tight security.
We are told to use a specific proxy for all DevOps agents which can be set within the agent.
However, when using pre-imported extensions this proxy config is bypassed which results in no connection to the Power BI Service.

**Describe the solution you'd like**
Add parameter to each task to allow the end-user to enter their own proxy settings.

**Describe alternatives you've considered**
After extension has been downloaded, I have manually updated the run.ps1 file top include the following code to set the proxy.

$proxyString = "http://proxy.azure:1234"
$proxyUri = new-object System.Uri($proxyString)
[System.Net.WebRequest]::DefaultWebProxy = new-object System.Net.WebProxy ($proxyUri, $true)

**Additional context**

**Comment by maikvandergaag** [comment]
@RickyDiazTech so you are using your own agents? 

If so you need to configure a system wide proxy.

**Comment by RickyDiazTech** [comment]
Hmmm, I thought I had done that using _netsh winhttp set proxy "http://proxy.azure:9999"_ on the VM but it was still ignored.

**Comment by maikvandergaag** [comment]
Yes that should be correct for the current user I think. It should be enabled for the user that is running the tasks itself.
