### ISSUE TITLE
How to rebind paginated report .rdl to a different model?

### ISSUE THREAD

**Issue by mflps** [maikvandergaag/msft-extensions#453]
**How to rebind paginated report .rdl to a different model?**

I'm trying to use rebind feature and doesn't work... give me an error...

I was looking in the docs, and I think there is an API function, but it's not implemented I think... [API request](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/update-datasources#rdldatasourceconnectiondetails)

Can you help me?

Thank you,
Miguel

**Comment by maikvandergaag** [comment]
Hi Miguel, I think so as well not everything is supported at the moment
