### ISSUE TITLE
How to change credentials for a SP publish dataset?

### ISSUE THREAD

**Issue by mflps** [maikvandergaag/msft-extensions#454]
**How to change credentials for a SP publish dataset?**

I'm trying to change the credentials for a datasource on a dataset published using SP connection and gives me an error...

It gives me error using PowerBI Actions and the UI... what I'm missing here?

thank you,
Miguel

**Comment by maikvandergaag** [comment]
That really depends on your situation and what you are trying todo could you elaborate more?

**Comment by mflps** [comment]
I  have a dataset that have two connections and I need to add SQL credentials using basic or auth but both failed... cannot change...

I have to manually take ownership with my account and everything works again...

**Comment by maikvandergaag** [comment]
Is the setup of your pipeline correct?

- For changes the SPN when used needs to be owner and should have the correct API permissions and the correct permissions in Power BI
