### ISSUE TITLE
How to use json with control characters in the update parameters 

### ISSUE THREAD

**Issue by smishr04** [maikvandergaag/msft-extensions#456]
Hello , I am using the - task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5 for updating datasets parameters . The database has a backslash " \\" in it and while running the task gives error and says bad request .

       - task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
         displayName: 'Power BI Action: UpdateParameters for Database'
         inputs:
           PowerBIServiceEndpoint: 'powerBI_SPN_NP'
           Action: UpdateParameters
           WorkspaceName: 'WorkspaceName'
           DatasetName: 'DatasetName'
           ParameterInput: '[{''name'' : ''ServerName'', ''newValue'' : ''"abcd.abcd.com\\qasql2020,61644"''},{''name'' : ''Database'', ''newValue'' : ''QADB7''}]'

Actual json i am looking to use - > 
[{"name":  "ServerName","newValue":  "abcd.abcd.com\\qasql2020,61644"},{"name": "Database","newValue":  "QADB7"}]
Any help on this ? thanks in advance .

**Comment by maikvandergaag** [comment]
Closing the issue because there was no response
