### ISSUE TITLE
Use TLS 1.2

### ISSUE THREAD

**Issue by negberts** [maikvandergaag/msft-extensions#46]
Our ADFS server is updated with a firewall in front of it, only accepting TLS 1.2 calls. Now the Power BI actions fail because this request is made with 1.0. 

Could you provide an option in the settings that TLS 1.2 can be used? That would be great!

**Comment by maikvandergaag** [comment]
will try to add it this week

**Comment by maikvandergaag** [comment]
Issue is fixed in version 2.0.7

**Comment by negberts** [comment]
Thank you!
