### ISSUE TITLE
Unable to find a build definition for Project

### ISSUE THREAD

**Issue by Alin-Dumitrescu** [maikvandergaag/msft-extensions#461]
Hello,

I am getting this generic error when trying to use the extension - we are on Azure DevOps services, tries both personal pat and system, both with 6.0 and 7.1-preview

What can be the problem? I attached the debug logs.

#
[logs_7378.zip](https://github.com/maikvandergaag/msft-extensions/files/10192244/logs_7378.zip)

**Comment by maikvandergaag** [comment]
This means that the build definition that you are trying to update cannot be found. This can be related to the fact of access rights or misconfiguration.

**Comment by Alin-Dumitrescu** [comment]
I did debug a bit through the PowerShell script - I don't think it's access or configuration - the set-up is pretty straight-forward. I think the issue is that the PS script is not getting all the builds for a build definition (e.g. if this is the 1st build AND it's not from the default branch) the script will not work.

**Comment by maikvandergaag** [comment]
Not totally getting your point the build definition is always there when configured

**Comment by Alin-Dumitrescu** [comment]
Exactly - this error message is misleading - the code is not handling all the scenarios correctly. The definition is there, since a build is running.

**Comment by maikvandergaag** [comment]
I think that it is. For example when your user does not have the correct permissions it will not be able to find and retrieve that specific definition. 

There are multiple ways to Rome here happy to accept a PR when you have a better solution.

**Comment by Alin-Dumitrescu** [comment]
Then, the error message should be invalid token, no? I tried both with a PAT and an system token, same issue.

**Comment by maikvandergaag** [comment]
Then something is still incorrect which guide did you follow

**Comment by Alin-Dumitrescu** [comment]
I used this web site. The code I have is here and the full build log is uploaded above:

  - task: versioncounter@2
    displayName: "Update build number"
    inputs:
      VersionVariable: 'next-build-number'
      DevOpsPat: '$(counter-pat)'
      buildapiversion: '6.0'

**Comment by maikvandergaag** [comment]
Ok, could you try this: https://msftplayground.com/2022/02/version-number-counter-now-supports-the-build-identity/

**Comment by Alin-Dumitrescu** [comment]
That's the one I have - I just installed the extension a couple days ago - it this different than the one on the market now?

**Comment by maikvandergaag** [comment]
The link has a full guide to setup your pipeline.
