### ISSUE TITLE
one or more error while publishing the report 

### ISSUE THREAD

**Issue by nikmk05** [maikvandergaag/msft-extensions#463]
Hi,
For publishing the files to power bi service workspace from azure devops release pipline does it requires same user id for both azure devops user account and power bi service connection user account?

I am getting the error while publishing "one or more erorr "

Currently i am using my work mail for service connection with power bi services and my lisense type is free.
But i only creating the pipeline with same work mail.

Can we use my work mail and some others power bi service id whoever having pro license?

Does it work?
[tasklog_6.log](https://github.com/maikvandergaag/msft-extensions/files/10318130/tasklog_6.log)

**Comment by maikvandergaag** [comment]
The user you use for the service connection should have a Power BI License. You can also use a SPN that does not require to have a license.

The account you use can be what ever you like it just needs a license

**Comment by nikmk05** [comment]
<img width="950" alt="Azure_devops_releasepipeline page" src="https://user-images.githubusercontent.com/121431424/210203045-39b2c481-0774-412c-afd1-c1237e0d4041.png">
<img width="545" alt="Deployerror" src="https://user-images.githubusercontent.com/121431424/210203048-250b43ec-b3b4-4e84-b2b8-97d5d80704e4.png">
<img width="930" alt="final error" src="https://user-images.githubusercontent.com/121431424/210203051-aaf9fda0-c1bc-46c8-a2e0-5901d473a36f.png">
<img width="747" alt="Serviceconnection page" src="https://user-images.githubusercontent.com/121431424/210203053-1a4bd49b-6961-4883-980e-1463d149e686.png">



Hi i am using username/password approch 
(because i am unable to enable service principle in Power bi services bcz i dont have admin access and i am using free account.)

So i attached the images of my CD process and Please consider this request and update me the solution.
I am struggling for this for last 3 days and i am getting only one error and that is same error too.


And please specify the lisence type of power bi service so we can achieve CD.

Thanks, 
NIkhil M K

**Comment by maikvandergaag** [comment]
Please add the variable: system.debug and set the value to true and then send the logs again

**Comment by nikmk05** [comment]
[tasklog_6 (1).log](https://github.com/maikvandergaag/msft-extensions/files/10357556/tasklog_6.1.log)

<img width="958" alt="Variable difining" src="https://user-images.githubusercontent.com/121431424/210937631-26ee8393-9297-48b8-a5ae-740ff00aa081.png">

Hi,
I am attaching Log file after declaring variable you said. And unable to find the issue. Please go through the file and update the same.

Thanks ,
Nikhil M K

**Comment by maikvandergaag** [comment]
Your Power BI Service connection is not configured correctly. Make sure you update that with the right credentials.

**Comment by nikmk05** [comment]
Okay thanks for your response and update.
