### ISSUE TITLE
##[error]Cannot bind argument to parameter 'Message' because it is null.

### ISSUE THREAD

**Issue by ahsanmirxa** [maikvandergaag/msft-extensions#464]
Using Trigger Azure DevOps Pipeline in yml pipeline. Following is the task configured. 

  - task: TriggerPipeline@2
    displayName: Trigger Reversion
    condition: and(eq(variables['reversionCheck'], 'true'), eq(variables['thresholdMet'], 'false'))
    inputs:
      serviceConnection: 'ADO'
      project: 'xyz
      Pipeline: 'Build'
      buildDefinition: '311'
      Branch: 'main'
      buildapiversion: '6.0'
      VariableInput: '{''triggeredbyRelease'':''$(triggeredByRelease)'', ''Environment'':''$(Environment)'', ''resultUrl'':''$(resultUrl)'', ''passedPercentage'':$(passedPercentage), ''releaseNumber'':''$(releaseNumber)''}'
      
But it is failing with the following error. 
##[error]Cannot bind argument to parameter 'Message' because it is null.

I am using same task to trigger another pipeline in the same yml, and it is working fine.

**Comment by ahsanmirxa** [comment]
I got the issue, actually this error came because of a runtime I am passing but missed to defined in the triggering pipeline. We are safe to close this thread.

**Comment by adityagu0910** [comment]
@ahsanmirxa 
I am facing similar issue but not able to figure out where the problem is.
Could you please share your complete example like how you are passing variable in triggering pipeline and then using that in triggered pipeline.
