### ISSUE TITLE
##[error]InvalidRequest

### ISSUE THREAD

**Issue by ee307079** [maikvandergaag/msft-extensions#466]
I get Invalid Request while updating parameters. My Update parameter Json is: 

[{'name': 'DataBase', 'newValue' : 'QA'}, {'name': 'Server', 'newValue' : 'qa-server'}]

What am i missing?

**Comment by maikvandergaag** [comment]
It seems to look valid any other configurations

**Comment by ee307079** [comment]
Action: Update parameters
Workspace name: Test-space
Dataset name: Injury BI
Update parameter json: [{'name': 'DataBase', 'newValue' : 'QA'}, {'name': 'Server', 'newValue' : 'qa-server'}]

**Comment by ee307079** [comment]
@maikvandergaag any updates on this please?

**Comment by ee307079** [comment]
The parameter type that are already set on PowerBI is "Any". Could that be a problem?

**Comment by maikvandergaag** [comment]
Could be

**Comment by ee307079** [comment]
Yes that was the reason. Thanks.
