### ISSUE TITLE
Power BI tasks are not available except Power BI Action: Publish

### ISSUE THREAD

**Issue by krishna914556** [maikvandergaag/msft-extensions#474]
After installing the extension, while creating the pipeline the powerBI action tasks are not available except for **Power BI Action: Publish**
<img width="810" alt="image" src="https://user-images.githubusercontent.com/127443756/224139674-36bea58e-b296-4aca-90d5-1ab623cec6d9.png">

**Comment by maikvandergaag** [comment]
Hi @krishna914556: There should be an action dropdown within the extension where you can change the action it performs.

**Comment by krishna914556** [comment]
Thanks a lot ! much appreciated
