### ISSUE TITLE
How to bind to Gateway datasource

### ISSUE THREAD

**Issue by Shahyads** [maikvandergaag/msft-extensions#475]
**Extension:** Power BI Actions 5.4.39
Hi @maikvandergaag 
I'm a newbe in PowerBI . I have an azure devops release pipeline.
I'm using PowerBI Actions to upload my pbix report file 
![PowerBI0](https://user-images.githubusercontent.com/9800566/224889449-bfb9ba2e-3ba4-40fe-a03a-d05400c9de02.JPG)
then i'm using PowerBI Actions to update the dataset datasource
![PowerBI1](https://user-images.githubusercontent.com/9800566/224889647-a459e1d0-f881-4905-9285-85a72ae1434d.JPG)
But after deploying the release, I have to map the datasource manually. How can I automate the following manual action?
![PowerBI2](https://user-images.githubusercontent.com/9800566/224889790-3778c6ce-65be-47f4-9878-dbe0946681d4.JPG)
could you please advise what is missing in my pipeline?
I tried  update gateway but 'm not sure if it is the correct action. Anyway it raises an error message it seems it needs more privileged account to be used. It is while I can apply mapping manually with the same account.
I think I don't know something obvious. any suggestions?
Thanks

**Comment by maikvandergaag** [comment]
Hi @Shahyads, I replyed to your pull request. Thank you of working with us!

**Comment by Shahyads** [comment]
Thanks @maikvandergaag 
I read your comment. Thanks for merging my code.
When are you going to release it?

How can i try the beta version? You might need to share it with my azure devops org [ShahyadS](https://dev.azure.com/ShahyadS) right?

**Comment by maikvandergaag** [comment]
Yes that is the case will do that as soon as possible and share you the link

**Comment by Shahyads** [comment]
Hi @maikvandergaag 
thanks. it seems you shared the last production version. so the new function is not included.

**Comment by maikvandergaag** [comment]
Thanks for noticing that. As we speak the beta version is being deployed.

**Comment by Shahyads** [comment]
Hi @maikvandergaag  
I installed the beta version . I did all my tests. It is working perfect. 
I will wait for the final release. 
Thanks

**Comment by Mo-Azh** [comment]
This is an amazing feature thank you for all your effort! When will we be able to have this in the final release? 👍

**Comment by maikvandergaag** [comment]
Should be in the final release.
