### ISSUE TITLE
Power BI Action update dataSource connection for paginated reports

### ISSUE THREAD

**Issue by sfabid** [maikvandergaag/msft-extensions#480]
Team I've been trying to setup my deploy pipeline using the power bi actions for the paginated reports. Publishing report using the "Upload Power BI report" works perfectly fine but "Update dataSource connection" is not working. 

I am trying to understand if this feature is intended for paginated reports or not and if there is a way we can configure the connection details through this addin. I know there is a rest api available from power bi to update the datasources for the paginated report but was hoping if there is something this addin has.

**Comment by maikvandergaag** [comment]
@sfabid to be completely honest we never tested it in a scenario like that.
