### ISSUE TITLE
Power BI Actions: Publish - Upload Power BI report (pbix) to workspace 

### ISSUE THREAD

**Issue by gopinaralasetty** [maikvandergaag/msft-extensions#486]
**Describe the issue**
I have stored my PBI file in azure Repos as used yaml code to build a artifact.
Using that artifact i was able to publish a PBI report to DEV Workspace using the Service principal till early last week with any issues.
but from few days i am facing an issue with error 'Forbidden'.

Error : 
2023-05-02T12:35:39.6566068Z ##[section]Starting: Power BI Action: Publish
2023-05-02T12:35:39.6673455Z ==============================================================================
2023-05-02T12:35:39.6673592Z Task         : Power BI Actions
2023-05-02T12:35:39.6673657Z Description  : Release Task Power BI Actions
2023-05-02T12:35:39.6673747Z Version      : 5.4.44
2023-05-02T12:35:39.6673806Z Author       : Maik van der Gaag
2023-05-02T12:35:39.6674382Z Help         : 
2023-05-02T12:35:39.6674470Z ==============================================================================
2023-05-02T12:35:41.2919365Z Starting Power BI Actions extension
2023-05-02T12:35:41.2919704Z ### Required Module is needed. Importing now...
2023-05-02T12:35:41.2920171Z ### Trying to import the incorporated module for PowerBI
2023-05-02T12:35:42.9187871Z Getting Power BI Workspace properties; SDP-PBI Dataset-DEV
2023-05-02T12:35:44.5682335Z Trying to publish PowerBI File: D:\a\r1\a\_SDP-PowerBI-Dataset\drop\PBI-Dataset\SDP PBI Model.pbix
2023-05-02T12:35:44.5719591Z Checking for existing Reports with the name: SDP PBI Model
2023-05-02T12:35:45.9739411Z Done processing Power BI Actions
2023-05-02T12:35:46.1726487Z ##[error]Operation returned an invalid status code 'Forbidden'
2023-05-02T12:35:46.2156705Z ##[section]Finishing: Power BI Action: Publish

**Extension **
Extension: Power BI Actions
Version: 5.4.39

**To Reproduce**
1. Create PBI workspace
2. Add Service principal as an admin
3. Allow Service principal to access the rest API in PBI tenant settings (Developer settings) 
4. Create build pipeline to build an artifact
5. Create a release pipeline with job to publish into the workspace
6. it fails with the error above.

**Expected behavior**
 Report should deploy to the Workspace without issues
 
**Log info**
Please add the log file of the agent in debug mode [Add the variable system.debug with the value 'true ' to your pipeline]

**Additional information**

**Comment by MGaneshwar** [comment]
> **Describe the issue** I have stored my PBI file in azure Repos as used yaml code to build a artifact. Using that artifact i was able to publish a PBI report to DEV Workspace using the Service principal till early last week with any issues. but from few days i am facing an issue with error 'Forbidden'.
> 
> Error : 2023-05-02T12:35:39.6566068Z ##[section]Starting: Power BI Action: Publish 2023-05-02T12:35:39.6673455Z ============================================================================== 2023-05-02T12:35:39.6673592Z Task : Power BI Actions 2023-05-02T12:35:39.6673657Z Description : Release Task Power BI Actions 2023-05-02T12:35:39.6673747Z Version : 5.4.44 2023-05-02T12:35:39.6673806Z Author : Maik van der Gaag 2023-05-02T12:35:39.6674382Z Help : 2023-05-02T12:35:39.6674470Z ============================================================================== 2023-05-02T12:35:41.2919365Z Starting Power BI Actions extension 2023-05-02T12:35:41.2919704Z ### Required Module is needed. Importing now... 2023-05-02T12:35:41.2920171Z ### Trying to import the incorporated module for PowerBI 2023-05-02T12:35:42.9187871Z Getting Power BI Workspace properties; SDP-PBI Dataset-DEV 2023-05-02T12:35:44.5682335Z Trying to publish PowerBI File: D:\a\r1\a_SDP-PowerBI-Dataset\drop\PBI-Dataset\SDP PBI Model.pbix 2023-05-02T12:35:44.5719591Z Checking for existing Reports with the name: SDP PBI Model 2023-05-02T12:35:45.9739411Z Done processing Power BI Actions 2023-05-02T12:35:46.1726487Z ##[error]Operation returned an invalid status code 'Forbidden' 2023-05-02T12:35:46.2156705Z ##[section]Finishing: Power BI Action: Publish
> 
> **Extension ** Extension: Power BI Actions Version: 5.4.39
> 
> **To Reproduce**
> 
> 1. Create PBI workspace
> 2. Add Service principal as an admin
> 3. Allow Service principal to access the rest API in PBI tenant settings (Developer settings)
> 4. Create build pipeline to build an artifact
> 5. Create a release pipeline with job to publish into the workspace
> 6. it fails with the error above.
> 
> **Expected behavior** Report should deploy to the Workspace without issues
> 
> **Log info** Please add the log file of the agent in debug mode [Add the variable system.debug with the value 'true ' to your pipeline]
> 
> **Additional information** Add any other context about the problem here.

 @maikvandergaag i am getting the same error, can you please help. I am the global admin and have full access 
@gopinaralasetty let me know if its resolved for you.

**Comment by MGaneshwar** [comment]
@maikvandergaag i am getting the same error, can you please help. I am the global admin and have full access
@gopinaralasetty let me know if its resolved for you.

**Comment by maikvandergaag** [comment]
Which permissions did you have setup for your service principal?

**Comment by MGaneshwar** [comment]
> Which permissions did you have setup for your service principal?

I have granted full permissions to service principal as in screenshot @maikvandergaag 

![image](https://github.com/maikvandergaag/msft-extensions/assets/137290916/634fac51-b4d6-4f2f-8342-c1181266509b)

**Comment by maikvandergaag** [comment]
You should look at the permissions in Azure AD

**Comment by MGaneshwar** [comment]
> You should look at the permissions in Azure AD

ok, you can have a look in this log as in screenshot and let me know where its failing. @maikvandergaag 

![image](https://github.com/maikvandergaag/msft-extensions/assets/137290916/24a0b869-e7b5-401e-85e9-56d7b348472a)

**Comment by maikvandergaag** [comment]
Could you do another run after you added a variable called system.debug and then share the logs?

**Comment by MGaneshwar** [comment]
[tasklog_8 (1).log](https://github.com/maikvandergaag/msft-extensions/files/11975305/tasklog_8.1.log)
 
Please find the detailed log

**Comment by maikvandergaag** [comment]
The issue seems to be coming from the Power BI PowerShell module of Microsoft. Is it a special kind of report you are trying to publish?

**Comment by MGaneshwar** [comment]
The report is connected live to one of the datamodel in powerbi workspace in which i am going to publish. @maikvandergaag

**Comment by maikvandergaag** [comment]
I think that could be related to the problem. Is there an option I could test this scenario for you?

**Comment by MGaneshwar** [comment]
> I think that could be related to the problem. Is there an option I could test this scenario for you?

* I Just tried a blank pbix file without connections, it got published.

Looks like the workspace is not accepting the reports which are connected to other datamodel in other workspace. I will import datamodel in the current workspace and then connect the report to that datamodel and try publishing the report from power bi actions.

you can test above scenario once like publishing the report of other workspace to current workspace through actions.

@maikvandergaag

**Comment by h-karthik12** [comment]
@maikvandergaag I too get the error while running the Publish task with service connection in release.
![image](https://github.com/maikvandergaag/msft-extensions/assets/108470701/6b1ac5aa-0b07-491f-849f-bbdd8a404581)

But work for username and password. I have followed same steps but not sure why this error occurring or I am missing some permission can you please guide me.
![image](https://github.com/maikvandergaag/msft-extensions/assets/108470701/dd68f95b-d868-4387-8cf3-8190a5a59572)

**Comment by h-karthik12** [comment]
@MGaneshwar @gopinaralasetty Do we need what type of azure AD Licence for PowerBI?
Because i am getting issue with free azure AD
![image](https://github.com/maikvandergaag/msft-extensions/assets/108470701/1aca8ab5-0b75-4d45-900f-adf8b421fc96)

**Comment by MGaneshwar** [comment]
> @MGaneshwar @gopinaralasetty Do we need what type of azure AD Licence for PowerBI? Because i am getting issue with free azure AD ![image](https://user-images.githubusercontent.com/108470701/256417396-1aca8ab5-0b75-4d45-900f-adf8b421fc96.png)

Yes karthik, it should have license. @h-karthik12

**Comment by h-karthik12** [comment]
@MGaneshwar Which type of license is preferred P1 or P2

**Comment by MGaneshwar** [comment]
> @MGaneshwar Which type of license is preferred P1 or P2

@h-karthik12 
for performing CI/CD from azure repo the pbi workspace should be in premium capacity, it can be either p1 or p2.

**Comment by MGaneshwar** [comment]
@maikvandergaag Is there a way to copy reports automatically from powerbi workspace to Azure repo through your extension?
I tried git integration in powerbi but the report format is in json which cannot be used for CI/CD

any ideas please?

**Comment by maikvandergaag** [comment]
@MGaneshwar are you still experiencing the problem. If so could you share more info please

**Comment by zhunipingan** [comment]
Hi @MGaneshwar and @maikvandergaag, I meet the similar problem, I can do the create workspace successfully, but will failed with "Unauthorized" error when do the uploading new report. Do you have any ideas. 
![image](https://github.com/maikvandergaag/msft-extensions/assets/26180853/4ce49207-abff-40d8-b2b1-01a83193fc9b)
![image](https://github.com/maikvandergaag/msft-extensions/assets/26180853/aa16b4e2-3fd4-4f82-9947-fac91e5f2c3c)
![image](https://github.com/maikvandergaag/msft-extensions/assets/26180853/0b19c29d-f2de-43ab-af14-0df91b13bf40)

**Comment by maikvandergaag** [comment]
Do you know what the SP permissions are?
