### ISSUE TITLE
Power BI Action - New-PowerBIReport failed

### ISSUE THREAD

**Issue by zuheirashraf17** [maikvandergaag/msft-extensions#494]
**Describe the issue**
The pipeline used to works fine without issue. Today there seems to be multiple error related to the Upload Power BI Report options. 
2 separate error on this action as following;
**1. ##[error]Operation returned an invalid status code 'Unauthorized'
2. The import was not successful for import ID 'xxx', report name 'xxx'. The import state was 'Failed'.**

**Extension **
==============================================================================
2023-07-24T03:54:28.5264623Z Task         : Power BI Actions
2023-07-24T03:54:28.5264690Z Description  : Release Task Power BI Actions
2023-07-24T03:54:28.5264790Z Version      : 5.4.44
2023-07-24T03:54:28.5264853Z Author       : Maik van der Gaag
2023-07-24T03:54:28.5265593Z Help         : 
2023-07-24T03:54:28.5265656Z ==============================================================================

**To Reproduce**
1. Upload existing report using Power BI Actions
2. Upload new report using Power BI Actions

**Situation (please complete the following information):**

 - Agent type: Azure Pipeline Pool | Windows 2022 / Windows 2019. same error
 - Authentication: Service Principal with all Admin workspace level access

**Log info**
Refer Attachment. 
[ImportState'Failed'.log](https://github.com/maikvandergaag/msft-extensions/files/12142211/ImportState.Failed.log)
[Unauthorized.log](https://github.com/maikvandergaag/msft-extensions/files/12142212/Unauthorized.log)

**Additional information**
Existing pipeline use to works fine until today, last time time it was working fine on 18th July. Tried to check on the version, nothing seems to change as well.

**API Permission has been reviewed as well, required access has been granted.**
![image](https://github.com/maikvandergaag/msft-extensions/assets/80750936/581905a9-68f5-4f07-aaff-546d0ebe6306)

Appreciate any support on this!

**Comment by maikvandergaag** [comment]
Is your secret still valid?

**Comment by zuheirashraf17** [comment]
> Is your secret still valid?

I had no idea what happen. The secret is till valid for at least another 3 month. and getting a workspace detail seems to be just fine as well, it was able to retrieve the Workspace ID etc. (based on the logging)

I went ahead and create a new secret and apply to the service connection to confirm of this. Now its working fine and resolved both issues.. I shall keep this in mind for future troubleshooting. Thanks!
