### ISSUE TITLE
Power BI Action: Publish - Import mode error

### ISSUE THREAD

**Issue by olofCarlsonBjernaldRexel** [maikvandergaag/msft-extensions#497]
**Describe the issue**
I use "Power BI Action: Publish" to publish reports from our TFS-repository to Power BI Service. I am connecting reports to a new dataset, using either the live connection to the dataset(datahub) or connecting via the xmla endpoint connection string. When i download using a live connection, the pipeline works perfectly. however, when i try to use the import mode (1st option), it fails.

![image](https://github.com/maikvandergaag/msft-extensions/assets/134390425/f593d10d-b86e-4271-85d7-1bed32aa1d94)

![image](https://github.com/maikvandergaag/msft-extensions/assets/134390425/4fa321fa-5bc2-4039-a540-9bd5dd7704ac)

**To Reproduce**
1. Go to power bi service and choose a report
2. Click on download file and choose "A copy of your report and data (.pbix)
3. Save your report in the repository and trigger pipeline

**Expected behavior**

**Situation (please complete the following information):**

 - Autentication: I am using a service connection with a service principal, which has admin rights in both the workspace and on the specific dataset.
 

**Log info**
Please add the log file of the agent in debug mode [Add the variable system.debug with the value 'true ' to your pipeline]
see below

[debug.txt](https://github.com/maikvandergaag/msft-extensions/files/12240426/debug.txt)

**Comment by maikvandergaag** [comment]
Does your service principal have the correct api permissions?
