### ISSUE TITLE
Update SQL Credentials - Scope parameter

### ISSUE THREAD

**Issue by kevinn1992** [maikvandergaag/msft-extensions#501]
**Describe the issue**
In the Power BI Action Update SQL Credentials there's a scope parameter which has the 2 values "Individual" and "Organization". If I'm not mistaken, this is the privacy level you give to your credentials like 'public', 'organizational' and 'private'. I refer to the official documentation: https://learn.microsoft.com/en-us/rest/api/power-bi/gateways/update-datasource#definitions

When I look at your code for the new Power BI Actions right here: https://github.com/maikvandergaag/msft-extensions/tree/main/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi for the function 'Update-BasicSQLDataSourceCredentials' (check the image below), it seems that the parameter 'Individual' is not correct.
![image](https://github.com/maikvandergaag/msft-extensions/assets/143867937/3e7d0c89-b90f-44ad-88e6-a6669fb7c437)
![image](https://github.com/maikvandergaag/msft-extensions/assets/143867937/d32affcc-1e3c-42f0-9ecc-cc4df98b08ca)

Isn't it the intention to give the 3 different privacy levels: 'public', 'organizational' and 'private' as parameter and change your function to some kind of switch?

Now, no matter what you fill in into your scope the $level variable will always be 'Individual' which is not a privacy level.
Please, correct me if I'm wrong.

Kind regards

**Comment by maikvandergaag** [comment]
@kevinn1992: when you are open to help with testing that would be much appriciated. I'm not a Power BI specialist and created the extension pure out of passion.

**Comment by maikvandergaag** [comment]
Still working on the xplat version. Would be able to incorporate it. Are you maybe able to help testing?
