### ISSUE TITLE
[error] Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by michelmetran** [maikvandergaag/msft-extensions#507]
**Describe the issue**
I created a pipeline to create an artifact, containing the .pbix file.
With the artifact created, I'm trying to publish it to a premium workspace. However, I am getting the error *##[error]Operation returned an invalid status code 'Unauthorized'*.

1. I have already registered the App on the Azure Portal
2. I have already defined the "Security Group" and authorized this group in Workspace.
3. I have already created a Secret to use when publishing the release

<br>

![](https://i.imgur.com/sTyvSio.png)

-----

**Extension**
 - Extension: [Power BI Actions](https://marketplace.visualstudio.com/items?itemName=maikvandergaag.maikvandergaag-power-bi-actions)
 - Version: 5.4.44

<br>

-----

**Expected behavior**
Considering that Security Goup is already enabled in the workspace, I expected the dashboar to be published in the workspace.

Note: here is a [video](https://www.youtube.com/watch?v=qskIb2Hilv4) containing explanations for configuring Power BI Actions

<br>

-----

**Situation (please complete the following information):**

 - Agent type: windows-2019
 - Autentication: Service Principal

<br>

-----

**Log info**
Attachment [tasklog_6(1).log](https://github.com/maikvandergaag/msft-extensions/files/12822639/tasklog_6.1.log)

**Comment by maikvandergaag** [comment]
Have you made the sp an admin and what are the configured ApI permissions?

**Comment by michelmetran** [comment]
Firstly, thank you for your help!
...your response was quick!!

I create a Security Group in Azure Portal and set the group as admin in a workspace.
![](https://i.imgur.com/qrF4fNz.png)

About APl permissions... I'll answer that part as soon as possible.
I don't remember requesting adjustments. Could you mention the correct definition?
(I don't have permission to use the Azure Portal, I need to ask other people in my company)

**Comment by maikvandergaag** [comment]
This is a screenshot when making it through the Power BI portal. These settings can also be configured in Microsoft Entra.

![image](https://github.com/maikvandergaag/msft-extensions/assets/9531411/e226bebd-5923-4632-bc6b-ec77d6cdcfb9)

**Comment by michelmetran** [comment]
I appreciate the help @maikvandergaag .
I managed to resolve the Unauthorized issue.
At the moment I have another problem that I have spent all day trying and have not been able to resolve.

I'm going to close this issue and open another one.
This extension will help a lot when I get it set up.

**Comment by zhunipingan** [comment]
Hi @michelmetran , how do you solve this problem, my issue is same to yours. And @maikvandergaag , what api permissions need to configure for the SP, I create the SP in azure portal, but not in the page as your screenshot, thank you all.

**Comment by michelmetran** [comment]
Initially I thought the problem was with API permissions, but that wasn't the main problem. Looking today (and working!), the only permissions I have active are:
- Tenant.Read.All
- Tenant.ReadWrite.All

At the time I was making a mistake when I put the Security Group (which I created in the Azure Portal) as a member of the PowerBI workspace. It's wrong! It is not necessary to place the Security Group (SG) as a member. In fact, it is necessary to place the Application (also created in the Azure Portal) as a member!!

After a lot of trial and error, I noticed the note and posted it at https://michelmetran.com.br/posts/pipelines/ (it's in Brazilian Portuguese)

**Comment by zhunipingan** [comment]
@michelmetran Thanks for your concrete and timely response！I have read you article, I think I have done the same steps as you, but I still meet the error, I can get workspace info but cannot do upload the report, hhh. I am so confused but don't know why, thanks for your sharing again.
