### ISSUE TITLE
Error: Power BI Action: Upload PBIX 

### ISSUE THREAD

**Issue by olofCarlsonBjernaldRexel** [maikvandergaag/msft-extensions#509]
**Describe the issue**
It seems that something in the Task has changed since 1 month ago. I use the action to upload pbix to pbi service, and it crashed today while having done no changes. There are 10 identical pipelines that point towards different folders in a TFS repository, the ones that has "å","ä","ö" in the folder name fail. The other succeeds. 

**Extension **
 - Power BI Action: Upload PBI report
 - Version: 5.4.44
**To Reproduce**
1. Rename a folder to contain "å","ä","ö"
2. Try to upload pbix from folder to Power BI Workspace

**Expected behavior**
##[error]Cannot find path 'D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.44\$\PBI Reports\Inköp' because it does not exist.

 - Agent type: 
 - Autentication: Service principal
 - Extension Version: 

**Log info**
[Error Log.txt](https://github.com/maikvandergaag/msft-extensions/files/12856589/Error.Log.txt)

**Additional information**
When i change the name using other letters the task works

**Comment by maikvandergaag** [comment]
Will check this out but see something strange in the error log. It is looking for a file in this folder is that correct?

D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.4.44\$\<Name> PBI Reports\Inköp

**Comment by maikvandergaag** [comment]
Closing this issue due to no response.
