### ISSUE TITLE
Does SPN work for update gateway and bind gateway?

### ISSUE THREAD

**Issue by dmkblesser** [maikvandergaag/msft-extensions#511]
First, thank you so much for making this extension. It helped us a lot in building up the pipeline.

The issue we are running into is after I successfully publish a report, I'd like to connect the datasource to a gateway and I'm not able to do that. 

The update gateway and bind gateway steps run successfully without popping any error messages. 

But when I check the dataset setting, it is not connected to the gateway. 

The report is using DirectQuery and we use a SPN for the service connection. 

I have read some past posts and here are my two questions:

1. Is this extension able to map datasource to the on-premise gateway when the report is using the DirectQuery Mode?
2. Does SPN support on update gateway? 

Again, thank you for your effort on this and really hope to get an answer from you.

**Comment by maikvandergaag** [comment]
If I am right you are not able to do that with a SPN

**Comment by dmkblesser** [comment]
thank you @maikvandergaag for the confirmation!
