### ISSUE TITLE
Publish Power BI pbix - always results in Error 400 Bad request

### ISSUE THREAD

**Issue by hoemT** [maikvandergaag/msft-extensions#512]
**Describe the issue**
I am trying to publish a pbix file with the "Publish" task.
It results in an error with "400 Bad request" at the Invoke-API step.
The exception message in the logs is truncated so I don't know how to further investigate the error.
My Testfile is a simple pbix without any special components.

I tried to copy the POST URL from the log to Postman and added the file there. --> with Postman the Upload works!

**Extension **
 - Extension: Power BI Actions
 - Version: 5

**Situation (please complete the following information):**

 - Agent type: windows latest 
 - Authentication: Service principal
 - Extension Version: should be the latest (installed it last week)

**Log info**
[Publish_Log.txt](https://github.com/maikvandergaag/msft-extensions/files/13236027/Publish_Log.txt)

**Comment by maikvandergaag** [comment]
Are you using any specific features in the Power Bi report?
