### ISSUE TITLE
Error in task Power BI Actions: Publish

### ISSUE THREAD

**Issue by Meelitafargose** [maikvandergaag/msft-extensions#518]
While deploying the PBIX file getting error as "The given key was not present in the dictionary."

I have followed some prerequisite steps as follows:

1)<img width="761" alt="1" src="https://github.com/maikvandergaag/msft-extensions/assets/154305163/21030d69-e12f-4fdf-a5ec-68c5de36a11b">

2)Added Power Bi Apis permission for SPN.

**Comment by maikvandergaag** [comment]
Could you share more info?

**Comment by Meelitafargose** [comment]
[ReleaseLogs_134.zip](https://github.com/maikvandergaag/msft-extensions/files/13713359/ReleaseLogs_134.zip)
pls find the logs release pipeline  logs

**Comment by maikvandergaag** [comment]
I think something is wrong in the configuration of the task. Could you share more details?
