### ISSUE TITLE
Clarification : New release create with PAT user but it should be originally build create user

### ISSUE THREAD

**Issue by LilanSilva** [maikvandergaag/msft-extensions#524]
**For which extension would you like to add a feature request?**

**Question**
I have a release pipeline called 'Parent Release' and 'Child Release.' I use an extension in the 'Parent Release' to trigger a new 'Child Release.' The problem is that the user created in the 'Child Release' appears as the PAT (Personal Access Token) created user instead of the 'Parent Release' created user. Is there any way to fix this?

**Comment by maikvandergaag** [comment]
Hi @LilanSilva not completely sure what you mean. Important is that the connection is made from the parent pipeline to the child one. There are no real specific permissions.

**Comment by LilanSilva** [comment]
My requirement is that when a developer commits changes to the master branch, a release pipeline called “Parent release pipeline” is triggered using the build from that commit. This release pipeline includes a "Trigger Azure DevOps Pipeline" step to trigger another release pipeline called “Child release pipeline” based on the build artifacts. To achieve this, I used the "Trigger Azure DevOps Pipeline" extention with a Personal Access Token (PAT). However, when I trigger a new release (“Child release”) pipeline using the PAT, the PAT is treated as the user creating the new release, causing an issue. New release (“Child release”) create user should be originally build trigge user.

**Comment by maikvandergaag** [comment]
Oke, so the user that triggered the parent pipeline should also be the one that triggers the child pipeline is that correct?
