### ISSUE TITLE
Please clear/fix the warning messages - unapproved verbs

### ISSUE THREAD

**Issue by Prashanth-PS** [maikvandergaag/msft-extensions#53]
Hi, 

Thanks for the task, it is really helpful for us to upload and update the PowerBI reports, however the product team is looking at much cleaner deployment. 

Hence could you please fix the below warning this task is generating: 
##[warning]The names of some imported commands from the module 'PowerBi' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

Regards,
Prashanth

**Comment by maikvandergaag** [comment]
Will be fixed in the new major release of the Power BI Actions extension.

**Comment by maikvandergaag** [comment]
Fixed in the new release
