### ISSUE TITLE
Power BI Report Parameters are not getting updated after the successful execution of the Azure DevOps CICD pipeline.

### ISSUE THREAD

**Issue by anupkosh** [maikvandergaag/msft-extensions#530]
**Describe the issue**
Power BI Report Parameters are not getting updated after the successful execution of the Azure DevOps CICD pipeline using the Pipeline tasks - Power BI Actions : UpdateParameters(Ver: 5.4.48).

**Extension **
 - Extension: Power BI Actions : UpdateParameters
 - Version: 5.4.48

![image](https://github.com/maikvandergaag/msft-extensions/assets/159920394/8abc360e-3bbd-4945-a041-1e9ccf79b4cd)

**Comment by maikvandergaag** [comment]
Could you share more info for example log files?

**Comment by anupkosh** [comment]
<img width="950" alt="1" src="https://github.com/maikvandergaag/msft-extensions/assets/159920394/deabcfde-68be-4efe-abf6-972e65dc44f8">
<img width="811" alt="2" src="https://github.com/maikvandergaag/msft-extensions/assets/159920394/6abfd3ce-ec68-4c1f-9c39-b9f02b4f773c">
<img width="915" alt="3" src="https://github.com/maikvandergaag/msft-extensions/assets/159920394/15e031b5-0abb-4c80-b605-cc064ec27de2">
<img width="944" alt="4" src="https://github.com/maikvandergaag/msft-extensions/assets/159920394/43e5ce1e-777f-43c4-99a4-0c8788ee170b">
<img width="944" alt="5" src="https://github.com/maikvandergaag/msft-extensions/assets/159920394/d987073d-f1aa-424d-a563-a63e81ea474d">
[5.txt](https://github.com/maikvandergaag/msft-extensions/files/14270207/5.txt)

Please find the attached log files.

**Comment by maikvandergaag** [comment]
Hi @anupkosh the label "needs-reply" is a internal thing that's why it was removed. If I look at your log images it seems that it does not find the report.

Could you maybe share the files?

**Comment by anupkosh** [comment]
Thanks for your response. Specific PowerBI report is already deployed to the respective workspace successfully using the CICD  Pipeline tasks - Power BI Actions : Publish(Ver: 5.4.48). Once after the report got uploaded the parameters for the specific report are not getting updated. In the **UpdateParameter** task , I've selected the checkbox "_Update all datasets in workspace the dataset name will be ignored_" but no luck. (FYI. Initially I've unchecked this and tried, but no luck) Please find the below screenshot to show you the tasks that I have used in the CICD Pipeline. Please let me know how to proceed further. Thanks.

![image](https://github.com/maikvandergaag/msft-extensions/assets/159920394/f01b29eb-be03-4ff3-886c-42b78e04063a)

**Comment by anupkosh** [comment]
Hi Maik,

Please find the log files attached.Please review it and let me know how to
proceed further.

Thanks & Regards,
Anup Koshy Jacob

**Comment by anupkosh** [comment]
Waiting for your response.Thanks

**Comment by maikvandergaag** [comment]
Hi @anupkosh: sorry can't see the log file

**Comment by anupkosh** [comment]
Yesterday I've sent the logs from my mail id to this email id : [reply+BGEDCCWLYCDW3R7ZQPS2EMOD3IILNEVBNHHH6G4ELE@reply.github.com](mailto:reply+BGEDCCWLYCDW3R7ZQPS2EMOD3IILNEVBNHHH6G4ELE@reply.github.com).

Could you please check your email and confirm?

**Comment by anupkosh** [comment]
Hi Maik,
Please find the attached log files.

Thanks.

**Comment by anupkosh** [comment]
Just now I've sent the log files to the email id mentioned in earlier chat. Could you please check it and confirm?

**Comment by maikvandergaag** [comment]
Still not there try sending it to info at msftplaygound dot com

**Comment by anupkosh** [comment]
I've sent the logs file to info at msftplaygound dot com. Could you please check it and confirm.

Thanks

**Comment by anupkosh** [comment]
Still waiting for your response. Thanks

**Comment by maikvandergaag** [comment]
Hi @anupkosh: Two things:
- Extension is a community effort. This mean I maintain it in my free time so please do not expect to get answers in 5 min.
- Sending the logs might have gone wrong as I did not receive them. Could you maybe add them to the issues?

**Comment by anupkosh** [comment]
[ReleaseLogs_135.zip](https://github.com/maikvandergaag/msft-extensions/files/14313606/ReleaseLogs_135.zip)

Please find the attached logs. Thanks.

**Comment by anupkosh** [comment]
Please let me know if any update after reviewing the logs. Thanks.

**Comment by maikvandergaag** [comment]
Hi @anupkosh,

We use following api call on the datasets to retrieve the current parameters:
https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-parameters

If we have replaced values and if the parameter names are correct. We use this api call:
https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/update-parameters

To update the parameters. As the update call is not beign peformed there can be two problems. No found parameters on the dataset or the names are not correctly supplied. Are you maybe able to check by running the powershell locally or doing the api calls?

**Comment by allankichowdary** [comment]
Same issue for my side also. i am able to update using powershell call but not from task.

**Comment by maikvandergaag** [comment]
Could you share the code you used?

**Comment by allankichowdary** [comment]
[logs.txt](https://github.com/maikvandergaag/msft-extensions/files/14430353/logs.txt)
<img width="687" alt="task" src="https://github.com/maikvandergaag/msft-extensions/assets/58021805/ec192fe4-2417-4fd2-9885-c9df05d412a1">


Please find logs and task. 

NOTE : same json is working using powershell.

**Comment by allankichowdary** [comment]
@maikvandergaag / @anupkosh Also i am looking for some suggestions for automating jobs : 

1 . uploading reports and datasets
2. take ownership
3. updating parameters
4. Update gateway
5 Bind the gateway 
6. rebind reports to dataset
7. refresh dataset. 

is my order correct or any changes are required ? i am having little doubtful about 4 & 5 points about order is correct or only update gateway is fine? 

Some time connections are not mapping automatically and we need to select from drop down from setting . please guide here.

**Comment by maikvandergaag** [comment]
> [logs.txt](https://github.com/maikvandergaag/msft-extensions/files/14430353/logs.txt) <img alt="task" width="687" src="https://private-user-images.githubusercontent.com/58021805/308463128-ec192fe4-2417-4fd2-9885-c9df05d412a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDk1ODQsIm5iZiI6MTcwOTEwOTI4NCwicGF0aCI6Ii81ODAyMTgwNS8zMDg0NjMxMjgtZWMxOTJmZTQtMjQxNy00ZmQyLTk4ODUtYzlkZjA1ZDQxMmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OGVmMzQwZDk0OTNkNDRhMTczZGRhMGY4ZTNkN2Q3N2Y5MzUyMDczMzZlZjFjYjU5MjFhZDBhZGQ2ZWU1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nvvbZszqV_5LT6ZTutkZEHt68u6z0vSkbGgPF0-o7Js">
> 
> Please find logs and task.
> 
> NOTE : same json is working using powershell.

Could you share the peace of powershell that worked for you? To see if there are differences.

**Comment by allankichowdary** [comment]
<img width="762" alt="image" src="https://github.com/maikvandergaag/msft-extensions/assets/58021805/d141a2b4-a22b-47a8-b1ed-bdc6d1b25822">


before there are 2 apis for fetching data set and workspace id

**Comment by maikvandergaag** [comment]
What result do you get when calling this api? https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-parameters

**Comment by allankichowdary** [comment]
giving existing parameters in dataset

**Comment by maikvandergaag** [comment]
Closing issues due to no response?

**Comment by maikvandergaag** [comment]
Issue fixed in new release
