### ISSUE TITLE
Service Connection not being used that is earlier created

### ISSUE THREAD

**Issue by SatyamGupta621428** [maikvandergaag/msft-extensions#533]
**For which extension would you like to add a feature request?**

**Question**

I have created a new task in power BI releases pipelines-> power BI Action -Update Parameters
Here it is asking for service connection , so i already used one service connection in my earlier tasks, so i want to use that only. but is giving invalid error.
What to do now.
<img width="758" alt="Screenshot 2024-03-12 122713" src="https://github.com/maikvandergaag/msft-extensions/assets/105654004/573630d7-d37a-43db-b74c-ec3bf3824470">

**Comment by maikvandergaag** [comment]
@SatyamGupta621428, with a new version of the task we also had to adjust the service connection. So It could be the case that it is different.

Normally any approved service connection should also pop up in the drop down and you can use the service connections over the different tasks. So please check the configurations of the tasks.

**Comment by SatyamGupta621428** [comment]
Now i am cloning tasks so that service connection issue is resolved. In PowerBi Actions Update parameters there is one field 
Update parameter Json in which what value will go . I need help.

**Comment by maikvandergaag** [comment]
In the hover there should be a example.

**Comment by SatyamGupta621428** [comment]
I have used the JSON but it is giving invalid request when i am creating release. SO what can be the error??

**Comment by maikvandergaag** [comment]
Please include a variable called system.debug and set the value to true.

**Comment by SatyamGupta621428** [comment]
Bro error is coming again invalid request although i added system.debug variable and set its value to true

**Comment by maikvandergaag** [comment]
Could you then share more info. With the info share now I can not help you.
