### ISSUE TITLE
api to update an existing power bi app

### ISSUE THREAD

**Issue by cyptus** [maikvandergaag/msft-extensions#535]
**For which extension would you like to add a feature request?**
power bi rest api

**Is your feature request related to a problem? Please describe.**
deployment pipelines and rest api's do provide automatic ways to deploy changes into reports. these changes are not reflected in the apps depending on this reports. every app needs to be manually updated every time. that breaks every continues integration and creates A LOT of manual work.

**Describe the solution you'd like**
add "app patch/update" functions to power bi rest api: https://learn.microsoft.com/en-us/rest/api/power-bi/apps
currently there are only read functions.
the endpoints should provide the option to "refresh" the reports that are already embedded in the app.

**Describe alternatives you've considered**
flags/options to automatically update an app on changes of the contents or scheduled updates

**Additional context**
a lot of existing issues have been marked as "completed", but there is still no API available to update apps automatically. these issues have **not** been completed: #294, #353, #121, #113

**Comment by maikvandergaag** [comment]
@cyptus We do not manage the power bi rest api's. So this should be a feature request with Microsoft. If they open up these API's then we can extend the extension with these actions.
