### ISSUE TITLE
Steps to perform complete deployment in Azure DEVOPS 

### ISSUE THREAD

**Issue by vinayprakash893** [maikvandergaag/msft-extensions#541]
HI @maikvandergaag ,

Im perfoming file.rdl deployment to powerBI

Step1: using upload task
- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
            displayName: 'workspace1 : Upload Report'
            inputs:
              PowerBIServiceEndpoint: 'sasa'
              WorkspaceName: ws1
              PowerBIPath: '$(System.DefaultWorkingDirectory)/artifact/add/ws1'
              Create: false

Step2: once the rdl file is deployed, im getting the below error in powerBI portal
![image](https://github.com/maikvandergaag/msft-extensions/assets/38611502/5b24bc3f-ed2b-4f7f-a663-269bc1a74e40)

Step3: Manual fix the issue
when i click on "manage" and manually TAKEOVER the below, it changes to my ownership and it works perfectly. 

![image](https://github.com/maikvandergaag/msft-extensions/assets/38611502/6967f5d4-812d-4296-aeff-7138555c1b06)

Step4: To achieve this over CICD, i have added 

- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
            displayName: 'Power BI Action: TakeOwnership'
            inputs:
              PowerBIServiceEndpoint: 'sasa'
              Action: TakeOwnership
              WorkspaceName: 'ws1'
              DatasetName: 'Ds1'
            condition: succeededOrFailed()

im getting error like the below ISSUE
https://github.com/maikvandergaag/msft-extensions/issues/450

I even tried using the below task

- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
            displayName: 'Power BI Action: UpdateSqlCreds'
            inputs:
              PowerBIServiceEndpoint: 'powerbi-actions-cicd'
              Action: UpdateSqlCreds
              WorkspaceName: 'ws1'
              ReportName: 'report1'
              Username: $(SQLusername)
              Password: $(SQLpassword)
            condition: succeededOrFailed()
            
![image](https://github.com/maikvandergaag/msft-extensions/assets/38611502/d17198f0-2428-48a6-9632-751750ea666c)

Could you please let me know the actual steps needed to achieve this..?

**Comment by vinayprakash893** [comment]
Hi Team, Any update on this..?

**Comment by maikvandergaag** [comment]
Hi,

Sorry it has been a busy week. It seems the your second step isn't able to find the report. Could you check this?

Maybe you should also try to not take the ownership through the portal.

**Comment by vinayprakash893** [comment]
Hi @maikvandergaag ,

Thank you for providing response,  

The second step is the error when we deploy the report "using : Upload Report'"
because it does not get the access to SQL server using the **service account** to deploy,  as error stating. 

even if i use **Step 4** to get Ownership( which is not required because it already deployed with service account only)
and using **step 5** to update SQL creds, its giving same error as **Step2** 


now to make this work, i should takeover manually as **STEP3** which uses my credentials as i will be the owner of that report/data

do i need use any of the options like PatchDatasourceCredentials, or does this extension has the capability ..?
https://github.com/microsoft/PowerBI-Developer-Samples/blob/master/PowerShell%20Scripts/PatchDatasourceCredentials.ps1

**Comment by maikvandergaag** [comment]
There is a new action to set database credentials but not sure if that works with your use case

**Comment by vinayprakash893** [comment]
Can you provide the New Action name..?

**Comment by vinayprakash893** [comment]
Hi @maikvandergaag , Any update..?

**Comment by maikvandergaag** [comment]
This one: "SetSQLDatasourceSPCredentials"
