### ISSUE TITLE
Publish report with live connection returning BadRequest

### ISSUE THREAD

**Issue by Learn-PBI** [maikvandergaag/msft-extensions#544]
**For which extension would you like to add a feature request?**

**Question**

I am trying to setup deployment for a report with a live connection but the Publish Report action is showing a BadRequest error when trying to upload this file. The pipeline has no issues creating a workspace, assigning users, publishing a model file with direct query connections, updating this datasets parameters, but on the next Upload report step, when trying to upload the report with a live connection data source - its throwing an error.

Are .pbix files with live connections not supported through the upload report action? Is there another method to deploy these reports?

Let me know if there are any logs or anything to help with any context on the issue. Thanks for any help!

**Comment by maikvandergaag** [comment]
I think it should work. The extension uses the Power BI API under the cover and as far as I can see it is not a known limitation.

https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import#post-import-example

So I think it is something else.

**Comment by Learn-PBI** [comment]
It was me, woops! 

Connected dataset of the report with the live connection needs to be in a workspace the SP created (or is admin on?) - thanks for the quick response and sorry for user error!

Thanks :)
