### ISSUE TITLE
Update parameters Task successful but doesn't update the parameters in dataset  

### ISSUE THREAD

**Issue by gopinaralasetty** [maikvandergaag/msft-extensions#548]
**Describe the issue**
A clear and concise description of what the issue is.

**Extension **
 - Extension: [Power BI Actions]
 - Version: [5*]

**Expected behavior**
Should update the dataset parameters

**Situation (please complete the following information):**

 - Agent type: private agent with windows
 - Autentication: service principle 
 - Extension Version: 5*
[ReleaseLogs_458.zip](https://github.com/maikvandergaag/msft-extensions/files/15212405/ReleaseLogs_458.zip)

**Log info**
Please add the log file of the agent in debug mode [Add the variable system.debug with the value 'true ' to your pipeline]

**Additional information**

**Comment by gopinaralasetty** [comment]
@maikvandergaag  - The Task is successful, but it doesn't update the parameter in the dataset.

Datasource type is azure databricks and we are using the databricks SQL serverless

**Comment by maikvandergaag** [comment]
Could you share logs after you have done with the variable system.debug added with the value true

**Comment by nhvduy** [comment]
[log.txt](https://github.com/maikvandergaag/msft-extensions/files/15226444/log.txt)
This is part of the logs after I changed some values, Maik.

**Comment by maikvandergaag** [comment]
@nhvduy thanks but is this the whole file. I think I miss a part.

**Comment by gopinaralasetty** [comment]
@maikvandergaag  - i have attached all the log in zip file- can you please have a look

**Comment by pphidev** [comment]
Hi @gopinaralasetty,

Do you 'takeover' the dataset with the service principal _before_ updating the parameters?

Kind regards,

Pim

**Comment by nhvduy** [comment]
Hi @pphidev  how can we takeover the dataset with the service principal?
From the workspace setting, user can takeover the dataset, but we cannot loggin as service principal.

**Comment by pphidev** [comment]
Hi @nhvduy,

You can use the `TakeOwnership` action. 

Example if you use a yml file setup:

```yml
- task: PowerBIActions@5
   displayName: 'Take dataset ownership'
   inputs: 
      PowerBIServiceEndpoint: ${{ variables.serviceConnection }}
      Action: 'TakeOwnership'
      DatasetName: ${{ variables.dataSetName }}
```

Next that, make sure the parameter type is not set to `any` in Power BI (Desktop) but to e.g. `text`. As far as I know, `type = any` will not work. 

Kind regards,

Pim

**Comment by gopinaralasetty** [comment]
> Hi @gopinaralasetty,
> 
> Do you 'takeover' the dataset with the service principal _before_ updating the parameters?
> 
> Kind regards,
> 
> Pim

Hi @pphidev 
i am using the classic pipeline 
yes i did takeover the dataset

![Screenshot 2024-05-07 150134](https://github.com/maikvandergaag/msft-extensions/assets/112641263/6d77b38d-0e14-4658-b13c-08173f88850d)

**Comment by pphidev** [comment]
> > Hi @gopinaralasetty,
> > Do you 'takeover' the dataset with the service principal _before_ updating the parameters?
> > Kind regards,
> > Pim
> 
> Hi @pphidev i am using the classic pipeline yes i did takeover the dataset
> 
> below are the steps of the task in my release pipeline ![Screenshot 2024-05-07 150134](https://private-user-images.githubusercontent.com/112641263/328531325-6d77b38d-0e14-4658-b13c-08173f88850d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcyOTYsIm5iZiI6MTcxNTA4Njk5NiwicGF0aCI6Ii8xMTI2NDEyNjMvMzI4NTMxMzI1LTZkNzdiMzhkLTBlMTQtNDY1OC1iMTNjLTA4MTczZjg4ODUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMzAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTQ1NzA4M2IzZDg0Nzg3YmM4MTNiZjA4Y2YxYWM4OWIzNmIwNGYyYTE5ZWI4NGIwMGU3ZmE4MzI4YzkwMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jo6MVWFGMN_f76Qzw2bizq6oa75Oy1yv4VdxdySvlWg)

Hi @gopinaralasetty,

What is the `type` of your parameter?

![image](https://github.com/maikvandergaag/msft-extensions/assets/128486645/d862a414-4e41-4a62-9ce9-0dc1817aa362)

**Comment by gopinaralasetty** [comment]
Hi @pphidev 

The parameter Type is Test

**Comment by pphidev** [comment]
> Hi @pphidev
> 
> The parameter Type is Test

`Test` is (I guess) the **value** of the parameter. But I refer to the **type** of the parameter. The default value for the type is `Any`. However, `Any` is not supported by the Power BI API (and therefore also not supported by the Power BI Actions). 

Available types are:
![328534585-d862a414-4e41-4a62-9ce9-0dc1817aa362](https://github.com/maikvandergaag/msft-extensions/assets/128486645/9a1f1443-d27a-45bb-aab5-b5ef89311db5)

**Comment by gopinaralasetty** [comment]
Sorry for the Typo -- The parameter is Text only

**Comment by gopinaralasetty** [comment]
@maikvandergaag , can you please check on it

**Comment by maikvandergaag** [comment]
Still missing some parts in the log.
