### ISSUE TITLE
Please add support to update datasource for all the reports/datasets 

### ISSUE THREAD

**Issue by Prashanth-PS** [maikvandergaag/msft-extensions#55]
Please add support to update datasource for all the reports/datasets within a PowerBI workspace, as how it is available for Uploading multiple .pbix report files from a folder using wild cards. Without this it is difficult to go through dataset update for each of the reports individually. 
Wildcard consideration is much appreciated. 

Regards,
Prashanth

**Comment by maikvandergaag** [comment]
HI Prashanth,

About which extension are you talking?

**Comment by Prashanth-PS** [comment]
> HI Prashanth,
> 
> About which extension are you talking?

This is for Power BI Actions extension

**Comment by maikvandergaag** [comment]
This actions has multiple actions and also contains a actions for updating the datasource for a DirectQuery report. At this moment I'm working on a Major update of the extension that will add additional support.

Besides that you should also be able to upload multiple reports at once by using a wildcard.

**Comment by maikvandergaag** [comment]
Functionality is added in version 3.2.6
