### ISSUE TITLE
Add New Lines Characters Has Unexpected Results

### ISSUE THREAD

**Issue by jzserai** [maikvandergaag/msft-extensions#56]
When I check this box, the entire file contents are pushed together making it very difficult to read.

If I leave it unchecked, I get only the first line of the file.

I would like the variable to store the file contents exactly so if I add the variable to a custom email task, it will appear correctly to the recipient.

The file is a text file, of course.

Thank you
[DeployResults_Sanitized.txt](https://github.com/maikvandergaag/msft-extensions/files/2676604/DeployResults_Sanitized.txt)

**Comment by maikvandergaag** [comment]
Sorry, had several discussion previously with the team and at that time it wasn't possible because variables do not have that functionality.
