### ISSUE TITLE
PowerBI Action : Publish - Exception on service connection

### ISSUE THREAD

**Issue by LekhaSahdev** [maikvandergaag/msft-extensions#60]
While trying to use the extension - getting the below error. I have created the Azure application - with all specified permission.
![image](https://user-images.githubusercontent.com/32700215/50813542-c1173580-133c-11e9-923d-14192b46490b.png)

![image](https://user-images.githubusercontent.com/32700215/50813696-3c78e700-133d-11e9-9560-bd61f62cc2c6.png)

![image](https://user-images.githubusercontent.com/32700215/50813743-64684a80-133d-11e9-92b3-edc6e47ae8fb.png)

**Comment by maikvandergaag** [comment]
There are a few things you could check and try:
- Check the type of the application it should be native.
- Check if you have granted the permissions.
- Check if the user itself has enough permissions within power-bi.

If this all is not the problem I would suggest recreating the application and keep everything default and only add the Power BI permissions.

**Comment by maikvandergaag** [comment]
Any progress regarding your issue or else I will close it.

**Comment by maikvandergaag** [comment]
Should work now.
