### ISSUE TITLE
Problem with token acquisition

### ISSUE THREAD

**Issue by KateHamster** [maikvandergaag/msft-extensions#64]
Hello, we were trying to create a release pipeline to publish reports to PowerBi. However, we encounter the following problem:
![image](https://user-images.githubusercontent.com/11301284/51307907-235cee00-1a41-11e9-8e55-f336d940ab4b.png)
I have searched your code and I suppose that the error is caused by the line 34 in the powerbi.psm1 file. According to the docs of Microsoft ( https://docs.microsoft.com/en-us/previous-versions/azure/mt459145(v%3Dazure.100) ) this method should take two paramters, however in your code it takes three parameters. 
How can this issue be solved? Thank you in advance for your explanation, if I have made a mistake about the reason of the error.
I hope that this issue will be solved soon as we really want to use your extension.

**Comment by maikvandergaag** [comment]
Sorry for the late response. What type of application are you using

**Comment by maikvandergaag** [comment]
Use the Native type application. Use the guide on this documention page: https://docs.microsoft.com/en-us/power-bi/developer/register-app

**Comment by dajxr8** [comment]
Hi I'm encountering the same issue using your extension on Azure DevOps :

![image](https://user-images.githubusercontent.com/7556183/51920294-69249980-23e5-11e9-95ab-47c51933f73c.png)

Thanks for the help :).

**Comment by maikvandergaag** [comment]
How did you configure the application? And what kind of user are you using?

**Comment by dajxr8** [comment]
I created a new App on the "App Registrations Service" on Azure then I set the required Api Permissions ( Power Bi Service ).
I used a basic user from azure AD.
Am I missing something ?

Thanks.
