### ISSUE TITLE
Publish PBIX: Error acquiring token

### ISSUE THREAD

**Issue by ruoccofabrizio** [maikvandergaag/msft-extensions#65]
Hi,

I have the following error trying to acquire token to publish a PBIX. 

![image](https://user-images.githubusercontent.com/22171838/51425731-4e317880-1be0-11e9-9ddf-a650782cd31a.png)

Exception calling "AcquireToken" with "3" argument(s): "wstrust_endpoint_not_found: WS-Trust endpoint not found in metadata document"

The same error is shown trying to connect directly with PowerShell to get token, without prompting user for credential. Could this be related to newer version of module, removing this method?

Thanks.

**Comment by maikvandergaag** [comment]
What type of Azure Active Directory application are you using?

**Comment by ruoccofabrizio** [comment]
I have tried both with native and web

**Comment by maikvandergaag** [comment]
Could you send a screenshot of the configured Azure AD Native application?

**Comment by ruoccofabrizio** [comment]
![image](https://user-images.githubusercontent.com/22171838/51699626-87694e80-200d-11e9-8e07-12aa297ad648.png)

**Comment by maikvandergaag** [comment]
Could you also show the overview screen of the app

**Comment by ruoccofabrizio** [comment]
![image](https://user-images.githubusercontent.com/22171838/51701119-0f048c80-2011-11e9-8a94-c7deee0f9bb2.png)

**Comment by maikvandergaag** [comment]
Thanks, I also had issues authenticating to azures with some applications could you retest it with a new application configured following the steps in this article of microsoft:

https://docs.microsoft.com/en-us/power-bi/developer/register-app

**Comment by ruoccofabrizio** [comment]
I will try and keep you up to date

**Comment by ruoccofabrizio** [comment]
Tried again with a new native app, without any success :(

**Comment by maikvandergaag** [comment]
same issue

**Comment by maikvandergaag** [comment]
did you mention in the original request that the same issue occurs when trying it on-prem? And are you using the hosted agents?

**Comment by ruoccofabrizio** [comment]
I have tried hosted agents and a personal built one, without any luck. Never tested on-prem

**Comment by maikvandergaag** [comment]
oke what did you mean with this line then? "The same error is shown trying to connect directly with PowerShell to get token, without prompting user for credential. Could this be related to newer version of module, removing this method?"

**Comment by maikvandergaag** [comment]
I have to investigate further, you are the first user that encounters this issue. Did you also granted the persmissions?

**Comment by ruoccofabrizio** [comment]
"I have to investigate further, you are the first user that encounters this issue. Did you also granted the persmissions?" Yes, I did


"The same error is shown trying to connect directly with PowerShell to get token, without prompting user for credential. Could this be related to newer version of module, removing this method?" I tried my app id using a powershell script to connect using the same AcquireToken method that fails. It seems to work when I ask for credential prompting the Azure login window. Trying with user credential it does not work.

**Comment by maikvandergaag** [comment]
Could you share the script that u used to try it. I have some time tomorrow and will try to find what is going wrong

**Comment by ruoccofabrizio** [comment]
sure, thanks!

`function GetAuthToken
{
    if(-not (Get-Module AzureRm.Profile)) {
      Import-Module AzureRm.Profile
    }

    $redirectUri = "urn:ietf:wg:oauth:2.0:oob"

    $resourceAppIdURI = "https://analysis.windows.net/powerbi/api"

    $authority = "https://login.microsoftonline.com/common/oauth2/authorize";

    $authContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" -ArgumentList $authority

    $authResult = $authContext.AcquireToken($resourceAppIdURI, $clientId, $redirectUri, "Auto")

    return $authResult
}`

Using this function to get an auth token (with same clientId that does not work in the DevOps  extension) I am prompted for credential and the PBIX upload does work. 

If I try to pass userCredential in the acquireToken method to avoid prompting for credentials, I got the same error I have in the DevOps extension

**Comment by maikvandergaag** [comment]
issue should be fixed in new release
