### ISSUE TITLE
Version number counter 

### ISSUE THREAD

**Issue by joelwang0528** [maikvandergaag/msft-extensions#69]
Got this error:
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"This request expects an object in the request body, but the supplied data could not be 
deserialized.","typeName":"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"RequestContentException","errorCode":0,"eventId":3000}
At line:94 char:13

This should be related to this problem with Invoke-RestMethod: https://stackoverflow.com/questions/50044942/issue-when-updating-build-definition-using-the-rest-api-of-vsts

Following fix works for me:
Invoke-RestMethod -Method Put -Uri $defUri -Headers $devOpsHeader -ContentType "application/json" -Body ([System.Text.Encoding]::UTF8.GetBytes($definitionJson)) | Out-Null

**Comment by maikvandergaag** [comment]
Accepted your pull request. Issue should be fixed
