### ISSUE TITLE
Question: How to set WorkspaceName from File content to variable?

### ISSUE THREAD

**Issue by bridgetashley** [maikvandergaag/msft-extensions#74]
Can I set the Workspace Name in **Power BI Action: Publish** task to a variable?

![image](https://user-images.githubusercontent.com/4041019/52414968-5f68f900-2aab-11e9-99ca-9c0009c00599.png)

![image](https://user-images.githubusercontent.com/4041019/52414950-54ae6400-2aab-11e9-9ce3-1af6b2cfcda0.png)

**Comment by maikvandergaag** [comment]
yes you can, save the name in a variable and add this in the workspace name field '$(variablename)' were variable name is the name of your variable
