### ISSUE TITLE
[VersionCounter] Update Build variable from Release Pipeline

### ISSUE THREAD

**Issue by MysterDru** [maikvandergaag/msft-extensions#79]
It would be nice if the version counter task had the ability to override the build id that is being updated.

I'd like to use this task from my release pipeline and whenever the app is deployed to production, update the minor version number variable on the build definition from the release pipeline.

Right now, I have to do that manually (which can easily be forgotten).

The task script grabs the build id from from the environment variables currently.
`$buildId = $env:BUILD_BUILDID`

It seems like it would be easily feasible to update that to grab the id from the vsts/devops input, and if not specified, default to `$env:BUILD_BUILDID`

**Comment by maikvandergaag** [comment]
Hi Drew sounds like a great feature can we have a small conversation some time to discuss it
