### ISSUE TITLE
version variabele not updated

### ISSUE THREAD

**Issue by codehunter13** [maikvandergaag/msft-extensions#80]
Hi,

The variable used as version is not updated in the next task.

Two tasks:
![image](https://user-images.githubusercontent.com/7559059/54813063-f4efcf00-4c8c-11e9-9c36-28133c52c273.png)

The patch number of SoftwelNgVersion2 var should be updated to 78:
![image](https://user-images.githubusercontent.com/7559059/54813111-1a7cd880-4c8d-11e9-82c1-11a248ba3a4c.png)

But its not if i check it in the show all build variables output:
![image](https://user-images.githubusercontent.com/7559059/54813217-5adc5680-4c8d-11e9-8fd1-30bbe07f91f2.png)

Any idea?
Thx

**Comment by maikvandergaag** [comment]
That's correct, the variable is changed but you will not see the change until you run the build or release again. This is because the variables are loaded at the beginning of the Job. if you add another Job it will work.

**Comment by codehunter13** [comment]
Indeed. Than it works.
 But it seems that the variabeles are loaded when a job is queued and not when it is started. so if i queue multiple jobs thy all use the same variabele:
var is 1
queue1 
queue2

run1 => it uses 1 and updates to 2
run2 => it uses 1 and updates to 3

queue3
=> it uses 3 and updates to 4 

Do you see any workaround?

**Comment by maikvandergaag** [comment]
I haven't tested it in a scenario like that I will have to check that out
