### ISSUE TITLE
Facing issue with path

### ISSUE THREAD

**Issue by ManikantaNani** [maikvandergaag/msft-extensions#81]
##[error]Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'D:\a\_tasks\PublishPowerBIFile_c9e44e10-97ef-11e7-8bd5-3dc66515223e\1.2.5\ps_modules\PowerBi\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' because it does not exist."

**Comment by maikvandergaag** [comment]
Hi ManikantaNani,

The extension you are using is not supported anymore as this moment please try the new extensions: Power BI Actions that has the same activity.
