### ISSUE TITLE
UpdateDataSource: Operation is not Supported

### ISSUE THREAD

**Issue by Singley** [maikvandergaag/msft-extensions#84]
Hi,

I'm working with the Power BI Actions task to set up CI / CD for our Power BI reporting.  My goal is that I can deploy the same file to a DEV Workspace and a PROD workspace, connected to different database environments (Dev + Prod, respectively) without having to update parameters, connection strings, and credentials manually.  

The automated deployment is working, but I'm trying to figure out the next step- updating the datasource to point to PROD.

When using the 'UpdateDataSource' action I'm currently getting the following error:
![image](https://user-images.githubusercontent.com/29473162/55833658-aa1fe500-5add-11e9-9117-422ec4c568a0.png)

Any insight is appreciated.  

Thanks,

Mark

**Comment by maikvandergaag** [comment]
Hi Mark,

What kind of data source are you using in the report?

**Comment by Singley** [comment]
Standard Azure SQL Database.  I did, however, set it up using Parameters
within the report to attempt to make it a little more dynamic- do you think
that's related?

[image: image.png]

**Comment by maikvandergaag** [comment]
Yes I think so, certainly because the error specifies the data source isn't supported

**Comment by Singley** [comment]
@maikvandergaag I confirmed that removing the parameters in the SQL connection have enabled this operation to work.  I'm going to jump on another feature request that's open with some additional details.

Thanks!

Mark
