### ISSUE TITLE
Trigger Azure DevOps Pipeline: How to choose stage?

### ISSUE THREAD

**Issue by paaland** [maikvandergaag/msft-extensions#85]
We use stages in the release pipeline to differentiate "dev", "test" and "prod" which all typically have their set of variables for connections strings etc.

I want to use you extension to create a "bundle release" that triggers several single release pipelines. But there is no way to choose which of the stages to trigger.

**Comment by maikvandergaag** [comment]
That feature isn't build in yet. I will mark this as a feature request

**Comment by maikvandergaag** [comment]
Sorry for the late response due to some personal stuff I haven't been able to proccess this hope to be able to do this in august
