### ISSUE TITLE
If old server cannot be found result in error

### ISSUE THREAD

**Issue by edkreuk** [maikvandergaag/msft-extensions#86]
Hi Maik,

We just started to use your component and we 're running into some issues.

Update Old Server to New Server

If the Old server string cannot be found these wil result in an error

##[error]Dataset doesn't contain a datasource that matches selector #1

Steps to reproduce

Create pbix file with a server called test
Create Release
Create taks  1,2,3 
      Publish PowerBI report
      Update datasource connection from Old server called Test to new server called test
      Update datasource connection from Old server called Prod to new server called test

I'm adding the last task because some people create reports on a Prod environment and If I publish them to a Test Workspace then need to look to the testserver as well.

The last task will create a error:
##[error]Dataset doesn't contain a datasource that matches selector #1

Is this by design or not.

**Comment by maikvandergaag** [comment]
For the old server you need to fill in the old connection server. In order to find the correct connection.
This is by design as the PowerBI API does not support a different method

**Comment by edkreuk** [comment]
Ok, thanks for the quick reply
