### ISSUE TITLE
Space in DataSetName with result in Error

### ISSUE THREAD

**Issue by edkreuk** [maikvandergaag/msft-extensions#87]
Hi Maik,

Our PBIX files have space in the name's, like Kwaliteit KT01.pbix. When using this name to update the datasource connection is result in a failure:
##[error]Cannot bind argument to parameter 'Set' because it is null.

Is there a workaround., I tried to use single quotes and double quotes.

After removing the space updating the datasource was working fine.

**Comment by maikvandergaag** [comment]
Which action are you using of the extension.

**Comment by edkreuk** [comment]
update the datasource connection

**Comment by maikvandergaag** [comment]
You need the fill in the correct information, the datasource is not always the same as the pbix file name

**Comment by edkreuk** [comment]
In this it case it is the same, Dataset name with spaces is not working but without cases is working(replaced space with underscore)

**Comment by maikvandergaag** [comment]
Ah oke, will try to fix it this week

**Comment by maikvandergaag** [comment]
Sorry for the late response due to some personal stuff I haven't been able to proccess this hope to be able to do this in august
