### ISSUE TITLE
Update Datasource Connection not working as expected

### ISSUE THREAD

**Issue by edkreuk** [maikvandergaag/msft-extensions#88]
Hi Maik, I've a question

We have multiple PowerBI-reports in the same workspace, but with different connection-types, some have a AAS-connection, others have a SQL-connection. When we use the Action “Update Datasource Connection” to update all the connections for AAS from a Test-server to a Prod-server, the task gives an Error “##[error]Dataset doesn't contain a datasource that matches selector #1”. It looks like this error is thrown because there are reports that don’t have a connection to a AAS-server but SQL-server and this task tries to replace it for all reports, not looking if it is a AAS-connect on forehand.

Specifying the property Dataset name doesn’t help. And also checking the option “Continue on error” doesn’t help, because it then skips the whole step, instead of skipping one report.

What I would expect is that the task loops trough all the PowerBI-reports in the workspace, tries to do the Find-and-replace, and ignores(based on “Continue on error”-property) all the reports where is cannot match the “Old Servername” or “Old Database”. 

 
![PowerBIAction](https://user-images.githubusercontent.com/20183155/56568865-29bab300-65b8-11e9-9256-5f7338f3882d.png)
  Could you please advice, thanks

**Comment by maikvandergaag** [comment]
Sorry for the late response due to some personal stuff I haven't been able to proccess this. In this feature the query for changing the datasets is tried on every dataset. So what you try to do isn't possible
