### ISSUE TITLE
Cannot refresh data set

### ISSUE THREAD

**Issue by KateHamster** [maikvandergaag/msft-extensions#89]
Hello,

I was trying to use a Refrech Dataset feature, however I met the following error:

> ##[error]Invalid dataset refresh request. Number of refresh requests in last 24 hours exceeded limit

It was the first time that we tried to refresh a dataset, so I don't understand why it returns such error. Do you have any ideas?

**Comment by maikvandergaag** [comment]
No did you refresh the dataset by hand?
