### ISSUE TITLE
[Version Counter] "The variables can not be found on the definition: , , "

### ISSUE THREAD

**Issue by ArchSerpo** [maikvandergaag/msft-extensions#92]
I have facing an issue where it is saying the variables can not be found on the definition. Here are some screenshots of the json returning by the definition API call

This occurs on a hosted VS2017 agent

![image](https://user-images.githubusercontent.com/16471369/57172795-ff4edc80-6e78-11e9-85e0-603df0a1f5eb.png)

![image](https://user-images.githubusercontent.com/16471369/57172792-f52cde00-6e78-11e9-9c4d-1c37b66161e1.png)

Here is the output from the build with debugging on

![image](https://user-images.githubusercontent.com/16471369/57172822-74baad00-6e79-11e9-87c1-f6ed83902388.png)

My PowerShell is a bit rusty, does this line need need an extra () around $VersionNumber?

`    if ($definition.variables.$VersionVariable) {
`

Edit - running a snippet of the script locally, variables is empty - 

`@{options=System.Object[]; triggers=System.Object[]; variables=; retentionRules=System.Object[]; properties=; tags=System.Object[]; _links=; buildNumberFormat=$(versionnu
mber); jobAuthorizationScope=projectCollection; jobTimeoutInMinutes=60; jobCancelTimeoutInMinutes=5; process=; repository=; processParameters=; quality=definition; author
edBy=; drafts=System.Object[]; queue=; id=2; name=BlazorPlay-CI; url=https://dev.azure.com/dev/f71c8c3b-f0ee-48d0-b2fb-4606f8258e03/_apis/build/Definitions/2?revis
ion=16; uri=vstfs:///Build/Definition/2; path=\; type=build; queueStatus=enabled; revision=16; createdDate=2019-05-04T02:16:11.763Z; project=}`

If I follow the API link via my browser I can see that data

![image](https://user-images.githubusercontent.com/16471369/57173107-4be8e680-6e7e-11e9-8421-6b01caa8ab4a.png)

**Comment by maikvandergaag** [comment]
Hi ArchSepo,

You have to supply the versionvariable without the characters ($()).

**Comment by ArchSerpo** [comment]
Thank you so much :)
