### ISSUE TITLE
Readme should mention TriggerPipeline task is windows-only

### ISSUE THREAD

**Issue by renefritze** [maikvandergaag/msft-extensions#94]
At least I didn't see any hint of that and only noticed when my build failed on first run.

**Comment by maikvandergaag** [comment]
Sorry for the late response due to some personal stuff I haven't been able to proccess this hope to be able to do this in august

**Comment by renefritze** [comment]
I should've mentioned I used a pretty straightforward workaround with a dependent job that runs a windows host: https://github.com/dune-community/dune-xt-super/blob/master/.ci/azure-job-template.yml#L24
