### ISSUE TITLE
The variables can not be found on the definition: , ,

### ISSUE THREAD

**Issue by evamodrakova** [maikvandergaag/msft-extensions#95]
Hi Maik,

I have this error: **The variables can not be found on the definition: , ,** when I try to run build pipeline with your extension for version number counter.
Maybe I miss some configuration so I would be very happy if you could somehow guide me.

My settings:
for version number counter plugin, tasks tab:
The saved version variable: '1.0.0'
Maximum value of the patch number: 1000
Maximum value of the minor number:100

variables tab:
I added variable named versionnumber with value '1.0.0'

for options tab:
Build number format: $(versionnumber)

Also I would like to know where I can find run-task.ps1 file.

I saw here same error but honestly I do not understand the resolution. I am so sorry.

I am looking for your answer.
Thank you,
Eva

**Comment by maikvandergaag** [comment]
Hi Eva, no problem can you share a screenshot of your configuration

**Comment by evamodrakova** [comment]
Hi Maik,

yeah, sure:
for tasks
![image](https://user-images.githubusercontent.com/50880237/58124728-2c3c1700-7c0f-11e9-896b-1b7cb02a67af.png)

for variables
![image](https://user-images.githubusercontent.com/50880237/58124740-3b22c980-7c0f-11e9-8ec3-43915d76185c.png)

for options
![image](https://user-images.githubusercontent.com/50880237/58124796-5988c500-7c0f-11e9-8fd7-7b89e90416e4.png)

Eva

**Comment by maikvandergaag** [comment]
Hi Eva,

The saved version variable should be the name of the variable. In your case it should be versionnumber.

**Comment by evamodrakova** [comment]
HI Maik,

thank you, it is working. Great.

I have another question. I set that maximum value for patch is 1000, after that number minor value will increased. What if I need to increase that number sooner for example I have version 1.0.359 and now I need version 1.1.0.
What/where should be changed?

Thank in,
Eva

**Comment by maikvandergaag** [comment]
Great to hear! If you want that the maximum patch value should be 359

**Comment by evamodrakova** [comment]
Hi Maik,

I will test every possibilities and if I will have any other questions I will write you.

Thank you so much for your time.

Eva

**Comment by maikvandergaag** [comment]
Np
