### ISSUE TITLE
Version number sync in build and release pipeline

### ISSUE THREAD

**Issue by evamodrakova** [maikvandergaag/msft-extensions#97]
Hi Maik,

I am curious, is it possible to somehow connected version number in build pipeline with release pipeline? I mean, we put version number counter only in build pipeline and this version will be send into release pipeline so versions will be sync. We would like to use CI and CD for pipelines.
If it is possible, how we can make it, for example save version number in some external file?

Thank you for answer,
Eva

**Comment by maikvandergaag** [comment]
Hi Eva,

If you have a specific name for you build in your CI and want to use that name/version for your CD you can use the build in variable "Release.Artifacts.{alias}.BuildNumber" make sure you also add a revision or else the possibility arises were you will have multiple releases with the same name.
