### ISSUE TITLE
Power BI Actions

### ISSUE THREAD

**Issue by evanmcneal** [maikvandergaag/msft-extensions#98]
I would like to see an action that allows us to take a folder of PBIX files and publish them all to a workspace. Instead of one PBIX at a time just allow a whole folder to be deployed to a common workspace. Right now I have a release pipeline with over 15 Reports being published to one workspace and more will be added to the repo by the devs in the future and will maintain the same workspace. Workspaces are determined by the folders in our repos. So basically just take the folder and upload all of the pbix files to the workspace (or create the wrokspace) that has the same name as the folder that is selected. This would help us roll out many more Reports without have a dedicated person to update the pipelines each time.

**Comment by maikvandergaag** [comment]
Hi thank you for your request, but this feature should already be buildin.

If you enter a folder path in the source file and end it with *.pbix it should search for all pbix files in the folder.

Let me know if it works as expected.
